### ISSUE TITLE
Update icon 634 which has no transparency

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#1003]
Icon 634, named `icon #7914` uses an image
 - too small
 - with no transparency.

This icon is being used in currently published snippets. 

@stsegovia-moz  can you please fix?

**Comment by glogiotatidis** [comment]
Also check these *currently published* icons:

 - https://snippets-admin.mozilla.org/admin/base/icon/633/change/ (no transparency)
 - https://snippets-admin.mozilla.org/admin/base/icon/631/change/ (transparent, but with white border pixels)
 - https://snippets-admin.mozilla.org/admin/base/icon/557/change/ (low quality, esp in dark mode)
 - https://snippets-admin.mozilla.org/admin/base/icon/542/change/  (transparent, but with white border pixels)
 - https://snippets-admin.mozilla.org/admin/base/icon/532/change/   (transparent, but with white border pixels)
 - https://snippets-admin.mozilla.org/admin/base/icon/456/change/ (pocket icon needs white detail inside, instead of transparent?)

**Comment by stsegovia-moz** [comment]
Thank you for the heads up! I'll see what I can do for these.

-Steve

**Comment by glogiotatidis** [comment]
>     * https://snippets-admin.mozilla.org/admin/base/icon/532/change/   (transparent, but with white border pixels)

Fixed this last one with some editing. 

Thanks for working on those @stsegovia-moz ! :cake:

**Comment by stsegovia-moz** [comment]
Perfect! There's a few more that need to be fixed, but I haven't had a
chance to bug the design team quite yet. But that is on my radar.


-Steve
