### ISSUE TITLE
Switch Snippets CDN to own AWS acc

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#1026]

**Comment by glogiotatidis** [comment]
We will stay with CloudFront and we will move the CDN distribution under our AWS account. The process is tracked in https://github.com/mozmeao/infra/issues/1042

**Comment by jgmize** [comment]
This is also being tracked in https://jira.mozilla.com/browse/SRE-313 and @limed is helping us with this. Based on our discussion yesterday he's already made some good progress on the terraform, but there is more cleanup he wants to do before opening a PR and we'll have to coordinate with AWS support on transferring the domain between accounts.

**Comment by glogiotatidis** [comment]
This has been resolved in https://github.com/mozmeao/infra/issues/1042
woot!
