### ISSUE TITLE
Drop update interval from 4 hours to 10 minutes

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#1039]
Currently browsers update their Snippet bundles every 4 hours. We need to the update interval down to a few minutes (target 10') to get:

 - Faster snippet publishing, a.k.a. "Real time Snippets"
 - Global Frequency Capping Capabilities: when snippets reach a goal they get pulled out of the Bundle

## Things to consider
 - Running (multiple) Normady tests to gradually decrease the update interval. 
 - CDN Costs
 - Computing resources required.

## Roll out Plan
 - [x] Switch CDN to own ACC #1026 
 - [x] Implement Static Bundles #917 
 - [x] Update `Cache-Control` headers
 - [ ] Update `updateCycleInMs` in 25% of Beta population to 60 minutes
 - [ ] Measure bandwidth use, extrapolate, calculate additional costs
  - [ ] Check how many users enrolled the Control and Treatment groups.
 - [ ] Update `updateCycleInMs` globally

### Note

Exact percentage of the testing population, testing steps and final  update interval are TBD

**Comment by metadave** [comment]
should we think about Cloudflare v Cloudfront if traffic will increase significantly? cc @jgmize

**Comment by glogiotatidis** [comment]
CloudFlare also has accesible and detailed stats which will help us with building the feature and the Normandy tests.

**Comment by glogiotatidis** [comment]
Created an normandy experiment targeting Beta to test a lowered interval of 1 hour. It's planned to go live tomorrow

https://experimenter.services.mozilla.com/experiments/reduce-snippets-update-interval-down-to-1-hour-from-4/

**Comment by glogiotatidis** [comment]
We learned from the experiement that with current code and infra setup we can go ahead and reduce the interval. This is not a priority atm though, so closing this one for now
