### ISSUE TITLE
Add Lockwise Add-On Targeting

### ISSUE THREAD

**Issue by stsegovia-moz** [mozmeao/snippets-service#1042]
Since lockwise is now an add-on, is it possible to add targeting parameters for that? 

https://github.com/mozilla-lockwise/lockwise-addon

**Comment by glogiotatidis** [comment]
Added Lockwise to the list of Addons available in Targets

![image](https://user-images.githubusercontent.com/584352/59406880-3e494980-8db8-11e9-8976-48713db29fbd.png)

**Comment by stsegovia-moz** [comment]
Perfect! Thank you!
