### ISSUE TITLE
Unknown Error When Creating New Snippet or Changing Language of Snippet

### ISSUE THREAD

**Issue by stsegovia-moz** [mozmeao/snippets-service#1080]
Hi Giorgos,

I am creating new snippets. I have no issues when copying a snippet, but when I created a new snippet, I get this unspecified error. I have also seen this issue when I have a snippet and I want to change the language of that snippet. 

The issue is that the snippet error message appears, but no field is highlighted with an issue. Even when I fill all the fields, I still receive this issue. 

Perhaps the old language field is still available as hidden, but required? Or perhaps the language field is not updating properly for both new snippets and snippets where the language is changed? 

![Screenshot_2019-07-18 Add ASR Snippet Mozilla Snippets Production Admin](https://user-images.githubusercontent.com/47153345/61495871-1f1d7900-a96f-11e9-85ef-8f01e0e9914b.png)

Let me know if you need me to reproduce this. You can reproduce by creating a new snippet, or changing the language of an old snippet.

**Comment by glogiotatidis** [comment]
Thanks for reporting Steve. It seems that this is related with the new locale switcher. I fixed it in #1083 where you can find a more detailed technical explanation.
