### ISSUE TITLE
Add button functionality to simple snippet below search bar template

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1102]
Hi Giorgos,
A heads up that @k88hudson and team will be producing this for Fx69 (Sept 3). Pinging Kate to keep you updated. Also there's potential additional work from Kate or the Fx Monitor team to enable FxA users to authenticate for Monitor and get their report right from the snippet (similar experience to the what's new page).

Per Justin and Luke's notes: 
1. Improve Snippets code so that it can retrieve a Flow ID and Flow Time from FxA servers, as in the code I included in my addendum to Jean's notes.
2. Point the "Sign In To Monitor" CTA to a specific URL on monitor.firefox.com, including a bunch of parameters which can be seen in the URL below (which I copied from WNP 68):

https://monitor.firefox.com/oauth/init?utm_source={{ something-from-snippets }}&utm_campaign={{ something-from-snippets }}&form_type={{ something-to-talk-to-FxA-team-about }}&entrypoint={{ something-from-snippets }}&flowBeginTime={{ retrieved-from-FxA-servers-before-click }}&flowId={{ retrieved-from-FxA-servers-before-click }}

Luke: 
I believe it's an open "/metrics-flow?" endpoint on the FxA servers already. E.g., here's the Monitor code that uses it to get a Flow ID & time: https://github.com/mozilla/blurts-server/blob/d99aa8133628202a15ce2471869bf5e3714ed04f/public/js/fxa-analytics.js#L80

And here's the code from the WNP page:
https://github.com/mozilla/bedrock/blob/d2a127ae9574b10b08a694a8305fc7ee3838f4dd/media/js/base/mozilla-fxa-form.js#L49-L68

Thanks,
J

![Screen Shot 2019-07-30 at 8 25 37 AM](https://user-images.githubusercontent.com/6807556/62142917-ff0d8400-b2a3-11e9-94ab-6b5a6268e6bf.png)

**Comment by jkt230** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1569597

**Comment by glogiotatidis** [comment]
Related ASR PR https://github.com/mozilla/activity-stream/pull/5208/files

According to the PR we need to add the following fields 
```
      icon: TEST_ICON,
      icon_dark_theme: TEST_ICON_BW,
      button_color: "#0C0C0D",
      button_background_color: "#0C0C0D1a",
      button_label: "Find Out Now",
      button_url: "https://www.mozilla.org/en-US/firefox/accounts",
      title: "See if you've been part of an online data breach.",
      text: "Firefox Monitor tells you what hackers already know about you.",
      block_button_text: "Block",
```

**Comment by glogiotatidis** [comment]
/remind me to test implementation when ASR PR gets merged into nightly in a month

**Comment by glogiotatidis** [comment]
Tested today. Snippets-service code is fine, ASR layout needs some work. Re-opened bug https://bugzilla.mozilla.org/show_bug.cgi?id=1569597

Will check again in the future

**Comment by glogiotatidis** [comment]
Tested button with latest nightly and works as expected.

**Comment by glogiotatidis** [comment]
Button works
