### ISSUE TITLE
Jobs: Have same snippet name - how do we make them unique outside of IDs?

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1116]
Not sure if this qualifies as an issue but wanted to get thoughts on how do we differ Job Names as well. The example below is that it uses the same Snippet but is different because one is for release channel and the other is beta channel. Is there a way to add a field to allow us to add in Job names or is that too much and redundant? Open to ideas!

![Screen Shot 2019-08-20 at 12 38 19 PM](https://user-images.githubusercontent.com/6807556/63382731-2e1d8f80-c350-11e9-95d5-04f87eecc74c.png)

**Comment by glogiotatidis** [comment]
We're now listing the targets used by each Job. Is this enough to identify each Job?

![image](https://user-images.githubusercontent.com/584352/63936973-fe663a00-ca69-11e9-8e45-06656aa185be.png)

A `name` field for Jobs feels redundant indeed, but that's something we can easily do if you prefer.

**Comment by jkt230** [comment]
Let's give this a try!

**Comment by glogiotatidis** [comment]
Ok target listing appears to work for now. We will open new issues if we need something more.
