### ISSUE TITLE
Jobs: Can be scheduled even though snippet content is in draft mode

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1117]
When jobs are scheduled but content is still in draft mode - does that mean it will be published?

Or it means that content has to be approved AND jobs are scheduled in order for it to be published?

**Comment by glogiotatidis** [comment]
> When jobs are scheduled but content is still in draft mode - does that mean it will be published?

Yes, it will be published. Currently Job Status and Snippet Status are not connected with any logic. 

The plan is to have only approved content getting published but to enforce this on the code level we need to discuss further how this will work. Part of #1077 

Will keep this open to discuss possible implementations

**Comment by glogiotatidis** [comment]
Will close this and move discussion in #1077
