### ISSUE TITLE
Jobs: Snippets before Job Deployment 

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1118]
Hi Giorgos,
Snippets that were created before job deployment means that there are no assigned jobs to them and that I cannot see targeting. 

Example: Snippet ID 12347 was a snippet created before and I wanted to see what targeting was assigned but unfortunately I cannot.

**Comment by glogiotatidis** [comment]
Understood. The migration to Jobs was not completed. I had a list of steps to follow before launching this. I'll complete and update here.

**Comment by glogiotatidis** [comment]
It's all complete and works now!
