### ISSUE TITLE
Simple Snippet Template: UTM paramters get automatically added in text field

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1119]
Hi Giorgos, 
I know you mentioned that utm parameters would automatically be added to urls but how do we override them if we don't need them?
For instance I only wanted to use: https://app.adjust.com/ou6v41x?&campaign=snippets&adgroup=nightly-v1&creative=de-gtm but the other utm parameters keep getting added.

![Screen Shot 2019-08-21 at 2 01 53 PM](https://user-images.githubusercontent.com/6807556/63468520-f2043080-c41c-11e9-9bc9-69e3b33e9a71.png)

**Comment by glogiotatidis** [comment]
Is there a problem to have them in the URL? GA params start with `utm_` and therefore can be identified and not conflict with other params.

**Comment by glogiotatidis** [comment]
Jean will check if it affects adject.com metrics and reply here.

**Comment by jkt230** [comment]
Turns out we can't track installs through that link anyways. Let's go with the assumption that adding the UTM parameters are not harmful for tracking purposes and reopen if we are in a situation that it does.
