### ISSUE TITLE
Jobs: Where do we find the data in our dashboard

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1120]
Currently we use https://datastudio.google.com/reporting/1OOLtdTYH4m8zQOQEUckNhnrWofReflkq/page/wN8V 

AND 

https://sql.telemetry.mozilla.org/dashboard/activity-stream-snippets?p_w53572_Minimum%20impressions_60751=1000000&p_w53571_Minimum%20clicks%2Fblocks_60750=1000

to find impressions, clicks by snippet ID or overall.

But now with Job IDs, how do we find the data for each individual job?

**Comment by glogiotatidis** [comment]
You'll find the data in the same places you did before. Jobs start with ID 20000 to easily separate them from Snippet IDs.

The reason you didn't see any Job IDs was that the migration was not complete until a few minutes ago and clients where still receiving the old, pre-Job Snippets.

Does this answer your question Jean?

**Comment by glogiotatidis** [comment]
We discussed that in our last mtg and data exists in the dashboards.
