### ISSUE TITLE
Jobs: We have [[Snippet ID]] in our utm parameters

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1121]
Does it make more sense to tag it as job ids? If we wanted to see individual performance of a job?

**Comment by glogiotatidis** [comment]
Yes, eventually. This first revision was supposed to change nothing to the way to do metrics so we can transition smoothly.

**Comment by glogiotatidis** [comment]
We're now automatically add `[[job_id]]` instead of `[[snippet_id]]` in urls.
