### ISSUE TITLE
Jobs: When QA'ing Snippets, QA team couldn't see targeting

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1122]
I helped publish two snippets in Nightly (RU and IT), message IDs: 12441, 12443 and QA said that they couldn't see the targeting info. They said they'd wait until the endpoints were updated (unclear to me what that means). 

A) Does endpoints need to be updated so that it includes targeting info?
B) How do we show QA to look for the targeting info? 

I know this is because targeting now sits within Job IDs, but I figured giving QA job IDs wouldn't help as I didn't know how to explain to them what to look for.

**Comment by glogiotatidis** [comment]
I don't see any  Jobs related to those snippets so they were never published, thus they had to targeting info. Targeting is part of a Job.

If you just shared the preview URLs, those don't have targeting information deliberately.

Does this answer your question @jkt230 ?

**Comment by jkt230** [comment]
Reminder to Jean: preview links do not have targeting info included. So when providing info to QA team (especially if asking for endpoints - they are asking about client match rules which is what Giorgos provides). 

QA team only needs to verify code within Firefox - but when it comes to content and how it operates, etc. it's on Giorgos and snippets team.
