### ISSUE TITLE
Ability to Edit Job After Scheduling

### ISSUE THREAD

**Issue by stevesegovia** [mozmeao/snippets-service#1136]
Hi Giorgos,

I know this isn't essential, but a nice to have. We have a use case for this as someone wants for us to pause certain snippets during September 11, which usually is a sensitive day for folks since its the anniversary of the World Trade Center attacks in the United States.

Since we don't currently have a pause or edit function, I can just create a new job for any snippets we stop on that day. But that would break off data from that specific campaign into two sets. 

The main need here is to edit a job after publishing (date, targeting, etc)

If it's not something that can be available in the near future that isn't a huge issue as we can work around it in the short-term. Just want to check to be sure. Thank you!

**Comment by glogiotatidis** [comment]
Noted. I will take a look when I start working on Freq Capping b/c those are related. Thanks!
