### ISSUE TITLE
Update auto localization for "Messages from firefox"

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#1138]
zh-TW: Firefox 的話
RU: Сообщения от Firefox 
pt-BR: Mensagens do Firefox
ID: Pesan dari Firefox
FR: Messages de Firefox
ES: Mensajes de Firefox
DE: Nachrichten von Firefox

**Comment by jkt230** [comment]
Adding one more,
PL: Komunikaty Firefox

**Comment by glogiotatidis** [comment]
>  ES: Mensajes de Firefox

Added this message to 
 - Spanish (Spain)
 - Spanish (LatAm)
 - Spanish (All)

@stsegovia let me know if that's ok.

**Comment by glogiotatidis** [comment]
Added!

**Comment by stsegovia** [comment]
Yes, that is perfect! It's all the same in each of those locales.

-Steve
