### ISSUE TITLE
Question about SQL Queries on Snippet ID vs Job ID

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1149]
When we use Big Query to get data such as snippet performance on Monitor Campaigns do we use SQL like this using SnippetID or should it be changed to JobID?

This is how we've done it in the past:
#standardSQL

SELECT
  SnippetID,
  name,
  body,
  url,
  SUM(impression) as impression,
  SUM(clicks) as clicks,
  SUM(snippetBlocked) as blocks

FROM
  `ga-mozilla-org-prod-001.snippets.snippets_performance_*`

WHERE

 date >= '2019-04-01'
     AND date<= '2019-06-30'

 AND   lower(campaign) like "%monitor%"

  GROUP BY 1,2,3,4
  ORDER BY 1,2,3,4

**Comment by glogiotatidis** [comment]
I don't know how Big Query is setup and how the metadata are combined. My guess is JobID. 

Job IDs start at 20000 whereas Snippet IDs are bellow 20000, so you can try with Job ID and if you get numbers back that's the correct one, otherwise it's Snippet ID.

**Comment by jkt230** [comment]
ok adding @jgmize, thanks!

**Comment by jgmize** [comment]
@glogiotatidis guess that we should query using the JobID appears to be correct to me. Here is an example query using JobIDs: https://sql.telemetry.mozilla.org/queries/64850/source

**Comment by glogiotatidis** [comment]
Agreed. On Redash we surely use JobID. Jean mentioned Big Query and I wasn't sure which Big Query instance this is. Thanks for confirming!
