### ISSUE TITLE
Make Job Ids searchable in snippet admin

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1160]
For Snippets, we can search using snippet ids. It doesn't work when in jobs. 
![Screen Shot 2019-09-27 at 9 00 21 AM](https://user-images.githubusercontent.com/6807556/65783734-45952880-e105-11e9-8e2b-2c7a370f1036.png)

**Comment by glogiotatidis** [comment]
Now able to search using Job ID or Snippet ID
