### ISSUE TITLE
Adding Tags to Specific Snippets with Specific Templates

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1178]
Giorgos,

@jgmize /Mindy/I are trying to figure out the best way to get Q3 data per specific product/campaign and we're having issues getting access to old meta data in Q3 (looks like in AWS, the oldest we have access to is Oct 3, 2019). 

One idea Josh had was to add tags to the old snippets that have been published based on the template used. 

Would it be possible for you to add these tags to the snippets with specific templates such as:

"FxA Widget" to all snippets using the Fx Accounts Sign Up template
"Send to Device" to all snippets using the Send to Device template
"Newsletter Sign Up" to all the snippets using the Newsletter Sign Up template

This is example of what we're trying to find for Q3 (this screenshot is for Q2):
![Screen Shot 2019-05-10 at 9 09 26 AM](https://user-images.githubusercontent.com/6807556/66610406-4b145900-eb70-11e9-9847-71766f32ccf6.png)

**Comment by jkt230** [comment]
@Mindy-Moz

**Comment by glogiotatidis** [comment]
> One idea Josh had was to add tags to the old snippets that have been published based on the template used.

What do you mean by "Old Snippets"? Are you referring to `Snippets` or `ASRSnippets`? 

We already have tags to ASRSnippets related to the template, like `SS`, `FxA`, etc. You're requesting other tags here. Can't we reuse what we already have?

**Comment by Mindy-Moz** [comment]
@glogiotatidis We are referring to ASRSnippets. Trying to get the metadata for the snippets pre-jobs (July 1 - August 26) before we started using tags. I think when the system was converted, any snippets that were published in Q3 no longer reflected a published status, so we weren't able to track down the metadata we needed that way. Josh tried to query via template source but it wasn't working as it was giving only one result. Can we retroactively add tags to all pre-job snippets in Q3, so we are able to query for them now while the template source query is being resolved?

**Comment by glogiotatidis** [comment]
Thanks for the additional info @Mindy-Moz. I still have some questions and I think it's better to discuss them in the next snippets mtg, tomorrow

**Comment by glogiotatidis** [comment]
Talked with @jgmize and there's no action to take with tags to extract data at this point. Current status is that all ASRSnippets have tags.
