### ISSUE TITLE
DailyJobPerformance model populated from Redash query

### ISSUE THREAD

**Issue by jgmize** [mozmeao/snippets-service#1208]
- Supports https://github.com/mozmeao/snippets-service/issues/1207
- Fields
  - job (fk)
  - date
  - impressions
  - clicks
  - blocks
- May decide to add HourlyJobPerformance model later

**Comment by glogiotatidis** [comment]
This has been deployed to production and metrics have been fetched for oct

**Comment by jgmize** [comment]
Thanks again @glogiotatidis!
