### ISSUE TITLE
Simple below Search template - weird placement of X

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1211]
We launched a few simple below search snippets this week using the button label, which works fine. The issue is when we tried to use a hyperlink within text, we noticed the weird placement of X - not sure if this occurred because of [adding the button fix ](https://github.com/mozmeao/snippets-service/issues/1102)to the Simple below Search template. 

https://snippets-admin.mozilla.org/admin/base/asrsnippet/11904/change/ as an example

![image](https://user-images.githubusercontent.com/6807556/67812773-2e778c80-fa5d-11e9-8f37-99d906a8145b.png)

**Comment by glogiotatidis** [comment]
This is on the AS side. I will file a bug

**Comment by glogiotatidis** [comment]
Filed bug https://bugzilla.mozilla.org/show_bug.cgi?id=1592525

**Comment by glogiotatidis** [comment]
/remind me to check in a week

**Comment by glogiotatidis** [comment]
Marked to be fixed in Fx72. Adding a reminder to check when Fx72 hits beta

/remind me to check on 2019-12-04

**Comment by glogiotatidis** [comment]
there's a fix needs to be uplifted. will check status next week 

/remind me on monday

**Comment by glogiotatidis** [comment]
This targets Fx 73.

/remind me to check on 2020-01-08

**Comment by glogiotatidis** [comment]
Fixed in Fx73, currently in nighlty
