### ISSUE TITLE
Auto change category for F100 Snippets with "Utility and FxA" in name

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1216]
Hi Giorgos,

There's a ton of F100 snippets (over a few hundred) that have been mislabeled with the category Utility when they should be FxA. Is there a way to write a script to change the published F100 snippets in all locales that have "Utility and FxA" in the name to have the FxA category?

![Screen Shot 2019-10-30 at 8 20 04 AM](https://user-images.githubusercontent.com/6807556/67871871-48ad7b00-faee-11e9-8a1b-33a749a6d80e.png)

**Comment by glogiotatidis** [comment]
Yes, will do. 

Also it seems that most of these snippets are the same, scheduled for different weeks of the 'journey'. We should make a plan to consolidate those into one with multiple jobs. Do you have ideas on how we can find the duplicates?
