### ISSUE TITLE
FieldError on /admin/base/job/add/

### ISSUE THREAD

**Issue by jgmize** [mozmeao/snippets-service#1220]
https://sentry.prod.mozaws.net/operations/snippets/issues/6453618/?query=is:unresolved

"'completed_on' cannot be specified for Job model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class JobAdmin."

**Comment by glogiotatidis** [comment]
Thanks for quickly fixing this Josh. Created an issue to add a list of tests to catch errors like this before they hit prod. #1223
