### ISSUE TITLE
Ad Hoc Report: All Live EN F100 Jobs with Copy 

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1234]
Hey Giorgos, 

Is it possible to quickly pull a report with a list of live F100 snippets for EN locale (organized by week based on name or profile age targeting) that lists out id, snippet name, copy? 

I need to do an audit to track what content is still relevant and take actions if they are not. I could easily filter in jobs to get f100 live snippets for EN locale but then I would have to go into each individual snippet to get the copy. 

Let me know, thanks!

**Comment by glogiotatidis** [comment]
Shared a document with you with the requested data.

**Comment by jkt230** [comment]
AMAZING! Thank you!!!!
