### ISSUE TITLE
 Ad Hoc Reports: All Live F100 Jobs with Copy (by locale) 

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1236]
Per issue #1234, you did this for the EN locale. Can you create a separate tab/report for each of the live F100 snippets in all the other locales as well please? No rush on this. Should have de/fr/pt-br/ru/es/pl/zh-tw/ru

**Comment by glogiotatidis** [comment]
Done! And also included other locales for which we run f100s

**Comment by jkt230** [comment]
Giorgos is it possible to add in the preview links or the URL of the destination pages within the sheet as well? MJ is viewing these and cannot see within the admin links: https://docs.google.com/spreadsheets/d/1UgFLu0_3ZST0-a9iW4YbiRZBkzpt8Eb0AP2B_3BuH3Y/edit?ts=5ddf89ec#gid=1225621160

**Comment by glogiotatidis** [comment]
Jean we'll have to re-do all the processing from start. How about giving read-only viewing rights to access the admin?

**Comment by jkt230** [comment]
Ok to re-process? Would greatly appreciate that.

**Comment by glogiotatidis** [comment]
Sure, np!

**Comment by glogiotatidis** [comment]
Added new sheets with update content and preview links.

**Comment by jkt230** [comment]
Thank you!
