### ISSUE TITLE
Bring additional locales into admin list

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1246]
Hi Giorgos, we're going to be running a few snippets (Monitor and FxA) for these locales - can you bring them into the list?

Break LATAM to:
ES-MX
ES-AR

VI (Vietnamese)
TR (Turkish)
HU (Hungarian)
NL (Dutch)
DA (Danish)
RO (Romanian)

**Comment by glogiotatidis** [comment]
Done!

I created `Spanish (Mexico)` and `Spanish (Argentina)`. We cannot "break" LaTaM since we have other snippets using this. 

Also do you want to provide translations for `Remove this` and `Messages from Firefox` ?
