### ISSUE TITLE
Add FPN Proxy Extension to Add-on List for Snippet Admin Targeting

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1247]
Hey Giorgos,

We need to be able to target users who don't have the FPN Proxy extension (seen here: https://fpn.firefox.com/#get-fpn). Can you add this proxy extension to the add ons list?

Thanks!

**Comment by glogiotatidis** [comment]
Done!

**Comment by glogiotatidis** [comment]
Also created two Targets `Addon: Installed FPN` and `Addon: Not Installed FPN`
