### ISSUE TITLE
Make preview work for right-to-left languages

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#1257]
We used to have this functionality pre-Quantum, curious if it's a lot of work to incorporate our current system.

**Comment by glogiotatidis** [comment]
This is a bug on the AS side, thus not very simple to fix. Filed bug https://bugzilla.mozilla.org/show_bug.cgi?id=1601880 to track this.

Is this high priority? Should we ask to prioritize fixing for Fx72?

/remind me in 1 week

**Comment by glogiotatidis** [comment]
After talking with Andrei it seems that this is only a Preview issue and snippets are displayed as they should in right-to-left browsers.

**Comment by glogiotatidis** [comment]
Andrei from AS will land a fix to allow us to correctly preview right-to-left snippets. Then we will use this to prepare proper preview links for right-to-left languages.

Marked blocked until AS work is done.

/remind me in a month

**Comment by glogiotatidis** [comment]
Update from bug
> The URLSearchParams now has a property "dir", which can be set to "rtl" to preview right-to-left orientation

**Comment by glogiotatidis** [comment]
- [ ] Push code to prod
- [ ] Mark RTL languages in DB

**Comment by glogiotatidis** [comment]
patch not merged in fx yet. 

/remind me in 20 days

**Comment by glogiotatidis** [comment]
@piatra I see the related Fx bug is fixed but I can't get this to work on nightly. I try with the following snippet (although in english). Some parts of the page get aligned to the right, but not the snippet. See screenshot. 

about:newtab?theme=light&dir=rtl&endpoint=https://snippets-admin.mozilla.org/preview-asr/8bebfd8d-2f13-47ac-8718-ae05fcbee94c/


![image](https://user-images.githubusercontent.com/584352/73741929-f797cd80-4753-11ea-8b39-15d245306438.png)

**Comment by piatra** [comment]
@glogiotatidis thanks for reporting, I only tested with below the searchbar snippets and missed this problem. We'll try to get a fix in before the 74 code freeze.

**Comment by glogiotatidis** [comment]
Thanks!
