### ISSUE TITLE
Disable Metadata export cron job

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#1291]
In #887 we introduced a Metadata Export Job to support the Google Dashboard. I believe this dashboard is no longer is use. If so

- [x] Delete relevant code
- [x] Delete S3 content
- [x] Update 0002 ADR 
- [x] K8s Config
- [x] DMS Snitch

**Comment by glogiotatidis** [comment]
@jgmize do you think we can go ahead with this?

**Comment by jgmize** [comment]
Yes, this can all be deleted.

**Comment by glogiotatidis** [comment]
Done! Thanks @jgmize
