### ISSUE TITLE
Add Locale, Product and Number of Snippets in Performance Report

### ISSUE THREAD

**Issue by Mindy-Moz** [mozmeao/snippets-service#1302]
Hi @glogiotatidis ,

Can we add data to [Q4](https://github.com/mozmeao/snippets-private-data/blob/master/2019/Q4/quarterly-performance.ipynb) by Locale (Slide 47), by Product (Slide 35), and Number of Snippets by Category (Slide 23)?

Please refer to these slides: https://docs.google.com/presentation/d/1S1HoJNneMumS6iD88ORgEMlBRVv3BEOULBI-w6mPtGA/edit 

Thanks 
Mindy

**Comment by glogiotatidis** [comment]
Hi Mindy,

 - OK about the Locales, I'm working on it
 - I understand that there's already a `by Category` table in the report.
 - How can I get the Product information?

**Comment by Mindy-Moz** [comment]
Hi Giorgos,

Yes, there is already a by Category table in the report, but it is missing a column of info "Number of Snippets". In [this doc where I am compiling the data](https://docs.google.com/spreadsheets/d/1Rcq2zrBAO2ap8waV1J776-mv-Vme4Mzut6OCOqHAUM4/edit?usp=sharing), in Tab "By Category" you will see a column highlighted in Red, this is what I want for Q4. The populated numbers in red now is the old ones from Q3.

In the same doc, you will see a tab that says "By Product", for Q4 all column info is in red, those are the columns of info I need by product. 

Here is how Josh pulled the info last time for "By Product" in this [DataBricks notebook](https://dbc-caf9527b-e073.cloud.databricks.com/#notebook/184588/command/192076), it is near the bottom, starting with "Fx Accounts Benefits Page".

**Comment by glogiotatidis** [comment]
2019Q4 report delivered with all the requested numbers
