### ISSUE TITLE
Make category field required

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#1315]
- [x] Create `Categorize me` Category
- [x] Add all Snippets w/o Cat to `Categorize me` cat.
- [x] Make field required
- [x] Ask M to properly categorize Snippets in `Categorize me` Category
- ~~Remove `Categorize me` Category~~ tracked in #1325

**Comment by glogiotatidis** [comment]
Hey @Mindy-Moz @ldwright could you please go ahead and assign a proper category for all the snippets listed here https://snippets-admin.mozilla.org/admin/base/category/11/change/ so we can go ahead with producing the Metrics?

Ping me here when you're done.

Thanks!

**Comment by Mindy-Moz** [comment]
Hey @glogiotatidis I updated all the "approved" snippets with a category, but not the drafts since they were never published. Let me know if you want me to go back and do those too. Thanks!

**Comment by glogiotatidis** [comment]
Yes all please. feel free to delete anything that looks like it should be deleted (like tests)

**Comment by Mindy-Moz** [comment]
Hey Giorgos, I deleted what I could and categorized the rest.
