### ISSUE TITLE
Re-enable Nightly Channel 

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#1322]
- [x] OMN team to create long running content targeting the nightly channel 
  - [x] Simple Template
  - [x] Newsletter Template
- [x] Ping Andrei to re-enable the channel
- [x] Confirm it works

**Comment by glogiotatidis** [comment]
Hey @Mindy-Moz the Fx team asked to also create a Newsletter Snippet  w/o end date before they re-enable the nightly channel.

Could you please take care of that and ping me here when done?

Thanks!

**Comment by Mindy-Moz** [comment]
Hi Giorgos,

Nightly Evergreen Newsletter has been scheduled out with no end date.

Thanks,
Mindy

13378
<https://snippets-admin.mozilla.org/admin/base/asrsnippet/13378/change/>
13379
<https://snippets-admin.mozilla.org/admin/base/asrsnippet/13379/change/>
13380
<https://snippets-admin.mozilla.org/admin/base/asrsnippet/13380/change/>

**Comment by glogiotatidis** [comment]
Thanks for working on this Mindy. We want to use the Newsletter templates so we can test their functionality. The ones you posted are just Simple snippets. Thanks!

**Comment by glogiotatidis** [comment]
Nightly is enabled. Newsletter and Simple Snippet templates in use. Thanks!
