### ISSUE TITLE
Expose Multi-Account Containers to AddOn drop-down targeting

### ISSUE THREAD

**Issue by Mindy-Moz** [mozmeao/snippets-service#1400]
@glogiotatidis Can/should we just have an open field to enter any extension as needed (with help text that links to a list of what their “code names” are), rather than adding specific ones to a drop-down each time? The exposed Multi-Account Containers to AddOn will enable us to update existing F100 snippet targeting to exclude users who already have it installed.

![Screen Shot 2020-06-23 at 12 41 19 PM](https://user-images.githubusercontent.com/54955529/85451607-ed356f00-b54e-11ea-84e5-d89e85df0686.png)

**Comment by glogiotatidis** [comment]
Hi Mindy. There's no list of extension code names, so this can't be just an open field. We can code automation to extract addon code name from addon link but the current use of this filter doesn't justify this work.

Meanwhile I'm happy to provide you with all the entries you need. I'll add Multi-Account Containers addon right away.

**Comment by glogiotatidis** [comment]
Done
