### ISSUE TITLE
Allow deletion of Icons not currently in use

### ISSUE THREAD

**Issue by Mindy-Moz** [mozmeao/snippets-service#1447]
Hi @glogiotatidis & @pmclanahan 

We have a lot of icons no longer appliable due to their pixel size or interface incompatability. Unable to remove them without deleting unpublished snippets (no current job tied to snippet). However, we would like to retain the snippets for reference or reuse in the future. Recommend icon archival button that allows the user to categorize and hide old icons as we continue to grow/change. Once an icon is removed to archive, the snippet that retains that icon should prompt a change to a new icon when it comes time to publish a job or the icon is stripped or a generic icon indicator to be updated. Implimentation is needed as we have new publishers joining the platform, worried about governance when it comes to programming. Thanks!

![Screen Shot 2020-09-30 at 10 29 33 AM](https://user-images.githubusercontent.com/54955529/95223207-2d42f980-07ae-11eb-9c0a-1f8f8e4f8963.png)

**Comment by glogiotatidis** [comment]
Instead of archiving we can just allow deletion of icons not associated with a Published Job. Would that work @Mindy-Moz ?

**Comment by Mindy-Moz** [comment]
Yes that works too as long as associated snippets that previously used that icon are not impacted.

**Comment by glogiotatidis** [comment]
> Yes that works too as long as associated snippets that previously used that icon are not impacted.

They are going to be impacted in the sense that they won't have icons anymore but I judging from your initial comment I guess you mean that copy is not lost

**Comment by Mindy-Moz** [comment]
Yeah, I meant the copy wouldn't be lost. Works for me what you will
implement. Thanks!
