### ISSUE TITLE
Activity Stream close button is broken

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#268]
Activity steam close button `chrome://browser/skin/sidebar/close.svg` is no longer available.

@ScottDowne can you please take a look and update https://github.com/mozmeao/snippets-service/blob/master/snippets/base/templates/base/includes/snippet_as.css#L24

**Comment by ScottDowne** [comment]
Blah, looks like someone moved it to chrome://global/skin/icons/close.svg

I'll see about making a small patch today.

**Comment by ScottDowne** [comment]
Also needs:

```
-moz-context-properties: fill, fill-opacity;
fill-opacity: 0;
```

to show it properly.

**Comment by glogiotatidis** [comment]
Aha, ic. So is it safe to refer to this image or it's better to bring it in with the cost of the image size?

**Comment by ScottDowne** [comment]
Dunno. Initially I was told it was safe to use, but that turned out to be kinda false for whatever reason.

I would be fine with just baking it in as a data uri. It's not like it's going to be big.

**Comment by glogiotatidis** [comment]
IC. Well since we're targeting different versions of Firefox at the same time I'd say it's better to get this as a data uri.

**Comment by ScottDowne** [comment]
Sorry I didn't get to this sooner given how easy it was.

https://github.com/mozmeao/snippets-service/pull/270

**Comment by glogiotatidis** [comment]
no worries and many thanks!
