### ISSUE TITLE
ImportError: Module "django.contrib.sessions.serializers" does not define a "JSONSerializer" attribute/class

### ISSUE THREAD

**Issue by jgmize** [mozmeao/snippets-service#272]
From sentry email on Tue, Aug 29, 2017 at 1:17 AM:
```
ImportError: Module "django.contrib.sessions.serializers" does not define a "JSONSerializer" attribute/class
(2 additional frame(s) were not displayed)
...
  File "django/contrib/sessions/middleware.py", line 16, in process_request
    request.session = self.SessionStore(session_key)
  File "django/contrib/sessions/backends/db.py", line 15, in __init__
    super(SessionStore, self).__init__(session_key)
  File "django/contrib/sessions/backends/base.py", line 42, in __init__
    self.serializer = import_string(settings.SESSION_SERIALIZER)
  File "django/utils/module_loading.py", line 33, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "django/utils/module_loading.py", line 29, in import_string
    return getattr(module, class_name)
```

**Comment by jgmize** [comment]
Also, while logging in to sentry to view this error it prompted me about https://blog.sentry.io/2017/05/01/release-commits.html -- @glogiotatidis do we already have this set up for snippets-service, or should I file a separate issue about it?

**Comment by glogiotatidis** [comment]
I've seen that kind of funny errors in the past. JSONSerializer does exist and the URL is working fine now, I don't understand why these errors happen

**Comment by glogiotatidis** [comment]
I think 

> @glogiotatidis do we already have this set up for snippets-service, or should I file a separate issue about it?

yes

**Comment by jgmize** [comment]
> I've seen that kind of funny errors in the past (in Tokyo?). JSONSerializer does exist and the URL is working fine now, I don't understand why these errors happen

It might be a race condition at startup time.

**Comment by glogiotatidis** [comment]
> I've seen that kind of funny errors in the past (in Tokyo?). JSONSerializer does exist and the URL is working fine now, I don't understand why these errors happen
> 
> It might be a race condition at startup time.

Any suggested action?

**Comment by jgmize** [comment]
Since this appears to be an import time race condition in `django.contrib.sessions`, it might be something that is already fixed in a newer version of django. I didn't find anything in a quick search, but you may have better luck.

**Comment by glogiotatidis** [comment]
We haven't seen this error for a while, so i'll close this issue for now.
