### ISSUE TITLE
Use gSnippetsMap.showFirefoxAccounts();

### ISSUE THREAD

**Issue by k88hudson** [mozmeao/snippets-service#274]
This will be available with this bug lands in Nightly: https://bugzilla.mozilla.org/show_bug.cgi?id=1394706

Usage is as follows:
```js
gSnippetsMap.showFirefoxAccounts();
// Opens about:accounts?action=signup&entrypoint=snippets
```

**Comment by k88hudson** [comment]
Ok this has landed!

**Comment by glogiotatidis** [comment]
PR https://github.com/mozmeao/snippets-service/pull/298
