### ISSUE TITLE
Support visually hiding snippets on the current page when `Snippets:Disabled` event is fired

### ISSUE THREAD

**Issue by k88hudson** [mozmeao/snippets-service#281]
We have recently added an event that triggers when the Snippet being enabled/disabled via the preferences panel. 

Documentation is here:
https://github.com/mozilla/activity-stream/blob/master/docs/v2-system-addon/snippets.md#events

To listen to the event, just listen on the window, i.e.

```js
window.addEventListener("Snippets:Disabled", () => {
  // hide stuff here
});
```
We probably don't want to actually block the currently shown snippet, as the user hasn't specifically indicated they don't want to see that snippet.

**Comment by tspurway** [comment]
@glogiotatidis - do you think this bug will land for 57?

**Comment by glogiotatidis** [comment]
Yes this will land in 57.

What I plan to do is to listen for the event and then write to `gSnippetsMap` that snippets are disabled and display None.

Do we have a reason why this doesn't get into AS addon and just don't load any snippets code when snippets are disabled?

**Comment by k88hudson** [comment]
@glogiotatidis no need to write to `gSnippetsMap` since snippets will not disabled on the *next* page load, this is just for the case if snippets are *already* shown on the page and get turned off in the settings panel in the upper right corner.

**Comment by k88hudson** [comment]
Also @tspurway note that this doesn't have to land with the trains, since this code lives/is deployed outside mozilla central

**Comment by glogiotatidis** [comment]
> @glogiotatidis no need to write to gSnippetsMap since snippets will not disabled on the next page load,

@k88hudson I guess you meant "since snippets will not be enabled on the next page load"?

If so, I guess  

```
window.addEventListener("Snippets:Disabled", () => {
    document.querySelector("#snippets-container").style.display = "none";
});
```

should be enough?
