### ISSUE TITLE
Placeholder for previews for AS snippets

### ISSUE THREAD

**Issue by k88hudson** [mozmeao/snippets-service#286]
I generated a static version of AS (no content, but has squares at least) if it's helpful.

Code is here: https://github.com/k88hudson/activity-stream-static/tree/gh-pages

or you can point to the html file directly: https://k88hudson.github.io/activity-stream-static/activity-stream-prerendered.html

**Comment by k88hudson** [comment]
cc @glogiotatidis

**Comment by k88hudson** [comment]
Also, note that this page is **not compatible with Chrome**, it only looks right if you look at in FF.

**Comment by glogiotatidis** [comment]
Thanks!

**Comment by glogiotatidis** [comment]
Preview fixed here https://github.com/mozmeao/snippets-service/commit/cf438c6c14a5fc2ebe29e4e137927a5924598b9d
