### ISSUE TITLE
Test_snippet_set_present fails due to beta channel snippet returning 204 No Content

### ISSUE THREAD

**Issue by stephendonner** [mozmeao/snippets-service#317]
This test is failing due to the response being a 204, rather than a 302:

https://github.com/mozmeao/snippets-service/blob/6d7d7425187f9820c4e1faef5786f9a0dabf55f6/tests/test_snippets.py#L24

```
20:48:18 FAIL test_snippets.py::TestSnippets::()::test_snippet_set_present[/3/Firefox/default/default/default/en-US/beta/default/default/default/]
20:48:18 =================================== FAILURES ===================================
20:48:18  TestSnippets.test_snippet_set_present[/3/Firefox/default/default/default/en-US/beta/default/default/default/] 
20:48:18 [gw7] linux2 -- Python 2.7.5 /home/jenkins/slavehome/workspace/snippets.prod/tests/.tox/py27/bin/python2.7
20:48:18 
20:48:18 self = <test_snippets.TestSnippets instance at 0x2e9e908>
20:48:18 base_url = 'https://snippets.mozilla.com'
20:48:18 path = '/3/Firefox/default/default/default/en-US/beta/default/default/default/'
20:48:18 
20:48:18     @pytest.mark.parametrize(('path'), test_data)
20:48:18     def test_snippet_set_present(self, base_url, path):
20:48:18         full_url = base_url + path
20:48:18     
20:48:18         r = self._get_redirect(full_url)
20:48:18 >       assert requests.codes.ok == r.status_code, full_url
20:48:18 E       AssertionError: https://snippets.mozilla.com/3/Firefox/default/default/default/en-US/beta/default/default/default/
20:48:18 E       assert 200 == 204
20:48:18 E        +  where 200 = <lookup 'status_codes'>.ok
20:48:18 E        +    where <lookup 'status_codes'> = requests.codes
20:48:18 E        +  and   204 = <Response [204]>.status_code
20:48:18 
20:48:18 test_snippets.py:65: AssertionError
```

**Comment by stephendonner** [comment]
Failure, through webpagetest.org: https://www.webpagetest.org/result/171107_BD_ed9ef15f7b99ca31dcdd59dae54e4379/
Success (aurora channel): https://www.webpagetest.org/result/171107_FQ_6ae01dde43c33bb842381c3b218d1ce1/

**Comment by stephendonner** [comment]
According to our CI, this regressed 2 days and 11 hours ago, so sometime around Sunday, November 5th, ~4:36am PST.

**Comment by glogiotatidis** [comment]
This is expected behavior since https://github.com/mozmeao/snippets-service/commit/4936f2371e341690def9be40a72abdd32205b0c9, both `302` and `204` are valid answers from the service. 

I suggest that you also change your URLs to `/5/....` to fetch snippets targeting activity stream which is going to be the default going forward.  Now there 're no snippets running on about:home for Beta since Beta is already on Activity Stream, thus you get 204.
