### ISSUE TITLE
Add a test to validate the served snippets

### ISSUE THREAD

**Issue by davehunt** [mozmeao/snippets-service#319]
We used to have a test that found all the `<a>` elements in the served content and validated them. This test iterated over the discovered elements, and as there was no assertion to check the list was not empty, the test has been passing despite there being no such elements in the payload for a couple of years. To restore this coverage we would need to parse the content to determine the snippets, and then check that these are valid.

@glogiotatidis may be able to confirm if this coverage is desired, and provide further details that may prove useful for a contributor wishing to help out.

**Comment by glogiotatidis** [comment]
The new Activity Stream Router payload is JSON and does not contain any HTML elements. All this functionality has move to activity stream addon.

Thanks for filing Dave
