### ISSUE TITLE
Implement override onboarding option for snippet campaigns

### ISSUE THREAD

**Issue by k88hudson** [mozmeao/snippets-service#323]
Let's makes sure that individual campaigns have an option to override onboarding if necessary. This can be accomplished by calling `gSnippetsMap.disableOnboarding()`, and will probably require a new option in the admin interface.

@glogiotatidis is this something you're able to do? Do you have everything you need?

**Comment by glogiotatidis** [comment]
I understand that `disableOnboarding` flips `onboardingFinished` to `true` until the browser closes. This will make all snippets appear, not individual campaigns. (Also it doesn't hide the Firefox icon on the upper left corner, but I don't know if that's intended) 

What I's expecting was that snippets would control the appearance of onboarding:

 1. Snippets code run
 2. Check if there are high-priority snippets that should override onboarding, is yes show them
 3. If no check if onboarding is finished, is no show onboarding
 4. If yes continue if the rest of the snippets.

Thoughts @k88hudson

**Comment by glogiotatidis** [comment]
This will be soon irrelevant as we move to AS Router. Closing.
