### ISSUE TITLE
Verify snippets should not show up for new profiles/users

### ISSUE THREAD

**Issue by k88hudson** [mozmeao/snippets-service#324]
Let's verify that snippets are not showing up for new users/profiles, and that onboarding is shown

**Comment by glogiotatidis** [comment]
Snippets are not showing up for new users profiles until onboarding is finished.

An exception to the statement above: Snippets may show up once along with onboarding if `gSnippetsMap.get("appData.onboardingFinished") ` hasn't been populated yet.

This will be replaced with new logic in AS Router which should fix this issue as well. See bug [1462415](https://bugzilla.mozilla.org/show_bug.cgi?id=1462415)
