### ISSUE TITLE
Beta and Aurora-channel Activity Stream tests are failing due to HTTP 204 response

### ISSUE THREAD

**Issue by stephendonner** [mozmeao/snippets-service#330]
https://github.com/mozmeao/snippets-service/blob/ec3d4c588503517875a2f069056ce4e9617aff8c/tests/test_snippets.py#L41 has been failing for **aurora** and **beta** channels, while **release** is fine for at least the past couple days.

TL;DR: https://snippets.mozilla.com/5/Firefox/default/default/default/en-US/aurora/default/default/default/ and https://snippets.mozilla.com/5/Firefox/default/default/default/en-US/beta/default/default/default/ serve up HTTP 204s with 0-byte text/html content (see https://www.webpagetest.org/result/171129_AD_1ba3f01647797beeb2791f8855e6d72a/1/details/#waterfall_view_step1 vs. the working _release:_ 

```
00:18:07 =========================== short test summary info ============================
00:18:07 FAIL test_snippets.py::test_activity_stream[aurora]
00:18:07 FAIL test_snippets.py::test_activity_stream[beta]
00:18:07 =================================== FAILURES ===================================
00:18:07 _________________________ test_activity_stream[aurora] _________________________
00:18:07 [gw7] linux2 -- Python 2.7.5 /home/jenkins/slave/workspace/snippets.prod/tests/.tox/py27/bin/python2.7
00:18:07 
00:18:07 base_url = 'https://snippets.mozilla.com', channel = 'aurora'
00:18:07 
00:18:07     @pytest.mark.parametrize(('channel'), ['aurora', 'beta', 'release'])
00:18:07     def test_activity_stream(base_url, channel):
00:18:07         url = URL_TEMPLATE.format(base_url, '5', channel)
00:18:07         soup = _parse_response(_get_redirect(url).content)
00:18:07 >       script = soup.find('script', type='application/javascript').text
00:18:07 E       AttributeError: 'NoneType' object has no attribute 'text'
00:18:07 
00:18:07 base_url   = 'https://snippets.mozilla.com'
00:18:07 channel    = 'aurora'
00:18:07 soup       = 
00:18:07 url        = 'https://snippets.mozilla.com/5/Firefox/default/default/default/en-US/aurora/default/default/default/'
00:18:07 
00:18:07 test_snippets.py:44: AttributeError
Post stage
00:18:07 __________________________ test_activity_stream[beta] __________________________
00:18:07 [gw1] linux2 -- Python 2.7.5 /home/jenkins/slave/workspace/snippets.prod/tests/.tox/py27/bin/python2.7
00:18:07 
00:18:07 base_url = 'https://snippets.mozilla.com', channel = 'beta'
00:18:07 
00:18:07     @pytest.mark.parametrize(('channel'), ['aurora', 'beta', 'release'])
00:18:07     def test_activity_stream(base_url, channel):
00:18:07         url = URL_TEMPLATE.format(base_url, '5', channel)
00:18:07         soup = _parse_response(_get_redirect(url).content)
00:18:07 >       script = soup.find('script', type='application/javascript').text
00:18:07 E       AttributeError: 'NoneType' object has no attribute 'text'
00:18:07 
00:18:07 base_url   = 'https://snippets.mozilla.com'
00:18:07 channel    = 'beta'
00:18:07 soup       = 
00:18:07 url        = 'https://snippets.mozilla.com/5/Firefox/default/default/default/en-US/beta/default/default/default/'
00:18:07 
00:18:07 test_snippets.py:44: AttributeError
00:18:07 ===================== 2 failed, 11 passed in 2.82 seconds ======================
```

Failure log from console: https://gist.github.com/stephendonner/a8234ff3ccee6952d1c5fcf8d48a1c7c

/cc @davehunt and @glogiotatidis

**Comment by glogiotatidis** [comment]
Both 204 and 200 responses are valid responses. What you get depends on what campaigns the Snippets team is running: If you get a 204 the team does not run any campaigns for your configuration, for aurora and beta en-US channels in this case. Do you think allowing both 200 and 204 as valid success codes is OK or you prefer another approach @stephendonner ?

**Comment by davehunt** [comment]
`test_response_codes` checks that the response code is either 200 or 204 for all combinations of version (3, 5), and channel (aurora, beta, release). I think that's fine.

The issue here is that we were previously able to test activity stream (version 5) on aurora and beta, but these are now returning 204 and no content. Whilst this is an acceptable response, it means we can't make the tests deterministic. I would not want to add logic to this test to skip the checks based on the reponse code, because that could give a false impression of coverage.

We could drop aurora and beta channels from this test, if we expect release to always be served a snippet. Alternatively, if we feel there is adequate coverage elsewhere, perhaps we do not need this end-to-end test. What do you think @glogiotatidis?

Also, I have raised [bug 1421571](https://bugzilla.mozilla.org/show_bug.cgi?id=1421571) to fix the email notifications from Jenkins, as we should be responding much earlier to these failures.

**Comment by davehunt** [comment]
It looks like this settled down for a while, but the beta channel has been failing again for the last ~6hrs.  Do you think we should remove this test for beta/aurora @glogiotatidis? Is it reasonable to expect release to always have an ActivityStream snippet served?
