### ISSUE TITLE
[new filter] Filter based on installed / available add-ons/themes

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#343]
Waiting for the information to become available for use. [Bug 1431525](https://bugzilla.mozilla.org/show_bug.cgi?id=1431525)

**Comment by glogiotatidis** [comment]
Fixed in Fx60

**Comment by glogiotatidis** [comment]
This solution must replace the semi-working Test Pilot addon filtering. (see #370)

**Comment by glogiotatidis** [comment]
> Hm, it seems like we're only refreshing this at browser startup time – maybe we should change this to a function we can call (so it's updated at request time) rather than being loaded once. What do you think?

I think that's a good idea. 



> On a fresh profile I have installed TestPilot add-on and then disabled it from addons menu. I did not uninstall the addon but it's not listed in appData.addonInfo. I expected it to be listed and have userDisabled set to true.

What about this @k88hudson ?

**Comment by k88hudson** [comment]
Ok, I'll file a bug to switch it to an async api.

As for the `userDisabled`, I'm not sure why that isn't included in the information – let me follow up with some web extension folks

**Comment by glogiotatidis** [comment]
Removing the blocked tag. Although this still needs some work on the AS front to

 - Update list of addons more often than just on startup time
 - Figure out wy `userDisabled` does not work.

we can proceed with that we have as v1.

@k88hudson we're waiting for your updates here to work on v2, thanks!

**Comment by k88hudson** [comment]
So i talked to the web extension folks, the reason no disabled information is getting included is indeed because we are loading this information at startup, and they are unable to provide it due to perf reasons. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1462124 to switch this to an async api you can call, and I will include in the response whether the full set of information is available yet. 

Sorry for the confusion!

**Comment by glogiotatidis** [comment]
OK per comment https://github.com/mozmeao/snippets-service/issues/343#issuecomment-389655291 we will deploy code to check only whether an addon is installed or not installed and I'll file a new issue to include "addon enabled" / "disabled" functionality when bug 1462124 lands.

Thanks for the investigation @k88hudson
