### ISSUE TITLE
[new filter] Filter based on open inspect element (or other devtools)

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#345]
Currently waiting for information to become available. [Bug 1431464](https://bugzilla.mozilla.org/show_bug.cgi?id=1431464)

**Comment by glogiotatidis** [comment]
https://github.com/mozilla/activity-stream/pull/4004

**Comment by k88hudson** [comment]
This has landed for 60

**Comment by glogiotatidis** [comment]
Let's prioritize this filter over other filters as Editors want to run tests as soon as possible with this.

**Comment by bensternthal** [comment]
Noted, I updated the priority list and will move the cards to reflect the above.
