### ISSUE TITLE
[new filter] Filter based on date of last Firefox use.

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#346]
Currently waiting for information to become available. [Bug 1431469](https://bugzilla.mozilla.org/show_bug.cgi?id=1431469)

**Comment by k88hudson** [comment]
Unfortunately I haven't had time to get this one yet, it may get pushed to 61 (I will update the bug next week)

**Comment by glogiotatidis** [comment]
Fixed in 61

**Comment by glogiotatidis** [comment]
From bugzilla
"""
We ended up only exposing the timestamp for the last time Activity Stream UNINIT'd which happens when the browser shuts down. It is exposed in snippets data as "previousSessionEnd".
"""

`gSnippetsMap.get("appData.previousSessionEnd")`
