### ISSUE TITLE
test_activity_stream failing against https://snippets.mozilla.com/

### ISSUE THREAD

**Issue by davehunt** [mozmeao/snippets-service#349]
https://snippets.mozilla.com/5/Firefox/default/default/default/en-US/release/default/default/default/ is returning no content, causing this test to fail:

https://github.com/mozmeao/snippets-service/blob/51d91f150d0031e6d4ea391a8292aa7f5e71648a/tests/test_snippets.py#L40-L46

The test is failing with:

```
     def test_activity_stream(base_url):
        url = URL_TEMPLATE.format(base_url, '5', 'release')
        soup = _parse_response(_get_redirect(url).content)
>       script = soup.find('script', type='application/javascript').text
E       AttributeError: 'NoneType' object has no attribute 'text'
```

/cc @glogiotatidis @stephendonner

**Comment by stephendonner** [comment]
This started passing again in build https://qa-master.fxtest.jenkins.stage.mozaws.net/job/snippets.prod/10612/

Around 3:28pm PDT?

**Comment by glogiotatidis** [comment]
Similarly to #330 the answer is that no-content is valid reply from the server. The content depends on the campaigns / snippets run by the snippets editors. 

Feel free to disable those tests since they are not actionable and failures are not real problems.

**Comment by davehunt** [comment]
Ah, I was under the understanding that prod would always serve content for activity stream on the release channel. If this is not the case then perhaps we should delete this test?

**Comment by glogiotatidis** [comment]
> Ah, I was under the understanding that prod would always serve content for activity stream on the release channel. If this is not the case then perhaps we should delete this test?

usually yes but apparently Snippet Editors left a weekend without content for the specific combination (activity stream, release, en-us, etc). 

You can disable this test or even all tests. We have other alerting about the service and I still plan to integrate some of your tests as deployment acceptance test.
