### ISSUE TITLE
Activity Stream Send to Device Template - update to allow other countries' phone numbers for SMS sends

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#354]
@jpetto For the Send to Device, we normally just do SMS in US. But now we're starting to incorporate countries like Germany.

I tried inputting this Germany domestic number: 015115716224 using SMS basket id: whatsnewfifty-snippet

But I think the template only takes 11 digits that will then allow me to hit send (US has 11 digits if we include country code). Can we update the template so it'll recognize other countries numbers as well? The Germany digits are 12 (including the country code).

**Comment by jpetto** [comment]
Do we expect people to enter a country code? If I'm in the US and have to enter a phone number in a field, I don't assume country code is necessary. (I assume it's added automatically if needed.)

**Comment by jkt230** [comment]
Hey Jon,

You're right it's only taking 10 digits right now.

1) Let's enable 10-11 digits for US so they can include country code if they want to
2) Let's enable 12 digits for Germany so they can include country code 

Not sure how you're going to update the back end to make sure that if it's a US number, that it only gets US texts (maybe that's based on the basket id) or that if it's a Germany number, that it only gets Germany texts.

**Comment by jpetto** [comment]
> Not sure how you're going to update the back end to make sure that if it's a US number, that it only gets US texts (maybe that's based on the basket id) or that if it's a Germany number, that it only gets Germany texts.

This should be handled by basket based on the supplied `locale`, `country`, and `message_id_sms`. I'm going to add the `country` param to the template so you can fill that out as well. For Germany, both the `locale` and `country` should be `de`. (Note that country codes do not always match the locale codes, e.g. `en-US` and `us`.)

I believe that basket will try to send the specified message ID localized for the `locale` specified. If it can't, it falls back to `en-US`.

**Comment by glogiotatidis** [comment]
Updated production
