### ISSUE TITLE
Activity Stream Send to Device Widget - locale parameter is not being passed on for email basket

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#358]
@jpetto 

For the Send to Device widget whether I use basket id: download-firefox-mobile OR download-focus-mobile and type in the locale parameter de OR fr, I still get the en version of the emails. The expected result is to get the de or fr version of the email. 

Can you please investigate?

Side note: I tested locale de and country de for the SMS message and did get a German SMS text message. So the SMS part is working.

**Comment by jpetto** [comment]
The issue with our testing was that the language for the email was not being specifically set to the value entered in the admin, and was instead being inferred from the `HTTP_ACCEPT_LANGUAGE` provided by the browser.

I believe this would have worked fine for a user with a German build of Firefox, as the `HTTP_ACCEPT_LANGUAGE` would be set to `de` for that build.

The PR filed above forces the `lang` value to be that of the `locale` specified in the snippet admin. This will fix our testing, but...

We are running into the difference between locale and browser build. Many folks outside the US use the en-US build of Firefox. Some of those folks change the default `HTTP_ACCEPT_LANGUAGE` to a different value (usually to their native language), while some leave it as the default - `en-US`.

The question is, do we want to force a communication to be in the language we specify, or do we want the language to be determined by the user's browser configuration?

I am not fully versed in how snippets are targeted to a specific locale. Is it by browser build? `HTTP_ACCEPT_LANGUAGE`? Geolocation?

**Comment by jkt230** [comment]
Can we take a look at how it was set up for the old template "Mobile Activation (Android, iOS, or both)"? Giorgos may have to point you to where that code is.

I tried it there and it was passing the right email (so if I input de for locale), I got the German version of the email.

**Comment by glogiotatidis** [comment]
pushed to prod
