### ISSUE TITLE
Update "Click or Dismiss" Logic for Specific Activity Stream Snippet Templates

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#368]
Hi Giorgos, 

Please confirm if this is correct:
Currently on all AS templates, when a user 
1) hit X on first scene 
2) click on hyperlink or button on first scene
3) click on "dismiss" button on second scene 

They will not see any snippets ever again with the same campaign field name. 

Because we have new templates that include second scenes, we don't want to consider the click on the button on the first scene to make it that they don't see snippets under the same campaign name ever again. This is because the first scene button is for users to continue the experience in the snippet (it's not an actual conversion).

For example, the Newsletter Sign Up template, we want to stop showing these snippets to users that actually converted on the second scene button (not the first scene button because first button is for them to continue to see the next scene). 

The templates that need logic update so that a click on hyperlink or button on first scene is NOT looped into the "do not show users these snippets under the same campaign name" group:
-AS FxA sign up / sign in
-AS Newsletter Sign Up
-AS Send to Device

Let me know if you need clarification.

**Comment by jkt230** [comment]
Err at the risk of getting yelled at, I'm just going to cc you once! @glogiotatidis

**Comment by glogiotatidis** [comment]
> Err at the risk of getting yelled at, I'm just going to cc you once! @glogiotatidis

ahha no worries but fyi i get all issues created here anyway :)

**Comment by glogiotatidis** [comment]
Apologies for the delay, I'll check tomorrow and reply here.

**Comment by glogiotatidis** [comment]
And this has been pushed back, still under my radar

**Comment by glogiotatidis** [comment]
Templates with first and second scene:

 - Firefox Accounts Signup 
 - Newsletter Signup
 - Send to Device
 - Video Snippet

What's currently happening in all templates for Scene 1:
 - Clicking `X` button in Scene 1 *blocks* the snippet
 - No other buttons in Scene 1 block the snippet, i.e. clicking button / link to advance to Scene 2

What's currently happening in all templates for Scene 2:
 - Clicking on `Dismiss` button in Scene 2 *blocks* the snippet
 - Additionally for `Newsletter Subscribe` and `Send to Device` snippets where we have `OK` and `Error` scenes to display the outcome of the action, clicking `Remove This` blocks the snippet.
 - For `Video Snippet` we don't have a `Dismiss` button but a `Done` button in Scene 2 which does not block the snippet. Only the `X` button in Scene 1 does.

**Comment by glogiotatidis** [comment]
> The templates that need logic update so that a click on hyperlink or button on first scene is NOT looped into the "do not show users these snippets under the same campaign name" group:
> -AS FxA sign up / sign in
> -AS Newsletter Sign Up
> -AS Send to Device

According to my previous comment this is what's happening right now. Only clicking on `X` on first scene blocks the snippet.

@katjoy @mediaChick do the above answer this issue?

**Comment by katjoy** [comment]
Awesome. Yes, the above answers the issue. Thank you @glogiotatidis!
