### ISSUE TITLE
Test Pilot Filtering not working on about:newtab

### ISSUE THREAD

**Issue by katjoy** [mozmeao/snippets-service#370]
I have signed up for Test Pilot and currently have the Notes experiment enabled.  I'm seeing a Test Pilot snippet (#7874) that was programmed to filter to "Show only to users without Test Pilot" and I am not seeing the Test Pilot snippet (#7878) that was programmed to filter to "Show only to users with Test Pilot."  We wanted to confirm that Test Pilot filtering is working correctly. 

 
![7874 without test pilot](https://user-images.githubusercontent.com/35277419/37793599-6778873c-2dcc-11e8-9a73-d2d4d418be1e.png)
![7878 with test pilot](https://user-images.githubusercontent.com/35277419/37793600-678caa64-2dcc-11e8-9106-a59c023399ae.png)
<img width="1036" alt="test pilot - notes enabled" src="https://user-images.githubusercontent.com/35277419/37793602-67a0d304-2dcc-11e8-83fb-92ac58b87500.png">
<img width="480" alt="test pilot add-on enabled" src="https://user-images.githubusercontent.com/35277419/37793603-67b3f358-2dcc-11e8-86c9-c1441fab703b.png">

**Comment by glogiotatidis** [comment]
Sorry for the delay, I'll take a look tomorrow and reply here

**Comment by glogiotatidis** [comment]
I did some digging and this is an interesting one...

Testpilot does work on `about:home` and it doesn't work on `about:newtab`. The first is the first page you get to see when you open firefox and the later is the page you see on every new tab. They appear to be the same but they are not under the hood.

Testpilot whitelists `about:home` and we can query it's existence there and thus filtering there works. Testpilot's whitelist does not include `about:newtab` and we cannot query in newtab and thus snippets believe that the addon does not exist.

This is something that the testpilot team controls. I filed issue https://github.com/mozilla/testpilot/issues/3451 to request that they whitelist `about:newtab` .

In the meanwhile the testpilot addon targeting is semi-broken.

**Comment by glogiotatidis** [comment]
Update: this seems that will remain as is (i.e. semi-working) until the release of Firefox 60 on 2018-05-09. 

I'm going to close this issue in favor of #343, which will provide a solution to this problem.

Thanks for the detailed initial report @katjoy . Your screenshots and overall issue reporting approach really helped.
