### ISSUE TITLE
[prod tests] test_legacy test fails with exception: AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by stephendonner** [mozmeao/snippets-service#373]
We're seeing the following error in our snippets.prod suite[0]:

```
Error Message

AttributeError: 'NoneType' object has no attribute 'text'

Stacktrace

base_url = 'https://snippets.mozilla.com'

    def test_legacy(base_url):
        url = URL_TEMPLATE.format(base_url, '3', 'release')
        soup = _parse_response(_get_redirect(url).content)
>       script = soup.find('script', type='text/javascript').text
E       AttributeError: 'NoneType' object has no attribute 'text'

base_url   = 'https://snippets.mozilla.com'
soup       = 
url        = 'https://snippets.mozilla.com/3/Firefox/default/default/default/en-US/release/default/default/default/'

tests/test_snippets.py:43: AttributeError
```

[0] https://qa-master.fxtest.jenkins.stage.mozaws.net/job/snippets.prod/18722/

**Comment by stephendonner** [comment]
Empty/0-length content, yeah?

https://www.webpagetest.org/result/180403_TC_e40a978e53c88d4a66c0c66aa28e1496/1/details/#step1_request2

**Comment by glogiotatidis** [comment]
@stephendonner thanks for filing this. As we discussed earlier this year  those tests provide little value as they are depended on the content edited by the snippets team and not the code itself. In this case snippet editors do not send any snippets to old pre-activity stream browsers

We run some tests against the services when we deploy new code and we monitor the availability of the service using synthetics. Eventually we may integrate some of your more detailed tests in our deployment test suite. 

I suggest that you disable all related snippets tests. Thoughts?

**Comment by stephendonner** [comment]
@glogiotatidis if you're confident they don't-yet provide value, and have more false-positives/negatives, sure.

And just to be clear, "disable all related snippets tests" means all of https://github.com/mozmeao/snippets-service/tree/master/tests, not just this failing test, right?  (There are only 3 tests, but multiple iterations/runs, due to testing different channels.)

For starters, I'll at least get up a PR to remove this test, as it's flooding our inbox :-)

/cc @davehunt

**Comment by jgmize** [comment]
Fixed in https://github.com/mozmeao/snippets-service/commit/fa6995a6357d02671d8f97d0ee32d4fbc48a8e04

**Comment by glogiotatidis** [comment]
We stopped webqa tests so this a wontfix. thanks all

**Comment by davehunt** [comment]
@stephendonner I notice that we still have snippets jobs in Jenkins. The prod job is passing, and the stage job has been disabled since April 18th. Should we delete these jobs? /cc @glogiotatidis

**Comment by glogiotatidis** [comment]
Yes please remove all jobs. We have our own monitoring. Thanks!

**Comment by stephendonner** [comment]
Done; I've removed:
* https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/snippets.adhoc/
* https://qa-master.fxtest.jenkins.stage.mozaws.net/job/snippets.prod/
* https://qa-master.fxtest.jenkins.stage.mozaws.net/job/snippets.stage/
