### ISSUE TITLE
production is ahead of master

### ISSUE THREAD

**Issue by jgmize** [mozmeao/snippets-service#381]
When I was trying to deploy to snippets-admin in oregon-b after merging #380 I found out that the [production branch is ahead of master](https://github.com/mozmeao/snippets-service/compare/master...production). I ended up doing a manual deploy to work around this, but if [this test still needs to be commented out in production](https://github.com/mozmeao/snippets-service/commit/8c44094a22b6c8223a0f1cdaeb4cad2b124e0059), should it not also be commented out (or deleted) in master?

**Comment by glogiotatidis** [comment]
Good catch jgmize. I synced the branches and updated those tests.
