### ISSUE TITLE
Snippets Cost Remediation: Change Snippet Bundles To Only Contain The Decision Engine, Move Snippet Content Entirely Out Of Bundle

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/snippets-service#387]
If brotli compression does not reduce costs enough...

Rather than bundle all the Snippets and the logic for display together we will separate these and only ship the decision logic in the bundle. Once a decision is made on which Snippet to display, the content will be loaded via link. This should:

- Reduce the size of the bundle, generally from 4Mb to 120Kb for a bundle containing 150 Snippets.  
- Only download snippets the user actually sees.
- Images will still be embedded Data URIs

**Comment by glogiotatidis** [comment]
Brotli compression significantly reduced costs (bundle size down to 0.5mb from 2.2Mb when gzipped).

We will change the payload to link to images instead of including them as data URIs. This change will be applied to SnippetsNG (AS Router) payload. Tracked in #634

**Comment by glogiotatidis** [comment]
Decision engine will move to AS Router in the near future which will render this obsolete. Closing.
