### ISSUE TITLE
Snippets Cost Remediation: Change Images From Embedded Data URIs To Links

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/snippets-service#388]
If brotli compression is not engouht..change images from being embedded data URIs to links. This should:

- Without images bundle size is reduced to  ~1.1MB or 50Kb in transfer cost after GZIP.  
- Allow images to be cached by the browser.
- Only download images the user actually sees.

**Comment by glogiotatidis** [comment]
Brotli compression provided enough reduction in Apr. To improve on that we will go fwd with moving the images outside the bundle for SnippetsNG. Tracked in #634
