### ISSUE TITLE
[SCL3 Decom] Trying to figure out why we're still getting traffic to snippet-stats.mozilla.org 

### ISSUE THREAD

**Issue by fox2mike** [mozmeao/snippets-service#396]
@vyas85 and I were chatting about the upcoming SCL3 decom and were trying to understand why we're still seeing production traffic to https://snippets-stats.mozilla.org/foo.html

Seems like there was a change made for https://github.com/mozmeao/snippets-service/pull/302 (72e19196bf4be52d71aa89a16cec49a1b3ceb99a) which changed the URL from the one above to https://snippet-stats.moz.works/foo

We still see about 3403865 hits for the period from April 16 to April 30th. I'm also seeing all versions of Firefox across multiple platforms all the way from 15 to 60. 

This will block the SCL3 exit, so we need to figure out what's going on here. Thanks!

**Comment by glogiotatidis** [comment]
Hi @fox2mike!

snippets-stats.m.o is not owned by us. It's something the Data Team built back in the day and it collects data that it's fed to Tableau. This is actively used by Marketing for analytics. Maybe Josephine T knows more (Matt Pressman used to be also involved)

**Comment by bensternthal** [comment]
@glogiotatidis 

Ok to make this discussion easier lets refer to these systems as:

AWS = https://snippet-stats.moz.works/foo
SCL3 = https://snippets-stats.mozilla.org/foo.html

I started poking around a bit.. just to be 100% sure am I correct that snippets no longer uses SCL3 as the analytics endpoint when using the [proxy](https://github.com/mozmeao/snippets-stats-proxy).

And that the hits Shyam is seeing are coming from something other than snippets... at least that is our hypothesis?

**Comment by mwarther** [comment]
@bensternthal we do get some snippet reporting from Tableau in addition to GA, not sure if that's related. the creation of that reporting pre-dates me, so don't have a lot of details on the how/when it was set-up.

**Comment by fox2mike** [comment]
Hey @glogiotatidis, @vyas85 is our current Data Team manager ;) and we're both really baffled by where this traffic is coming from :) Specifically because all the hits go to snippets-stats.mozilla.org/foo.html and no where else and we're seeing hits from across the board - mobile, desktop, multiple different versions of Firefox etc.

**Comment by bensternthal** [comment]
Ok we have logs from shyam and will be researching.. thanks for the help.

**Comment by bensternthal** [comment]
OK I think I got to the bottom of this.

There seems to have been an assumption made that because we changed the URL in the snippets-service the snippets stat collector run by the Data Team was no longer in use.

**This is not true.**

We changed the url to use a [proxy](https://github.com/mozmeao/snippets-stats-proxy). The proxy is still hitting https://snippets-stats.mozilla.org/foo.html

AFAIK there have never been plans to decom snippet-stats. It's an active service that is very much in use.

**Comment by fox2mike** [comment]
@bensternthal  and I had a chat - and this all makes sense. I think @vyas85 is going to reach out to @mwarther and figure out what stats they like to see and if GA is sufficient. Once that conversation happens, we can figure out a future path for snippets-stats.mozilla.org. 

Thanks for all the help here folks!
