### ISSUE TITLE
Open Questions

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/snippets-service#404]
- How long do we need to support pre-as. Understand how many versions back. 
- How long do we need metrics from pre-as/esr.
- Ping center.. when do we need to do this.. guidance from legal
- Content Signing

**Comment by glogiotatidis** [comment]
- Which filtering capabilities we have in the new ASI.
- Can we use UITour in the new ASI

**Comment by glogiotatidis** [comment]
* We are going to launch with one template only (simple snippet) in Fx62. Does the LCM team want to automatically serve all the Activity Stream Simple Template based Snippets to the new Activity Stream version or they want to have a different set of snippets?

**Comment by bensternthal** [comment]
closing this one.. created sep issues for each.
