### ISSUE TITLE
Remove deprecated JSON (Fennec) snippets code

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#469]
The JSON backend was used to serve snippets to Fennec. Last JSON snippets were on Sept 2017, when Fennec switched to another platform. 

This issue tracks the removal of code related to JSON snippets

Papertrail webserver logs return no results for `/json/1/` which is the URL used for Fennec snippets

## Deployment plan
- [x] Export JSON snippets to CSV, share with LCM team
- [x] Backup prod DB
- [x] Push to prod

**Comment by glogiotatidis** [comment]
@bensternthal Can you please confirm that this is the case for Fennec snippets so we can proceed and remove some code and tech debt?

**Comment by bensternthal** [comment]
on it.

**Comment by bensternthal** [comment]
Do not decom yet. Michele is looking into running an "upgrade snippet" and once that finishes it's run we can likely decom.

**Comment by glogiotatidis** [comment]
> Do not decom yet. Michele is looking into running an "upgrade snippet" and once that finishes it's run we can likely decom.

ACK

**Comment by glogiotatidis** [comment]
latest update: Fennec Snippets code is still around, even on the latest Firefox versions. Reaching out to Firefox team about this

**Comment by glogiotatidis** [comment]
Snippets on Android are fetched but not displayed. Filed [bug 1482836](https://bugzilla.mozilla.org/show_bug.cgi?id=1482836) to track the removal of Snippets code.

We 're still investigating
 - when Leanplum was integrated in Fennec
 - if the removal of snippets-service fennec code will cause any issues to older Fennec versions.

**Comment by glogiotatidis** [comment]
> when Leanplum was integrated in Fennec

Leanplum was integrated on Fx56 according to [wiki](https://wiki.mozilla.org/QA/Fennec/LeanPlum).

**Comment by glogiotatidis** [comment]
> if the removal of snippets-service fennec code will cause any issues to older Fennec versions.

Fennec team suggested that we can proceed with server code removal thus this should not be an issue.

**Comment by glogiotatidis** [comment]
With the LCM team we agreed to run a few messages in 2018 targeting users on versions <= 55. We will discuss decom in 2019-Q1.

**Comment by glogiotatidis** [comment]
We have green light from the LCM team to decom. Adding this to the work queue

**Comment by glogiotatidis** [comment]
aaaand gone! 


![image](https://media1.giphy.com/media/7DzlajZNY5D0I/giphy.gif)
