### ISSUE TITLE
Implement JSON snippets endpoint for AS Router

### ISSUE THREAD

**Issue by k88hudson** [mozmeao/snippets-service#503]
## Specs
* MozMeao will develop a new “Activity Stream NG” endpoint.
* The URL for the new endpoint will start with /6/, otherwise it will follow the exact same format of existing endpoints.
* The endpoint will return a JSON formatted response adhering to this [this schema](https://github.com/mozilla/activity-stream/blob/master/content-src/asrouter/schemas/provider-response.schema.json).

## Risks

- [ ] JSON Spec not Final

---

### Original Request From Kate
We'd like to have a JSON-based endpoint from the snippets service for our experiment in 62. The expected response should follow [this schema](https://github.com/mozilla/activity-stream/blob/master/system-addon/content-src/asrouter/schemas/provider-response.schema.json), which is essentially a JSON object containing a single property `messages`, an array of messages. 

You can see a full example response here: https://activity-stream-icons.services.mozilla.com/v1/messages.json.br

So far, we've only implemented the `simple_snippet` template designed to be backwards compatible with the existing activity stream simple snippet. The schema for this is [here](https://github.com/mozilla/activity-stream/blob/master/system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json). The only new variable we've introduced so far is `button_type`, which is kind of a temporary way of having a link show up at the end of the `text`. We can probably remove this when we land https://bugzilla.mozilla.org/show_bug.cgi?id=1457233, which adds support for HTML in snippet content.

Let me know if there's anything else you need/if there are any changes we should make to the schema to make the integration smoother for you guys. Thanks @glogiotatidis @pmac!

*Edit: updated broken schema link*

**Comment by glogiotatidis** [comment]
Thanks for filing @k88hudson 

Schema looks good. I understand why `button_type` is there but since there's already a bug to add support for HTML so there's no need to implement this for Fx62. Is this assumption correct?

**Comment by glogiotatidis** [comment]
@k88hudson I's thinking about naming the new endpoint `Activity Stream NG` and start the url with `/6/`. Sounds good?

**Comment by k88hudson** [comment]
Awesome!

**Comment by glogiotatidis** [comment]
Also where does the JEXL part fit in the schema @k88hudson ?

**Comment by glogiotatidis** [comment]
@k88hudson can you confirm that's OK if the endpoint returns

 - 200 with JSON content
 - 302 to JSON content
 - 204 with no content (optional)

?

**Comment by glogiotatidis** [comment]
@k88hudson your current schema for simple template does not match the simple template currently in use. Besides the `button_type` that we already talked about, there' re multiple fields missing:
 
```
  @blockable: checkbox - Check to allow user to block this snippet.
  @button_background_color: hash, optional - Button background color. Default #D7D7DB.
  @button_color: hash, optional - Button text color. Default #0C0C0D.
  @title_icon: image, optional - Title icon. 16x16px. SVG or PNG preferred. Grayscale.
  @tall: checkbox, optional - Fundraising only, increases height to roughly 120px.
```

Could you please provide some insight on whether these are going to be supported or not?

**Comment by k88hudson** [comment]
re other variables, I filed a ticket[ here](https://bugzilla.mozilla.org/show_bug.cgi?id=1464126) to implement these; would it be ok to remove `blockable`/(default it to `true`) though? I think we want to make sure all snippets are blockable

**Comment by k88hudson** [comment]
re the HTTP codes, I will write some tests to confirm the they work as expected

**Comment by glogiotatidis** [comment]
> ok to remove blockable/(default it to true) though? I think we want to make sure all snippets are blockable

(capturing what we said in the mtg): Lisa will discuss with LCM team about the block button.

**Comment by ldwright** [comment]
@glogiotatidis Per the above, LCM is comfortable with making blocking a default/standard on all snippets. Currently the checkbox always gets checked when snippets are programmed and we weren't able to identify any mission critical use cases where a snippet would need to not be blockable. We’ll want to remove that checkbox from the Admin side if it’s no longer necessary, too.

**Comment by ldwright** [comment]
@glogiotatidis Per the above, LCM is comfortable with making blocking a default/standard on all snippets. Currently the checkbox always gets checked when snippets are programmed and we weren't able to identify any mission critical use cases where a snippet would need to not be blockable.

**Comment by k88hudson** [comment]
@glogiotatidis oops, sorry! updated link is here:

https://github.com/mozilla/activity-stream/blob/master/content-src/asrouter/schemas/provider-response.schema.json

**Comment by k88hudson** [comment]
(I also updated the top comment)

**Comment by glogiotatidis** [comment]
This is now in production
