### ISSUE TITLE
Pingcenter Integration

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/snippets-service#515]
AS team is responsible for implementing template <--> pingcenter integration.

Our requirements for the 62 are that the Simple Snippet template sends the following data to pingcenter:

- Impressions
- Clicks 
- Blocks
- Arbitrary Values set via html custom data attributes (data-metric)

**Comment by glogiotatidis** [comment]
@k88hudson can you please confirm that AS Router sends the following data to pingcenter and provide links to docs /code?

``
    Impressions
    Clicks
    Blocks
    Arbitrary Values set via html custom data attributes (data-metric)
``

**Comment by glogiotatidis** [comment]
We have confirmation for impressions, clicks and blocks. Will ping again to get confirmation on custom metrics 

https://sql.telemetry.mozilla.org/dashboard/activity-stream-experiment-beta-61-activity-stream-router

**Comment by k88hudson** [comment]
Custom metrics are available for links as well, see the bottom of this page: https://activitystream.gitbook.io/as-router/api-reference/template-fields#richtext-and-richlink

Essentially for any link, a custom metric field can be passed along via the `metric` property.

**Comment by glogiotatidis** [comment]
We have confirmation and ASR collects and sends the said pings to Ping Center.
