### ISSUE TITLE
Activity Stream Segmentation Analysis

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/snippets-service#517]
- Which filtering capabilities we have in the new ASI.
- Can we use UITour in the new ASI

**Comment by glogiotatidis** [comment]
See also #521

**Comment by glogiotatidis** [comment]
> Which filtering capabilities we have in the new ASI.

The docs here describe the available JEXL which define the filtering capabilities besides locale and channel (which two are server side)

https://github.com/mozilla/activity-stream/blob/master/content-src/asrouter/schemas/message-format.md#targeting-attributes

> Can we use UITour in the new ASI

AS provides another way to open Special / Deep links that we used UITour for. We still gather info on how this can be used by Snippets.
