### ISSUE TITLE
Decide if We Serve All Activity Stream Simple Templates to Fx62 or subset.

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/snippets-service#518]
We are going to launch with one template only (simple snippet) in Fx62. Does the LCM team want to automatically serve all the Activity Stream Simple Template based Snippets to the new Activity Stream version or they want to have a different set of snippets?

**Comment by glogiotatidis** [comment]
Take into account the fact that we probably would have limited targeting capabilities as well. See #517

**Comment by glogiotatidis** [comment]
Given that we're going to have limited targeting options, I suggest that we create new Snippets for Fx62. 

When we get all targeting options and templates available (that's probably Fx63) we could build automation to migrate existing Snippets to the new Activity Stream integration to lower the burden on Content Creators.

@Ldwright can you please help with this decision?

**Comment by glogiotatidis** [comment]
We hand picked 5 snippets to run on SnippetsNG

https://activity-stream-icons.services.mozilla.com/v1/messages.json.br

Will go with these for now and we can re-eval before prime time if needed
