### ISSUE TITLE
Figure out how JEXL is going to work

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#520]

**Comment by glogiotatidis** [comment]
We're waiting on specs and a couple of filters made available by the AS team so we can test.

**Comment by bensternthal** [comment]
Docs due next week.

**Comment by glogiotatidis** [comment]
Docs here [message-format.md#targeting-attributes](https://github.com/mozilla/activity-stream/blob/master/content-src/asrouter/schemas/message-format.md#targeting-attributes)

**Comment by glogiotatidis** [comment]
We now know who this is going to work. Filed #617 to implement it
