### ISSUE TITLE
Preview of Snippets in the new Activity Stream 

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#522]
We need a way to preview the snippets in the system. Currently we host the templates and we render a fake `about:home` page with the template content.

We discussed about extending AS addon so it can preview snippets directly in the real `about:home` page. One possible solution would be to allow URLs like

  - `about:home?preview=XXXX-XXXX`

where `XXXX-XXXX` is a uuid generated by the snippets service. Then AS would fetch snippets as usual from the snippets-service but instead of hitting the normal URL it would hit the preview url with the uuid, e..g  https://snippets.mozilla.com/preview/XXXX-XXXX/json, which in turn would return a valid json response to be directly loaded in AS.

The benefits of this approach is that 
 1. we don't have to have the templates in the snippets service,
 2. Everyone can get a preview link to proof check the snippet before going live. Especially useful when the LCM team runs snippets for other teams, for example the Pocket team. LCM will just share a link and we don't need to create separate logins
 3. The preview is going to happen within the real addon, instead of a mockup page which will allow of special links (see #521, #352) to work.

Questions:
 - Probably we need to whitelist snippets.m.c to be able to open links like `about:home?preview=` ?

**Comment by piatra** [comment]
Addons can't link to certain `about:` pages like `home` and `newtab`.
Right now ASRouter endpoint can be changed through prefs to point to a different location. It's not a great process but shouldn't that be enough to preview new snippets?

**Comment by glogiotatidis** [comment]
I'm afraid changing prefs manually is not acceptable as a preview method. 

So to make sure I understand correctly we cannot make the AS addon read a parameter from the URL and change the location from where it requests snippets?

In other words AS cannot read `XXXX` from `about:home?preview=XXXX`?

**Comment by glogiotatidis** [comment]
(adding more info)

It won't have to change the `about:config` pref b/c it's preview, we only need to get the url once and display the snippet

**Comment by piatra** [comment]
> I'm afraid changing prefs manually is not acceptable as a preview method.

Got it

> So to    sure I understand correctly we cannot make the AS addon read a parameter from the URL and change the location from where it requests snippets?
In other words AS cannot read XXXX from about:home?preview=XXXX?

Sorry I misunderstood this. Yes AS can read query parameters but there is still the issue of security around `about:` pages and not being able to link to them. A user would have to manually open the tab and paste that address in.

> Probably we need to whitelist snippets.m.c to be able to open links like about:home?preview= ?

Website whitelisting isn't very likely due to how access is implemented ([this is the flag about:home/newtab is missing](https://searchfox.org/mozilla-central/rev/eb51d734a8c06ac5973291be9bcc74ed4e999bca/browser/components/about/AboutRedirector.cpp#72)) but I'm don't have much experience with this, maybe someone else knows more.

**Comment by k88hudson** [comment]
I think we'll be able to use a URL-based method like you described, however we have to do it through some kind of intermediary page (maybe `about:messages` or something like that) as well as have some UI to clearly indicate you are in a "preview mode".

I filed a bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1463836, and @piatra is going to book an initial meeting with security to get some feedback on possible approaches for this

**Comment by glogiotatidis** [comment]
Excellent! Going through an intermediary page shouldn't be a problem, as long as it's as automatic (read "one-click") as possible. 

Yes to preview mode!

**Comment by glogiotatidis** [comment]
Currently blocked by [1477631](https://bugzilla.mozilla.org/show_bug.cgi?id=1477631)

**Comment by glogiotatidis** [comment]
Moving this to 2018Q3 milestone

**Comment by glogiotatidis** [comment]
Note to self: ASR Preview requires snippets to get saved first.
