### ISSUE TITLE
Update SSO callback URLs

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#532]
We're going to be move snippets-admin to `https://snippets-admin.mozilla.org`. File an issue in ServiceNow to update the SSO callback URLs when the new domain is in place.

See also

 - https://github.com/mozmeao/infra/issues/843
 - https://github.com/mozmeao/snippets-service/issues/522

**Comment by jgmize** [comment]
see https://github.com/mozmeao/infra/issues/843#issuecomment-402274810 -- next step is to update SSO callback url

**Comment by glogiotatidis** [comment]
Filed servicenow request to update callback and logout URLs

**Comment by glogiotatidis** [comment]
- Updated `ADMIN_REDIRECT_URL` in snippets-prod tokyo, frankfurt, oregon.
 - Updated SSO callback URLS
 - Emailed users with active logins about the URL change.

This is now done. Thanks!
