### ISSUE TITLE
[new permission] Snippet Editor

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#534]
For each channel (release, beta, etc) create a new permission that will allow users to `create` / `edit` / `delete` snippets.

This permission is not sufficient for users to `publish` a snippet.

This is currently only for the Desktop Snippets

**Comment by glogiotatidis** [comment]
I believe we got this. @mozmeao/omn-team is there anything else needed here?

**Comment by stsegovia-moz** [comment]
We can close this. Thank you!
