### ISSUE TITLE
[new permission] Snippet Viewer

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#535]
For each channel (release, beta, etc) create a new permission that will allow users to view snippets.

This permission must not allow any editing.

This is currently only for the Desktop Snippets

**Comment by glogiotatidis** [comment]
@mozmeao/omn-team is this still needed / useful?

**Comment by stsegovia-moz** [comment]
I don't think this is urgent or quite necessary at the moment. Since we don't have plans to scale the team or foresee any viewers, I don't believe that's necessary.

**Comment by glogiotatidis** [comment]
KK closing for now
