### ISSUE TITLE
500 Errors Reported Via Admin Users

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/snippets-service#542]
Kat & Michele both encountered a 500 error around 9.53- 9.57 am PT. The issue looks to have resolved itself but wanted to flag if we wanted to poke around the logs.

**Comment by bensternthal** [comment]
Looking in papertrail I see a lot of errors:

`Jun 06 10:42:33 ip-10-0-39-207 kubernetes.var.log.containers.kube-controller-manager-ip-10-0-39-207.us-west-2.compute.internal_kube-system_kube-controller-manager-e9aa9a1bd3c8ca07fbec5e3d51b4f714bcdadaf1777e7555dbbc5b7e17f7d876.log: {"log":"I0606 17:42:33.166617       5 deployment_controller.go:483] Error syncing deployment snippets-prod/snippets-prod-web: Operation cannot be fulfilled on deployments.extensions \"snippets-prod-web\": the object has been modified; please apply your changes to the latest version and try `

& 

`
Jun 06 10:21:38 ip-10-0-61-165 kubernetes.var.log.containers.snippets-admin-web-6f79bff885-w9n2v_snippets-admin_snippets-admin-web-71255c2600ecb92745c8ea9740ef7a6e11c2c151ef781153194e49125e1f5839.log: {"log":"django.db.utils.OperationalError: (2005, \"Unknown MySQL server host 'ee-mariadb-us-west.c03fennjgqdk.us-west-2.rds.amazonaws.com' (-3)\")\n","stream":"stderr","time":"2018-06-06T17:21:30.888348456Z"} `

**Comment by jgmize** [comment]
The "Unknown MySQL server host"  error is one we've seen intermittently on several apps. Internal DNS resolution (and networking in general) in AWS is unfortunately not as reliable as we'd like and is one of the reasons we're evaluating GCP.

**Comment by jgmize** [comment]
No further issues or action needed.
