### ISSUE TITLE
62 Snippet Specs

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/snippets-service#544]
The following are the implementation details for the 62 snippet. 

- **Only** the Simple Snippet With Button template will be served as part of this experiment. {if not just simple snippet [AS must provide list of templates they will implement](https://docs.google.com/a/mozilla.com/document/d/1E_1hxrU4GNMwKz6rwN4Iw8LoTefUmUl6wneyJ9-7U84/edit?disco=AAAAB-fQSYM)} :heavy_exclamation_mark:
- The appearance of the snippet **will** match the current version.
- The customization options **will** match the current version.
- Targeting **will** include release channel and locale. {Verify this matches AS reqs.} :heavy_exclamation_mark:
- JEXL based targeting **may be** included and is dependent on specs from AS.
- The template **will** be served from a new system developed by AS.

**Comment by glogiotatidis** [comment]
Also 
 * The response **may** will be content signed #516

**Comment by glogiotatidis** [comment]
We successfully delivered for Firefox 62 the above except for:
 * The response **may** will be content signed #516 
 * JEXL based targeting may be included and is dependent on specs from AS.

Marking fixed.
