### ISSUE TITLE
End Legacy Analytics Support

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/snippets-service#545]
Pingcenter is only available in newer versions (63+ we think) of firefox. Therefore we need a sunset strategy for GA in older versions.

## Requirements from Marshall 

1. Ideally should not respect DNT, rather should respect telemetry setting and apply to all measurements. Includes impression & clicks.
1.  Proxy usage is within policy. Sunset policy is on us.

## Handy Docs
- [Hybrid-Content Migration Guide](https://docs.google.com/document/d/1ylmdvAD5XYdQneVr-4indH3aDLRG_fWD0putn1cq2oE/edit?ts=5b16a03c#)
- [In-Product Third-Party Analytics Policy - 2018 Q2 Update](https://docs.google.com/presentation/d/1pgyprAMV6-02J0q9kYiYg3r4LVuUjOwoHGsMmMW6zmE/edit?ts=5b169efd#slide=id.g1e194307db_0_124)

**Comment by glogiotatidis** [comment]
> Ideally should not respect DNT, rather should respect telemetry setting and apply to all measurements. Includes impression & clicks.

We already do that for AS snippets. [Code](https://github.com/mozmeao/snippets-service/blob/master/snippets/base/templates/base/includes/snippet_as.js#L601)

> Proxy usage is within policy. Sunset policy is on us.

ACK. I suggest that we sunset together with the Snippets for 1-4 Startpage Versions (i.e. old about:home) and with 5 Startpage Version (i.e. current AS implementation). We should plan that for EOY 2018

**Comment by glogiotatidis** [comment]
- After we deploy AS Router to 100% of all browsers, for how long do we want to:
  - Be able to collect metrics, including impressions, clicks and blocks for Snippets from old systems?
  - Be able to publish new Snippets to old systems?

Definition of `old systems`:  
 - All Snippets targeted to Startpages 1-4 (pre Quantum)
 - All Snippets targeted to Startpages 5 (Quantum and up to the firefox we fully deploy AS Router)

@ldwright can you help answer the above questions?

**Comment by glogiotatidis** [comment]
> Does this help?

Yes, thank you! :cake: 

Per previous comment moving this to 2019Q1

**Comment by glogiotatidis** [comment]
Will discuss this with the LCM team next week to set a EOL date.

/remind me in two weeks

**Comment by glogiotatidis** [comment]
We'll sunset this on May 15th

/remind me to check on may 08th

**Comment by glogiotatidis** [comment]
- [ ] Update `METRICS_URL` in running instances
- [ ] Remove Infra
- [ ] Archive repository
- [ ] Remove references in https://abouthome-snippets-service.readthedocs.io/en/latest/data_collection.html#google-analytics-for-firefox-63-and-earlier

**Comment by glogiotatidis** [comment]
It's happening! Check list in https://github.com/mozmeao/snippets-service/issues/545#issuecomment-485384942

**Comment by glogiotatidis** [comment]
Done updating the metrics URL. Will confirm within the week that we receive stats directly to Tableau before moving on with next steps.

**Comment by glogiotatidis** [comment]
Verified that Tableau still gathers data

**Comment by glogiotatidis** [comment]
Updated data collection docs
![image](https://user-images.githubusercontent.com/584352/57911937-c6a7fd80-7891-11e9-8583-e05b9ac67258.png)

**Comment by glogiotatidis** [comment]
Hey @jgmize @metadave there 're a few infra related steps in https://github.com/mozmeao/snippets-service/issues/545#issuecomment-485384942 which I'm not sure whether I should do from console or we have automation for them. 

Could you please take a look and advise or even take over if it's something you want to do?

Thanks!

**Comment by glogiotatidis** [comment]
/remind me in a month to archive repo

**Comment by glogiotatidis** [comment]
@metadave manually removed

- Route 53
-    Zone entry
-    Traffic Policy
-    Health Checks

as discussed yesterday. Waiting on steps for ELBs and Certs.

**Comment by glogiotatidis** [comment]
Friendly ping @jgmize @metadave  to help check the last boxes from https://github.com/mozmeao/snippets-service/issues/545#issuecomment-485384942

**Comment by glogiotatidis** [comment]
We still have some work to do on this as it has been pushed back due to other priorities.

/remind me to re-check and archive in a month

**Comment by jgmize** [comment]
@glogiotatidis I've deleted the ELBs, certs, and relevant route53 automation. The last unchecked box in https://github.com/mozmeao/snippets-service/issues/545#issuecomment-485384942 is to archive the repo. Do you want to add anything to the description or the README before we archive?

**Comment by glogiotatidis** [comment]
> @glogiotatidis I've deleted the ELBs, certs, and relevant route53 automation. The last unchecked box in [#545 (comment)](https://github.com/mozmeao/snippets-service/issues/545#issuecomment-485384942) is to archive the repo. Do you want to add anything to the description or the README before we archive?

thanks! I've added text in the `snippets-service` docs about the stats proxy decom, no need to update the readme. I'll go ahead and archive
