### ISSUE TITLE
Research Snippet Spend

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/snippets-service#571]
Cloud health is reporting an increase in snippet spend that does not look consistent with traffic.

In other words traffic and bytes transferred look generally the same as the previous month.

Reached out to shyam.. I am not sure I trust cloudhealth is reporting the right info.

**Comment by bensternthal** [comment]
May 
All Data:	Total: 535,755.1151 GB
All Requests:	Total: 5,778.2412 M
Cloudhealth Cost: 6.18k

June
All Data:	Total: 421,136.9878 GB
All Requests:	Total: 5,073.7948 M
Cloudhealth Cost: 12.73k So far

**Comment by metadave** [comment]
met w/ Shyam today, we can't find any extra charges for the Snippets CDN. Shyam will email us screenshots of our findings.

**Comment by metadave** [comment]
thanks @pmac for pointing out that this [snippet](https://snippets-admin.us-west.moz.works/show/uuid/2b5fd5a7-60b4-4d19-b417-c8c03c431d4f/ ) is using a [preload](https://github.com/mozmeao/snippets/blob/master/activity-stream/simple-video-snippet.html#L189).
