### ISSUE TITLE
Snippet Admin Returning 500

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/snippets-service#572]
Reported to me via slack by michelle and I confirmed. 

The following url returns 500. Note other urls seem to be fine.
https://snippets-admin.us-west.moz.works/admin/base/snippet/

@jgmize tagging you in here in case this is infra related if not, will have @glogiotatidis  look at tomorrow morning. 

<img width="774" alt="screen shot 2018-06-21 at 11 52 25 am" src="https://user-images.githubusercontent.com/198507/41739387-c1504d0c-7549-11e8-9fa7-5f6b5c54b938.png">

**Comment by jgmize** [comment]
Replicated this issue, I see the tracebacks here: https://rpm.newrelic.com/accounts/1299394/applications/41872252/filterable_errors#/show/0e1042da-7585-11e8-aca1-0242ac110007_3306_7565/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart

**Comment by jgmize** [comment]
Tracebacks from sentry:

```
KeyError: u'text'
(17 additional frame(s) were not displayed)
...
  File "advanced_filters/admin.py", line 113, in changelist_view
    ).changelist_view(request, extra_context=extra_context)
  File "reversion/admin.py", line 254, in changelist_view
    return super(VersionAdmin, self).changelist_view(request, context)
  File "snippets/base/admin.py", line 100, in changelist_view
    return super(DefaultFilterMixIn, self).changelist_view(request, *args, **kwargs)
  File "snippets/base/forms.py", line 172, in __init__
    text = instance.dict_data[self.body_variable]
```

**Comment by jgmize** [comment]
This appears to be a separate issue from #542

**Comment by jgmize** [comment]
Filed https://github.com/mozmeao/snippets-service/pull/573 which should fix the issue

**Comment by glogiotatidis** [comment]
It's fine now. Thanks for reporting @bensternthal
