### ISSUE TITLE
[Activity Stream] EOY 2017 Snippet Template Button Text Color CSS conflict

### ISSUE THREAD

**Issue by mediaChick** [mozmeao/snippets-service#581]
Issue reported today by Mac users that the button text displayed on snippets using the EOY 2017 Snippet Template look like this:
![screen shot 2018-06-28 at 11 29 16 am](https://user-images.githubusercontent.com/39389621/42055217-5132a7ea-7acb-11e8-9f40-0eb6b1c336fc.png)

On PCs it looks like this:
![image](https://user-images.githubusercontent.com/39389621/42055252-6cd78aec-7acb-11e8-8362-505201ee7173.png)

The default color for buttons (button_color) should be white (#000000) but displays black (#FFFFFF) on PCs and a bright blue on Macs. Changing the color hex code in the button_color doesn't change the text on the button. 

Please fix the CSS in the EOY 2017 Snippet Template and check the CSS in the other templates for the same issue.

**Comment by pmac** [comment]
Working on this now.

**Comment by pmac** [comment]
Appling @craigcook's suggested fix of changing the CSS rule for the button text color to `#snippets-container .snippet .donation-form-url`.

**Comment by pmac** [comment]
Seems to have worked! Changes are rolling out now. Please reopen if this hasn't fixed the issue for all platforms.

**Comment by ldwright** [comment]
Looks good now - this appears to be resolved. Thanks all!
<img width="763" alt="screen shot 2018-06-28 at 12 17 15 pm" src="https://user-images.githubusercontent.com/32490072/42056099-14028d6a-7ace-11e8-867c-2e81c3abd042.png">
