### ISSUE TITLE
[Activity Stream] Simple snippets with Button Template Has a Button Text Color CSS conflict

### ISSUE THREAD

**Issue by mediaChick** [mozmeao/snippets-service#625]
Identical to [Issue 581](https://github.com/mozmeao/snippets-service/issues/581), the default text color for buttons displays as bright blue and changing the color hex code doesn't change the color. (See #581 for screenshots.)

Issue #581 was fixed by changing the CSS rule in the button text color to #snippets-container .snippet .donation-form-url. Will that also work for this issue?

If yes, please make that change and also make the change to all the [Activity Stream] templates so I can use the button. @glogiotatidis

**Comment by glogiotatidis** [comment]
Fixed all templates in https://github.com/mozmeao/snippets/commit/d8b5eaf80d3b6bf8328c4812e2413edf70660b36

```
activity-stream/fxa.html                  | 2 +-
activity-stream/newsletter-subscribe.html | 2 +-
activity-stream/send-to-device.html       | 2 +-
activity-stream/simple-snippet.html       | 2 +-
activity-stream/simple-video-snippet.html | 2 +-
```

EOY 2017 was already fixed in https://github.com/mozmeao/snippets/commit/dc81f2e71a4ee7e79923bad4c628ae650aa18418

**Comment by glogiotatidis** [comment]
@mediaChick you might want to keep in mind that Activity Stream adapts to Firefox themes. Changing the button color may not appear nicely on all themes. Default button values on the other hand adapt.
