### ISSUE TITLE
Snippets not displaying as expected for all after the A/S Router implimentation

### ISSUE THREAD

**Issue by mediaChick** [mozmeao/snippets-service#629]
The five (5) hard-coded AS Router snippets in the Snippets NG base are not displaying as expected for me, but they are for @glogiotatidis. Clearing my browser cache didn't fix this issue.

**Fx GA 61.0.1**
Clicking "Preview URL" in the snippet admin or on the magnifying glass icon in Snippets NG base displays snippets that look like this:
![snippetng-release channel- snippet view](https://user-images.githubusercontent.com/39389621/43339510-5b843a18-918e-11e8-86fd-c01e75d6a69d.png)

**Fx Beta 62.0b12**
Clicking "Preview URL" in the snippet admin or on the magnifying glass icon in Snippets NG base displays snippets that look like this:
![snippet ng-beta channel-snippet view](https://user-images.githubusercontent.com/39389621/43339706-f741c25e-918e-11e8-84f2-98f367e2f9b5.png)

**Clicking the "Preview snippet" button in the snippet admin displays correctly.**

**Comment by glogiotatidis** [comment]
Thanks for reporting @mediaChick 

@ldwright do you have the same issue?

**Comment by glogiotatidis** [comment]
Thanks for this more detailed bug report @mediaChick. Your `Clicking "Preview URL" ` comment made it possible to identify the issue. I's using the preview button under the template fields which was working fine.

**Comment by mediaChick** [comment]
@glogiotatidis @ldwright The views all look great for me on both GA and Beta now. Yay!
