### ISSUE TITLE
Block snippets after default action taken.

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#638]
Snippets should not appear again (i.e. get added to block list) after default action has been taken (i.e. user clicked `donate` on a fundraising snippet).

Change all AS template to default to this action.

**Comment by glogiotatidis** [comment]
See [bug 1482859](https://bugzilla.mozilla.org/show_bug.cgi?id=1482859) for ASR Templates

**Comment by glogiotatidis** [comment]
@ldwright is it OK to skip implementing this for the current system and only target fixing it for ASR templates what we will use in Fx63?

**Comment by ldwright** [comment]
Hi @glogiotatidis - chatted with Michele W. about this and if we can at least implement it for our current Fundraising/EOY template that would be ideal. We'll be starting a more frequent push of donation campaigns in November and want to make sure we're being conscious of our users' experience with those snippets specifically. (i.e. If they donate, we don't want to keep asking them.) - The other templates can wait/be implemented with ASR templates.

**Comment by glogiotatidis** [comment]
OK filed issue #755. Please confirm that this is what you need

**Comment by glogiotatidis** [comment]
Moving to Fx64 Milestone since we didn't get the templates in for Fx63

**Comment by glogiotatidis** [comment]
According to [bug 1482859#c10](https://bugzilla.mozilla.org/show_bug.cgi?id=1482859#c10) this has been fixed for all ASR templates for Fx64

**Comment by glogiotatidis** [comment]
Assigning this to self to review ASR templates

**Comment by glogiotatidis** [comment]
Reviewed and everything is working fine
