### ISSUE TITLE
AS Snippets and AS Router Attribute Targeting Check List

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#650]
Current System              | AS Router        | OK
-----------------------------|------------------|---------
 Publish Start               | Server Side (*)   and https://github.com/mozmeao/snippets-service/issues/667 | :ok_hand: 
 Publish End                 | Server Side (*)   and https://github.com/mozmeao/snippets-service/issues/667 |:ok_hand: 
 Prevalence (weight)         |      https://bugzilla.mozilla.org/show_bug.cgi?id=1484996        and https://github.com/mozmeao/snippets-service/issues/666     |:ok_hand: 
 Product Channels            | Server Side       |:ok_hand: 
 Firefox Version             |  https://bugzilla.mozilla.org/show_bug.cgi?id=1484207              and https://github.com/mozmeao/snippets-service/issues/665   | :ok_hand: 
 Firefox Account             | hasFxAccount  (See also https://bugzilla.mozilla.org/show_bug.cgi?id=1484698)    and https://github.com/mozmeao/snippets-service/issues/668 |:ok_hand: 
 Is Developer                |  devToolsOpenedCount                 and https://github.com/mozmeao/snippets-service/issues/669 |:ok_hand: 
 Default Browser             | isDefaultBrowser  and https://github.com/mozmeao/snippets-service/issues/670 |:ok_hand: 
 Screen Size                 |      https://bugzilla.mozilla.org/show_bug.cgi?id=1484205             and https://github.com/mozmeao/snippets-service/issues/671 - *will not implement* | :ok_hand: 
 Previous session closed     |              https://bugzilla.mozilla.org/show_bug.cgi?id=1484206     and https://github.com/mozmeao/snippets-service/issues/672 |:ok_hand: 
 Profile Age                 | profileAgeCreated and https://github.com/mozmeao/snippets-service/issues/673 | :ok_hand: 
 Add-on Info                 | addonsInfo and https://github.com/mozmeao/snippets-service/issues/674  |:ok_hand: 
 Bookmarks Count             |   https://bugzilla.mozilla.org/show_bug.cgi?id=1483977  and https://github.com/mozmeao/snippets-service/issues/675              |:ok_hand: 
 Country                     |   https://bugzilla.mozilla.org/show_bug.cgi?id=1484207 and https://github.com/mozmeao/snippets-service/issues/676              |:ok_hand: 
 Locale                      | Server Side       |:ok_hand: 
 Search Engines              | searchEngines     and https://github.com/mozmeao/snippets-service/issues/676 |:ok_hand: 
 Client Match Rules          | Server Side       |:ok_hand: 

Useful Links:
 - [AS Router Documentation]( https://github.com/mozilla/activity-stream/blob/master/content-src/asrouter/schemas/message-format.md#targeting-attributes)
 - [AS Snippets Implementation](https://github.com/mozmeao/snippets-service/blob/master/snippets/base/templates/base/includes/snippet_as.js)

**Comment by k88hudson** [comment]
Just had a couple of questions here:

- weight: We had previously discussed that weight wouldn’t be needed since we have frequency capping, is that still the case?
- Fx Version: I thought this is a server side filter?Isn’t this just %VERSION%? If not easy to add
- Screen size: I don’t recognize this one, what’s needed/currently implemented here?
- Previous session closed: Also don’t recognize this one
- Bookmarks count: filed https://bugzilla.mozilla.org/show_bug.cgi?id=1483977 
- Country: I thought this is also a server side filter? If not easy to add

**Comment by glogiotatidis** [comment]
> Just had a couple of questions here:
> 
>     weight: We had previously discussed that weight wouldn’t be needed since we have frequency capping, is that still the case?

First time I hear this. Maybe @ldwright knows more?


>     Fx Version: I thought this is a server side filter?Isn’t this just %VERSION%? If not easy to add
Yes it's in the URL but we typically filter on the client side 
https://github.com/mozmeao/snippets-service/blob/master/snippets/base/templates/base/includes/snippet_as.js#L232

>     Screen size: I don’t recognize this one, what’s needed/currently implemented here?
We can target based on Screen size. 
https://github.com/mozmeao/snippets-service/blob/master/snippets/base/templates/base/includes/snippet_as.js#L265

>     Previous session closed: Also don’t recognize this one
That's `appData.previousSessionEnd` you built in the current implementation

https://github.com/mozmeao/snippets-service/blob/master/snippets/base/templates/base/includes/snippet_as.js#L283

>     Bookmarks count: filed https://bugzilla.mozilla.org/show_bug.cgi?id=1483977
Thanks!

>     Country: I thought this is also a server side filter? If not easy to add

No it's not server side. We 're pinging MLS to get user country https://github.com/mozmeao/snippets-service/blob/master/snippets/base/templates/base/includes/snippet_as.js#L475

**Comment by glogiotatidis** [comment]
@k88hudson in https://github.com/mozilla/activity-stream/blob/master/content-src/asrouter/schemas/message-format.md you list `hasFxAccount` in example but you don't list in the table. 

Can you please confirm that this is implemented?

Also since this is actually reflecting if user is using Firefox Sync (and not if they have a Fx Account, which they may have but not use to Sync) can we rename it to `usesFirefoxSync`?

**Comment by glogiotatidis** [comment]
> @k88hudson in https://github.com/mozilla/activity-stream/blob/master/content-src/asrouter/schemas/message-format.md you list hasFxAccount in example but you don't list in the table.
> 
> Can you please confirm that this is implemented?

nvm that part, i's looking at the wrong docs. The rename question still stands

**Comment by k88hudson** [comment]
@glogiotatidis filed https://bugzilla.mozilla.org/show_bug.cgi?id=1484698

**Comment by ldwright** [comment]
@glogiotatidis @k88hudson - Just chatted with Michele Warther on this... We use prevalence (weight) as a mechanism for setting priorities when multiple snippets are running, so frequency capping wouldn't be a replacement for that in our mind, it would just be a subsequent capability - it would be nice to have both. Is that possible?

**Comment by k88hudson** [comment]
Thanks @ldwright, filed https://bugzilla.mozilla.org/show_bug.cgi?id=1484996

**Comment by glogiotatidis** [comment]
In current AS implementation we have `profileCreatedWeeksAgo` which we can use to target users that have a profile in the first week, second week and so on.

In ASR, `profileAgeCreated` is a timestamp of when the profile was created. Is there a JEXL way to do the math to check in which week the user is? Something between the lines of

`(Date.now() - profileAgeCreated) / 604800`

@k88hudson @piatra can you please advise?

**Comment by piatra** [comment]
That looks correct to me except it should be `(604800 * 1000)`

**Comment by glogiotatidis** [comment]
thanks for the advise

> Update: we're missing a way to get the current timestamp, I will be adding that as part of filtering snippets by date.

got a bug for that?

**Comment by piatra** [comment]
@glogiotatidis https://bugzilla.mozilla.org/show_bug.cgi?id=1485345

**Comment by glogiotatidis** [comment]
ASR now has targeting parity with current snippets system.
