### ISSUE TITLE
Re-word Firefox Account targeting parameter

### ISSUE THREAD

**Issue by ldwright** [mozmeao/snippets-service#656]
We recently learned that the pref for "show only to users with an enabled Firefox Account" actually looks at whether or not someone has Sync enabled (which therefore _tells us_ that someone has a Firefox Account) - now that we know this, it'd be nice to rephrase that targeting parameter to be more accurate in the admin tool.

Proposal to change field values to:
"Show only to FxA users with Sync enabled"
"Show only to users without Sync enabled"

And to clarify: @glogiotatidis Can you confirm that if we choose "Show only to users without Sync enabled" in this case, that we would theoretically be targeting people without a Fx Account _as well as_ people with a Fx Account but do not have Sync enabled? There's no way to tease those two buckets apart at this point, right?

Thanks!
CC for FYI: @mediaChick

**Comment by glogiotatidis** [comment]
> And to clarify: @glogiotatidis Can you confirm that if we choose "Show only to users without Sync enabled" in this case, that we would theoretically be targeting people without a Fx Account as well as people with a Fx Account but do not have Sync enabled? There's no way to tease those two buckets apart at this point, right?

That's correct.
