### ISSUE TITLE
Migrate F100 Snippets from AS to ASR

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#678]
This issue tracks the work need to be done to migrate F100 Snippets from AS to ASR while preserving all targeting options.

See also #688: `Create migration script of current AS Snippets to ASR Snippets seedling ASR`

Snippets that need attention in #860 

Channels
 - [x] Nightly
 - [x] Dev
 - [x] Beta
 - [x] Release

Snippets to migrate:
 - Modified in the last 6 months
 - Currently Published
 - All F100

Plan:
 - Set `DATA_UPLOAD_MAX_NUMBER_FIELDS` env variable to `10000`
 - From the Admin -> Snippet listing page
 - Filter by "Activity Stream" and "Not migrated" Snippets
 - Start migrating in batches of 100 snippets. Some snippets will need special attention
 - Unset `DATA_UPLOAD_MAX_NUMBER_FIELDS` env variable

**Comment by glogiotatidis** [comment]
@ldwright do we want to migrate only F100 Snippets? Or all `published` snippets at the time of the switch?

**Comment by ldwright** [comment]
Yes, any published snippets at the time should migrate over, including F100.

Questions:

- What happens to snippets that we want to migrate but aren’t published at the time of the switch? (We ask because we often copy and/or re-run snippets - so would we need to recreate those, or could we have access to them as well? and/or identify the ones we would want brought over for you?)

- We're in the midst of localizing the F100 journey in multiple other languages (programming is currently underway, and we hope to have them published by the end of this month or so) - when will this migration work on your end be happening?

**Comment by glogiotatidis** [comment]
>     * What happens to snippets that we want to migrate but aren’t published at the time of the switch? (We ask because we often copy and/or re-run snippets - so would we need to recreate those, or could we have access to them as well? and/or identify the ones we would want brought over for you?)

We can select for migration all published snippets *and* unpublished snippets modified in the last 60 days from the point of migration. What do you think @ldwright ?

**Comment by glogiotatidis** [comment]
>     * We're in the midst of localizing the F100 journey in multiple other languages (programming is currently underway, and we hope to have them published by the end of this month or so) - when will this migration work on your end be happening?

I plan the migration to happen very close to the date we switch to the new system. The exact datetime is yet to be determined. We will discuss and plan together when we approach that day to limit the duplicate work to a minimum.

**Comment by glogiotatidis** [comment]
Moving this to Fx64 Milestone since ASR will hit release channel with 64

**Comment by glogiotatidis** [comment]
# Migration of Beta, Dev and Nightly Snippets Report

Migration of Beta, Dev and Nightly snippets to ASR Snippets has been completed. Everything runs smoothly.

A few ASRSnippets require special attention to manually correct content. One of the listed snippets was in published state, so we can fixed when/if we device to publish. 


       9476 - MOCO_Global_2018_P100_Deep Link Test_About Preferences General_SS_EN_NIGHTLY -- preferences wrong link
       9477 - MOCO_Global_2018_P100_Deep Link Test_About Preferences Privacy_SS_EN_NIGHTLY -- preferences wrong link
       9672 - VPN Mockup - LW -- invalid link, missing `https://`
       8517 - MOCO_global_2018_campaign_IRL S3E1 July V2_activity_stream_EN_PRE -- invalid link, missing `"`
       9629 - MOCO_global_2018_P100_Email_Fx Nov More Fox_Email_EN_PRE -- invalid link, space between `href=` and `"`
       9630 - MOCO_global_2018_P100_Email_Fx Nov Zero Inbox_Email_EN_PRE -- invalid link, space between `href=` and `"`
       9813 - MOCO_Global_2018_P100_Email_Moz Labs Intro - Curious_Email_EN_PRE -- invalid link, space between `href=` and `"`
       9814 - MOCO_Global_2018_P100_Email_Moz Labs Intro - Knowledge_Email_EN_REL_PRE -- invalid link, space between `href=` and `"`

**Comment by jkt230** [comment]
Thanks for flagging.

What is the correct link for 9476 and 9477?

Not worried about the rest as they are either a mock up/test, been fixed.

**Comment by glogiotatidis** [comment]
## Migration of Release Snippets Report

First step of migration of Release snippets to ASR Snippets has been completed. 

We migrated:
 - All Published Snippets
 - All Snippets modified in the last 60 days
 - All Snippets with `f100` in their name

for the Release channel.

A few ASRSnippets required special attention to manually correct content. I proceeded with fixing those snippets. A full list of snippets with their fixed issues follows:


### Snippets that require manual edits
```
7869 - extra space in link
7871 - extra space in link
8904 - extra space in link
8906 - extra space in link
9000 - extra space in link
9001 - extra space in link
9282 - extra space in link
9329 - extra space in link
9334 - extra space in link
9266 - extra space in link
9345 - extra space in link
9346 - extra space in link
9128 - extra space in link
9129 - extra space in link
9248 - extra space in link
9246 - extra space in link
7913 - had to replace `>` with `&rarr;`
7916 - extra space in link
7920 - extra space in link
7897 - extra space in link
7868 - extra space in link
7870 - extra space in link
7894 - extra space in link
9147 - had to replace `>` with `&rarr;`
9171 - extra space in link
8871 - extra space in link
8928 - had to replace `>` with `&rarr;`
8936 - extra space in link
8939 - extra space in link
8658 - extra space in link
8828 - extra space in link
8831 - extra space in link
8763 - had to replace `>` with `&rarr;`
8753 - extra space in link
8750 - extra space in link
8725 - extra space in link
8724 - extra space in link
8641 - extra space in link
8699 - extra space in link
8700 - extra space in link
8792 - extra space in link
8795 - extra space in link
8816 - extra space in link
8817 - extra space in link
8964 - had to replace `>` with `&rarr;`
7895 - extra space in link
7896 - extra space in link
9672 - missing https://
9243 - had to replace `>` with `&rarr;`
9263 - extra space in link
9162 - had to replace `>` with `&rarr;`
9177 - extra space in link
9186 - extra space in link
9627 - extra space in link + removed target="_blank"
9611 - removed target="_blank"
9612 - removed target="_blank"
9613 - removed target="_blank"
9614 - removed target="_blank"
9615 - removed target="_blank"
9616 - removed target="_blank"
9605 - removed target="_blank"
9606 - removed target="_blank"
9607 - removed target="_blank"
9608 - removed target="_blank"
9609 - removed target="_blank"
9610 - removed target="_blank"
9617 - removed target="_blank"
9618 - removed target="_blank"
9619 - removed target="_blank"
9620 - removed target="_blank"
9621 - removed target="_blank"
9622 - removed target="_blank"
9631 - removed target="_blank"
9632 - removed target="_blank"
9633 - removed target="_blank"
9634 - removed target="_blank"
9635 - removed target="_blank"
9636 - removed target="_blank"
9637 - removed target="_blank"
9638 - removed target="_blank"
9639 - removed target="_blank"
9640 - removed target="_blank"
9641 - removed target="_blank"
9642 - removed target="_blank"
8908 - wrong link
9628 - removed target="_blank"
9455 - removed target="_blank"
9655 - removed target="_blank"
8583 - missing `"` in links
9459 - At least version 57 targeting - Removed that since ASR is at least 57 anyway
9484 - at least version 62 targeting - Removed that since ASR is at least 62 anyway
```

## List of snippets that failed to migrate
```
9396 - Is using the Send to Device Card Template which does not exist in ASR
```

## Next Steps

We proceeded with migrating Release snippets this weeks to allow time to the QA team to test Firefox 64 with real content before we flip the pref and enable ASR Snippets for all. (see bug [1514169](https://bugzilla.mozilla.org/show_bug.cgi?id=1514169))

The pref flip date is currently set on **Monday January 7th 2019**.

Before making the pref flip, we fill identify which snippets have been edited between Dec 13th and Jan 7th and we'll re-migrate those to get the latest content on ASR. Snippet editors do *not* need to do double duty and update both ASR and non-ASR for this period. Everything will be migrated auto-magically.

**Comment by glogiotatidis** [comment]
# Final Migration Report

Just completed migration of the Snippets that were 
 - Already migrated on Dec 14th but they got modified between then and now. These were snippets 8964, 8792, 8816, 9814, 9813, 9812, 9811`
 - Created between then and now not including the following snippets which have been manually created both as Snippet and ASRSnippets: 9896, 9895, 9898, 9897, 9894, 9893, 9892, 9889, 9890, 9891

All systems operational, we are ready to start the pref flip on Release.

# Next Steps
AS team will handle the pref flip on Release starting today, Jan 7th, and gradually increasing to 100% by Jan 17th.

Between now and Jan 17th Snippets must get updated / created on as Snippets and ASRSnippets.
