### ISSUE TITLE
Tracker: ASR Templates

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#680]
This issue tracks the Templates available for ASR

 - [x] Simple Snippet
 - [x] Send to Device
 - [x] Newsletter Subscribe

 - [x] FxA sign up 
 - [x] Fundraising templates
 - ~~Video~~ Video Template is not required for Fx64. Filed #835 to track it's development for future versions.

Also related bugs
 - [Add title to snippets block button in AS Router](https://bugzilla.mozilla.org/show_bug.cgi?id=1477633) FIXED
 - [Update Simple Snippet Template to block snippet after user action.](https://bugzilla.mozilla.org/show_bug.cgi?id=1482859) FIXED

**Comment by glogiotatidis** [comment]
Newsletter template https://github.com/mozilla/activity-stream/pull/4438

**Comment by glogiotatidis** [comment]
Moving to Fx64 milestone since we didn't get templates in for 63

**Comment by glogiotatidis** [comment]
Filed QA Issues:
 - https://github.com/mozmeao/snippets-service/issues/830
 - https://github.com/mozmeao/snippets-service/issues/831
 - https://github.com/mozmeao/snippets-service/issues/832
 - https://github.com/mozmeao/snippets-service/issues/833
 - https://github.com/mozmeao/snippets-service/issues/834

**Comment by jkt230** [comment]
Let me know what else is needed here!

**Comment by glogiotatidis** [comment]
I believe we're good. Thanks!
