### ISSUE TITLE
Snippet display issues when using built-in dark theme

### ISSUE THREAD

**Issue by jpetto** [mozmeao/snippets-service#682]
During review of mozmeao/snippets#148, @alexgibson noticed that the snippet content is really difficult to read/see when using the new built-in dark theme.

We should audit existing snippets against this theme to figure out impact and solution(s).

**Comment by glogiotatidis** [comment]
We're building a way to preview snippets in the dark theme #942 and also the option use different images for dark themed browsers #930 

The LCM team is aware of the issue so content is created with the two themes in mind.

I'll close this one now and track the dark image / preview work in the issue mentioned.

Thanks for reporting @jpetto !
