### ISSUE TITLE
Add SMS capabilities to new Send to Device Card snippet template

### ISSUE THREAD

**Issue by jpetto** [mozmeao/snippets-service#683]
As an extension to the snippet added/referenced in #661, we need to implement SMS capabilities. This should essentially be a copy/paste from the pre-existing Send to Device snippet template.

**Comment by mediaChick** [comment]
You're right, @glogiotatidis. This template is experimental and will be de-commissioned as of the Activity Stream Router platform launch. 

@jpetto, let's close this issue.
