### ISSUE TITLE
Please decom snippets-stats new relic monitor

### ISSUE THREAD

**Issue by cvalaas** [mozmeao/snippets-service#685]
@bensternthal got an alert re snippets-stats:

> howdy.. got a new relic alert via email “Snippets Stats Server (WebOps Managed) failed” about 30 minutes ago.. just want to verify webops also got the alert and is on it

snippets-stats was just moved over to haul running on Nubis, so the New Relic monitor in question is no longer useful. Please remove, thanks!

**Comment by metadave** [comment]
Synthetics monitor has been disabled.

**Comment by glogiotatidis** [comment]
I changed the url to https://snippets-stats.mozilla.org/foo.html (the real URL used to collect stats) and re-enabled the monitor to keep this under my radar until we complete the migration to Ping Center.

Thanks!
