### ISSUE TITLE
[new filter] Filter based on number of devices synced

### ISSUE THREAD

**Issue by ldwright** [mozmeao/snippets-service#694]
Associated with [Bug 1483046](https://bugzilla.mozilla.org/show_bug.cgi?id=1483046).

Background on request: We would like to be able to target snippet users based on the number of devices they have synced, since a significant number of people have Sync enabled, but only one device connected - which does not provide any value. This is important so we can encourage people with only one device to download/use Sync with another device.

**Comment by glogiotatidis** [comment]
`ASRouterTargeting.Environment.sync`

**Comment by glogiotatidis** [comment]
`desktopDevices: 1
​
mobileDevices: 0
​
totalDevices: 2`

**Comment by glogiotatidis** [comment]
Fixed in https://github.com/mozmeao/snippets-service/commit/32504b34f1c956c26b95d44c1c84565285dec74a
