### ISSUE TITLE
[new filter] Filter based on type of devices synced

### ISSUE THREAD

**Issue by ldwright** [mozmeao/snippets-service#695]
Associated with [Bug 1483050](https://bugzilla.mozilla.org/show_bug.cgi?id=1483050).

Background on request: Once we're able to target users based on their number of devices synced, we'd also like to be able to target snippet users based on the type of devices they have synced - i.e. two desktop devices, but no mobile devices - so we can cross-sell mobile, for instance.

**Comment by glogiotatidis** [comment]
This lives under `ASRouterTargeting.Environment.sync`

​```javascript
{
desktopDevices: 1
mobileDevices: 0
totalDevices: 2
}```

**Comment by glogiotatidis** [comment]
@jkt230 do these options for number of synced devices make sense?
![image](https://user-images.githubusercontent.com/584352/57456872-16c20700-7277-11e9-8b2e-3c8ebd223551.png)

**Comment by jkt230** [comment]
Is there a way to promote a snippet for users to download a Firefox mobile app but NOT to those who are Synced on at least 1 mobile device? [We are assuming that those who are synced via a mobile device that they already have the Firefox mobile app].

**Comment by glogiotatidis** [comment]
> Is there a way to promote a snippet for users to download a Firefox mobile app but NOT to those who are Synced on at least 1 mobile device? [We are assuming that those who are synced via a mobile device that they already have the Firefox mobile app].

Yes you would choose 

`Mobile Synced devices: From and included "No Limit" up to (excluded) "1"`

If you want to additionaly limit to users who are already syncing, set "Uses Firefox Sync" to "Yes"

**Comment by glogiotatidis** [comment]
We discussed this during our mtg and it's good to go. @mozmeao/omn-team please ping me if you need a second look at the target you build.

Thanks!
