### ISSUE TITLE
[new filter] Filter based on y/n updates enabled

### ISSUE THREAD

**Issue by ldwright** [mozmeao/snippets-service#696]
Associated with [Bug 1483056](https://bugzilla.mozilla.org/show_bug.cgi?id=1483056).

Background on this request: We'd like to be able to target snippet users based on whether or not they have updates enabled. This may help us begin to ascertain a user's level of tech savviness and usage habits. Could possibly be measured against retention and/or (if value = no) be used for upgrade campaigns.

**Comment by glogiotatidis** [comment]
This lives under `browserSettings.update.autoDownload`
