### ISSUE TITLE
[new filter] Filter based on y/n auto-download updates enabled

### ISSUE THREAD

**Issue by ldwright** [mozmeao/snippets-service#697]
Associated with [Bug 1483057](https://bugzilla.mozilla.org/show_bug.cgi?id=1483057).

Background on request: We'd like to be able to target snippet users based on whether or not they have updates enabled to auto-download or not. Similar to #696 this may be able to help us ascertain a user's level of tech savviness and usage habits, and could possibly be measured against retention.

**Comment by glogiotatidis** [comment]
This lives under `browserSettings.update.autoDownload`
