### ISSUE TITLE
Select priority countries in admin

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#731]

**Comment by glogiotatidis** [comment]
Set the following countries as priority, i.e. they are listed first in the country dropdown.

 'AT', 'BR', 'CA', 'CH', 'DE', 'ES', 'FR', 'GB', 'ID', 'IE', 'IN', 'MX', 'NL', 'PH', 'PL', 'TH', 'US'

Made this change in production. 

![image](https://user-images.githubusercontent.com/584352/46476410-c2dad580-c7f0-11e8-97e1-d8a42be76c78.png)


@mediaChick @ldwright sounds good?

**Comment by mediaChick** [comment]
@ldwright @glogiotatidis I don't know the context for the countries chosen as "priority" but I do know that snippet locale priorities are:

EN, DE, ES, pt-BR, RU, zh-TW, PL and ID. Of the countries listed first in the dropdown, RU and China aren't there. Should they be?

**Comment by glogiotatidis** [comment]
Nothing to do with priority markets. This is for your convenience, so you get frequently used countries listed first. I created the list based on the countries we have targeted in the past.

**Comment by glogiotatidis** [comment]
So the question is: 

 - We have the said countries listed first in the dropdown down. Does this make your life easier @mediaChick? Do you want countries added to priority list or removed from it?

**Comment by mediaChick** [comment]
@glogiotatidis Priority countries are the countries I target the most, so yes, it would make life easier if EN, DE, FR, ES, pt-BR, RU, zh-TW, PL and ID were at the top, and beneath that CA, CH, AT, UK. Thank you!

**Comment by glogiotatidis** [comment]
@mediaChick you're listing locales, while this is about countries. I fixed locales for you and also selected corresponding countries.

I'm going to close this one now. We can always update the list of priority countries & locales as the targeting patterns change, just file an issue with the request.

Thanks!

Thanks!
