### ISSUE TITLE
Add help text with deep links and `[[snippet_id]]` in ASRSnippet

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#745]
![image](https://user-images.githubusercontent.com/584352/46720224-9c95b980-cc78-11e8-9abf-14352a1657e2.png)

**Comment by glogiotatidis** [comment]
@mediaChick @ldwright added more help text in `ASRSnippets` explaining deep links and the `[[snippet_id]]` trick. The `[[snippet_id]]` trick works also for current `Snippets`

**Comment by mediaChick** [comment]
@glogiotatidis The [[snippet_id]] trick is used here?
![image](https://user-images.githubusercontent.com/39389621/46756822-35c6cf00-cc7d-11e8-8e06-3b4ec80390e6.png)

**Comment by glogiotatidis** [comment]
I don't understand how that could be used there?

This is for text you input in Template Fields and you can see the result in preview.

**Comment by mediaChick** [comment]
Sorry, I thought [[snippet_id] was for searching for a snippet using their ID and I replied before your screenshot was added. 

How are deep links and using [[snippet_id]] related? It's not clear to me what [[snippet_id]] is a "trick" for?

**Comment by mediaChick** [comment]
I saw that, but we already put the snippet ID in the utm parameters. Is there a reason why I'd want to use [[snippet_id]] versus using the actual ID in the tracking link?

**Comment by glogiotatidis** [comment]
It's just a convenience, so you don't have to scroll up and down and copy paste the ID. Also in case you're using the same link in multiple snippets you don't have to update the link with the ID of each snippet.

You don't have to use it, I just brought it up (it has been there forever) b/c you mentioned that's difficult to get the Snippet ID into the links.

**Comment by mediaChick** [comment]
Got it! Thanks. 

I mentioned the snippet ID and links because in the edit field the only place you see the ID is in the address bar link (no need to scroll to see it). To have the ID also displayed on the edit page is on my Wish List -- I'll be filing issues next sprint.
