### ISSUE TITLE
Create a button to copy to clipboard the preview link on click

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#748]
Preview link for ASR Snippets cannot be directly clicked and instead must be copied and pasted to the URL bar. Create a `Copy` button next to the link to make the procedure easier.

**Comment by mediaChick** [comment]
Is it possible for that copy button to open that copied url in new:tab?

**Comment by glogiotatidis** [comment]
> Is it possible for that copy button to open that copied url in new:tab?

Unfortunately you'll have to copy and paste as I mentioned in the meeting. This issue is so that copying is easier.
