### ISSUE TITLE
Integrate Slack to post updates when Snippet changes

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#751]
Post updates when Snippet changes
 - Becomes ready for review. See #648 
 - Gets published

![image](https://user-images.githubusercontent.com/584352/47205804-a366af80-d38f-11e8-921f-536bf1b96b7c.png)

**Comment by jkt230** [comment]
Thank you! Please send these pings to #snippetsadmin on Slack.

**Comment by glogiotatidis** [comment]
* Created `#snippets-admin`
* Invited LCM team
* Setup bot to send notifications there.

:dancing_men:
