### ISSUE TITLE
Automatically add utm params to Snippet links

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#752]

**Comment by hoosteeno** [comment]
This document has logic to autogenerate links using inputs for 5 utm fields (utm_source, utm_medium, utm_campaign, utm_content, utm_term): https://docs.google.com/spreadsheets/d/1VzSbNN7nt4tKuTAW0EwP1YMOJsItjuyATeECnwNP76Q/edit#gid=0. 

For snippets, most of those fields are always the same -- this document explains what should go in them: https://docs.google.com/presentation/d/1yP-nT70DCTv4VtEOrd5fnVNee3aYZmVl2cnxVWPGgUw/edit#slide=id.g3e5601f53f_0_7

Looks like the current scheme uses algorithms to determine every field except campaign.
