### ISSUE TITLE
[Fundraising Template] Block Snippet after user clicks donate button

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#755]
The snippet or any snippet in the campaign must not re-appear after user clicks `Donate`

- [x] Update production

**Comment by ldwright** [comment]
@glogiotatidis Correct - once a users clicks "Donate Now" on the Fundraising template, we will assume they have actually followed through with donating on the donate.mozilla.org page that it drives them to, and therefore we shouldn't bug them again with the same message or any other message with the same campaign name.

CC: @mediaChick for FYI.

**Comment by glogiotatidis** [comment]
This has been fix in production

/cc @mozmeao/lcm-team @jkt230 @mediaChick
