### ISSUE TITLE
Automatically localize block button text for ASR Templates

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#757]
The ASR Templates still rely on snippets-service to provide a localized version of the `Remove this` block button text. 

We can however hard-code the values into code and automatically select one because on the Snippet locale to reduce the burden of having to repeatedly input the same value when creating a Snippet.

**Comment by mediaChick** [comment]
"Remove this"

DE - Entfernen
FR - Supprimer
RU - Удалить
ES - Quitar esto
pt-BR - Remover este item
PL - Usuń to
zh-TW - 移除這個
ID - Hilangkan ini
IT- Nascondi questo messaggio
CS - Odstranit
NL - Verwijder dit
zh-CH - 删除它

**Comment by glogiotatidis** [comment]
This is not blocking Fx64 release, removing from milestone

**Comment by glogiotatidis** [comment]
The functionality has been delivered and block button has been localized. We're able to localize other fields of the templates as needed (like Dismiss Button, Messages from Firefox header). Snippets team has been made aware of the functionality and update with new translations for strings as needed.
