### ISSUE TITLE
Fix CSRF timeout

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#767]
When clicking to save a Snippet sometimes a CSRF exception is returned. This happens in production.

We have session CSRF ([code](https://github.com/mozmeao/snippets-service/blob/master/snippets/settings.py#L208))

and we use Redis to store our sessions

**Comment by glogiotatidis** [comment]
@mozmeao/backend any ideas why this might be happening. I haven't found a way to reproduce this consistently.

**Comment by glogiotatidis** [comment]
> Is this happening to people using the admin, or are you only seeing this in Sentry?

This is not raising a Sentry error, i"ve seen it when trying to save in admin

**Comment by glogiotatidis** [comment]
@metadave @jgmize do you have any ideas?

**Comment by pmac** [comment]
sessions timing out? for how long is the session valid?

**Comment by jgmize** [comment]
I think we should consider switching `CSRF_USE_SESSIONS` to the default of `False` and explicitly set `CSRF_COOKIE_SECURE` to `True`.

**Comment by jgmize** [comment]
We can also leverage the support for same-site cookies that landed in [Django 2.1.2](https://code.djangoproject.com/ticket/27863) and [Firefox 60](https://blog.mozilla.org/security/2018/04/24/same-site-cookies-in-firefox-60/)

**Comment by jgmize** [comment]
Filed https://github.com/mozmeao/snippets-service/pull/784 with the changes I described above.

**Comment by glogiotatidis** [comment]
Pushed change to production and pinged LCM team to keep an eye for new errors. Will close in two weeks time if no new errors.

Thanks for your help @mozmeao/theconn :metal: 

/remind me to re-eval the situation in two weeks

**Comment by glogiotatidis** [comment]
While using Production Admin, configured to use CSRF cookies, I got the error again.

Any ideas @mozmeao/theconn ?

**Comment by jgmize** [comment]
@glogiotatidis can you share any more details about the CSRF error you got? I double checked the settings and they looked correct, and sentry and didn't show any recent CSRF errors, and without a traceback or even an error message building a model of what could be going wrong is challenging.

**Comment by jgmize** [comment]
from https://sentry.prod.mozaws.net/operations/snippets/issues/4921873/?query=is:unresolved

Forbidden (CSRF cookie not set.): /admin/base/asrsnippet/6/change/

{"status_code":403,"request":"<WSGIRequest: POST '/admin/base/asrsnippet/6/change/'>"}

**Comment by jgmize** [comment]
Note that in the error above, we can see that the sessionid cookie was set, but the CSRF cookie was not.

**Comment by glogiotatidis** [comment]
> @glogiotatidis I also noticed that this was your session. Did this correspond to a CSRF timeout on your end?

This was me from my local dev environment verifying that the log handler to Sentry was working. I did manually remove the CSRF cookie to trigger the error.

This was just pushed to production.

Errors in production admin instance should appear in the custom [Prod Admin](https://sentry.prod.mozaws.net/operations/snippets/searches/1754/) sentry search

**Comment by glogiotatidis** [comment]
According to reports from Snippet Editors in #801 they still get the error. I cannot find a related report in Sentry.

**Comment by glogiotatidis** [comment]
Discussed with OMN team and this doesn't seem to be an issue anymore. Will close for now but feel free to re-open if this appears again.
