### ISSUE TITLE
Integrate Slack to post updates when ASRSnippet changes

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#771]
See also #751

**Comment by glogiotatidis** [comment]
/remind me to re-eval in 2 weeks

**Comment by glogiotatidis** [comment]
The Slack integration proved useful, let's implement this

**Comment by mediaChick** [comment]
To clarify: Everytime a snippet is changed, a status update pushes to slack?

If so, that seems unnecessary.

The slack channel is so we can keep an eye on snippets that need reviewing,
and so content creators can get notified when their snippets have been
reviewed and published -- not as a catch-all for snippet activity.

**Comment by jkt230** [comment]
Let's definitely do this for ASR when it rolls out next week, thanks!
