### ISSUE TITLE
Set `target="_blank"` for time.is link in admin

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#793]
The link "See the current time in UTC" on the Change ASR Snippet page should be target="_blank" (because otherwise, when you click the link, unsaved work is lost when the url loads)

**Comment by jkt230** [comment]
![screen shot 2018-10-25 at 10 34 58 am](https://user-images.githubusercontent.com/6807556/47519122-abb46400-d841-11e8-9668-16fea753a89c.png)

**Comment by glogiotatidis** [comment]
This has been fixed in production.

@mozmeao/lcm-team @jkt230 @mediaChick can you please confirm that this works for you?
