### ISSUE TITLE
ASR Snippet Admin: Calculate PT and ET zones automatically alongside UTC publishing times 

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#798]
Publishing time is difficult to calculate with UTC/server time; we would like to be able to ensure that users (wherever they are in the world) see our snippets based on the timeframe we set for that day. (i.e. 12:00am to 11:59pm for PT, ET, etc.) rather than us setting it for ET and the PT folks getting it 3 hours late and running 3 hours too long for instance.

**Comment by glogiotatidis** [comment]
So what you're really asking here is for Browser Local Publishing Time (instead of server) and that's covered by #667 

Feel free to re-open if I get this wrong. Thanks!
