### ISSUE TITLE
ASR: List of running snippets for public audience

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#799]
We used to use snippets.mozilla.com to guide people to live snippets so they could see what was running and what specific snippets looked like. Can we have something like this with ASR?

**Comment by grahamperrin** [comment]
+1

Cross reference https://www.reddit.com/r/privacytoolsIO/comments/abfgj5/-/ed2jmog/

**Comment by grahamperrin** [comment]
https://snippets.mozilla.com/list/jobs/ noted with thanks. 

I have snippets enabled but I see no snippet at (for example) 

`about:newtab?theme=light&endpoint=https://snippets-prod.oregon-b.moz.works/preview-asr/a176df98-c66a-4139-963f-1c5c7c070b25/`

@glogiotatidis please, what am I missing?

**Comment by glogiotatidis** [comment]
Hey @grahamperrin 

You're not missing something. I designed the list to work on https://snippets-admin.mozilla.org and thus from snippets.mozilla.com it returns non-working preview links (this domain is not whitelisted by default). I also filed #1251 to fix this permanently, meanwhile just use https://snippets-admin.mozilla.org.
