### ISSUE TITLE
ASR Snippet Admin: Have "Save" Button always in view when scrolling through edit pane (same for "Target" and "Campaigns" editing pages)

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#800]
Would also like to have a “Save” button always in view when scrolling through edit pane (aka sticky button); rather than just at the top and bottom of the page.

**Comment by jkt230** [comment]
![screen shot 2018-10-25 at 10 39 01 am](https://user-images.githubusercontent.com/6807556/47519324-3301d780-d842-11e8-8b1d-94ba939b3983.png)

**Comment by glogiotatidis** [comment]
From previous discussions I understand that this is wanted so you can save more often to avoid #801.

Is this true? If so, when we fix #801 would this still be a need?

**Comment by jkt230** [comment]
Not needed right now.
