### ISSUE TITLE
ASR Snippet Admin: Investigate why randomly we get error messages when using the "save and continue editing" button

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#801]
Continuing to get error messages when using the “Save and continue editing” button - haven’t been able to pinpoint scenarios that trigger this.  One theory is if we spend more than a few minutes on the editing pane without saving this occurs.

**Comment by jkt230** [comment]
![screen shot 2018-10-25 at 10 39 39 am](https://user-images.githubusercontent.com/6807556/47519427-765c4600-d842-11e8-8e29-2c29ccc9380f.png)

**Comment by glogiotatidis** [comment]
We're aware of this and trying to understand the root cause. We try to fix this in #767.

I will update here when we have this in production.

**Comment by jkt230** [comment]
I have not received this error in the last two weeks while testing the ASR snippets. I defer to @mediaChick in regards to Activity Stream snippets.

**Comment by mediaChick** [comment]
I got the error last Saturday (Nov 24) in Activity Stream.

**Comment by glogiotatidis** [comment]
This is very helpful, thanks @mediaChick

**Comment by glogiotatidis** [comment]
Discussed with OMN team and this doesn't seem to be an issue anymore. Will close for now but feel free to re-open if this appears again.
