### ISSUE TITLE
ASR Snippet Admin: Place Snippet ID on editing page

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#802]
Currently we only see what the snippet id is in the URL, would like to see the Snippet ID on top of the editing page. (One thought is to replace or move the red Delete button and put Snippet ID there instead).

**Comment by jkt230** [comment]
![screen shot 2018-10-25 at 10 43 00 am](https://user-images.githubusercontent.com/6807556/47519616-c1765900-d842-11e8-8fa2-38716861cdd3.png)

**Comment by glogiotatidis** [comment]
Placing things next to those buttons is a pain. 

I can put it above the snippet name and even apply styles to make more prominent (color, background) if you want. 

What do you think @jkt230 ?

**Comment by glogiotatidis** [comment]
This has been fixed in production for Snippet, ASRSnippet and JSONSnippet.

@mozmeao/lcm-team @jkt230 @mediaChick can you please confirm that this works for you?

**Comment by mediaChick** [comment]
Confirmed! Nice to see those snippet IDs on the edit page in Snippet, ASRSnippet and JSONSnippet.
