### ISSUE TITLE
Snippets not showing in Firefox 63

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#815]
Both Michelle and I upgraded to Firefox 63 and we are not seeing snippets. We double checked the admin to make sure that there are published snippets that should be running.

Not sure if it's related to this issue: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1493262

But this is a priority! Thank you!

**Comment by jkt230** [comment]
@k88hudson in case you may know.

**Comment by k88hudson** [comment]
This does indeed appear to be a bug on the Firefox side, I've filed and escalated to release management here: https://bugzilla.mozilla.org/show_bug.cgi?id=1503047

**Comment by glogiotatidis** [comment]
Thanks for reporting @jkt230. As Kate mentions this is a platform bug. 

I filed #816 to improve the monitoring situation to catch errors like this in the future.

Will leave this open to track the fix of the bug.

**Comment by glogiotatidis** [comment]
This has been fixed in Firefox 63.0.1. Will re-check to confirm that we get expected number of impressions.

/remind me to check number of impressions on Wed

**Comment by glogiotatidis** [comment]
Numbers have returned back to normal :sweat_smile:
