### ISSUE TITLE
ASR Snippets: Preview snippet loads and then a "real" snippet loads

### ISSUE THREAD

**Issue by mediaChick** [mozmeao/snippets-service#824]
Snippets previewed in a new tab using the copy/pasted link provided on the edit page of ASR snippets first loads the snippet to be previewed, then loads a "real" snippet. 

Here's an ASR preview link that behaves as described above for me: about:newtab?endpoint=https://snippets-admin.mozilla.org/preview-asr/cacded45-c3f4-4446-a88f-f98305c8c382/

I'm unable to capture the preview snippet, before it loads the real snippet with the Screenshot add-on -- it's too fast. In trying to capture the bug, (and this may be an entirely different issue or not an issue): the Fx Screenshot add-on appears to be available to use via the awesome bar (...) 

![awesome-bar-snippet-screenshot](https://user-images.githubusercontent.com/39389621/47883139-36203900-dde9-11e8-9ef5-b84e466ac399.png)

But selecting "Take a Screenshot" just opens the My Screenshots. 

@glogiotatidis @k88hudson @jkt230

**Comment by piatra** [comment]
I can confirm the bug. This issue has been resolved in Firefox 64.
