### ISSUE TITLE
Update snippet stats datadog monitor thresholds

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#825]
Monitors to check metrics collection created in #816 #654 will have to be updated to match the new lower thresholds  when we switch to ASR and Telemetry for data collection.

The same monitors will be eventually deleted when we decide to drop pre-ASR support.

/remind me to update monitors on 12/10/2018

**Comment by glogiotatidis** [comment]
We're waiting for 65 to reach Beta, which should be this week. Will keep an eye

**Comment by glogiotatidis** [comment]
Monitor still OK, I'll recheck when we're about to flip the pref for Release channel 

/remind me to update monitors on 01/07/2019

**Comment by metadave** [comment]
added myself

**Comment by glogiotatidis** [comment]
The [`Collected snippet metrics unusally low`](https://app.datadoghq.com/monitors/6919608) monitor got triggered after fully switching snippets to ASR on Jan 17th. This is expected behavior. 

I'm pasting here the monitor configuration for reference
```
Metric:
sum:snippets_proxy.process_request.ga.200{*}.as_count()

Alert Threshold: 25000
Warning Threshold: 30000
```

and I'm deleting the monitor since it's not useful anymore.

Will keep the anomaly detection monitor around to keep checking for anomalies in the pre-ASR pipeline.
