### ISSUE TITLE
QA ASR Simple Snippet Template

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#830]
Simple Snippet Variables

```
{{ title }}
{{ text }}
{{ icon }}
{{ title_icon }}
{{ button_url }}
{{ button_label }}
{{ button_color }} * default #0C0C0D.
{{ button_background_color }}  * default #D7D7DB.
{{ block_button_text }}  * default "Remove this"
{{ tall }}
{{ do_not_autoblock }}
```
Verified that:
 - `block_button_text` defaults to `Remove this`
 - `block_button_text` can be overridden
 - `icon` works
 - `title` works
 - `title_icon` works
 - `button_label` if present, button appears
 - `button_url` works
 - `tall` works
 - `do_not_autoblock` works

Differences
 - `button_color` to `inherit` - This is a good change so snippets show nicely with different Fx themes, but we need to verify that snippet which those use look OK. Filed #836
 - `button_background_color` defaults to `var(--newtab-button-secondary-color)` - This is a good change so snippets show nicely with different Fx themes, but we need to verify that snippet which those use look OK. Filed #836
 - Clicking on button opens link in new Tab. This is different from what happens now. Clicking on link opens link in the same Tab. This is what happens now. Filed bug [1506594](https://bugzilla.mozilla.org/show_bug.cgi?id=1506594)

Need information on how to verify
 - `do_not_autoblock` - update: works
 - Pinged AS QA to provide info in [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1482859#c12)
 - Update: 
   - Set `browser.newtabpage.activity-stream.asrouter.devtoolsEnabled` pref to `true` and visit `about:newtab#asrouter`. Will see the block list.

**Comment by glogiotatidis** [comment]
Added an item in tomorrow's mtg agenda to discuss clicking on links / buttons and new tabs

**Comment by glogiotatidis** [comment]
@mozmeao/lcm-team FIY this is the QA for Simple Snippet Template. Please add any additional information / issues / missing elements in this PR asap.

**Comment by ldwright** [comment]
@glogiotatidis - Per snippet help text for "title" field in the admin tool (i.e. _Optional. Snippet title displayed above snippet text._) When used and being previewed, the copy actually shows up right before/side-by-side to the actual snippet text rather than above as intended.

**Comment by glogiotatidis** [comment]
@ldwright This is the proper design afaik. This brings up a good point though: Do we have an updated and complete list of all the template designs?

**Comment by glogiotatidis** [comment]
> @ldwright This is the proper design afaik. This brings up a good point though: Do we have an updated and complete list of all the template designs?

Filed [bug 1506600](https://bugzilla.mozilla.org/show_bug.cgi?id=1506600) to discuss and fix this. 

/cc @ldwright

**Comment by glogiotatidis** [comment]
Related bugs have been fixed. Template works fine.
