### ISSUE TITLE
QA ASR Newsletter Template

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#832]
Newsletter Variables
```
{{ scene1_icon }}
{{ scene1_button_label }}
{{ scene1_button_background_color }}  #D7D7DB.
{{ scene1_button_color }} #0C0C0D
{{ scene1_text }}
{{ scene1_title }}
{{ scene1_title_icon }}

{{ scene2_text }}
{{ scene2_title }}
{{ scene2_newsletter }}  Default 'mozilla-foundation'
{{ scene2_email_placeholder_text }} Default 'YOUR EMAIL HERE'.
{{ scene2_button_label }} Default 'Sign Me Up'.
{{ scene2_privacy_html }}
{{ scene2_dismiss_button_text }} Default 'Dismiss'.

{{ locale }} Default "en-US".
{{ error_text }}
{{ success_text }}

{{ block_button_text }}
{{ do_not_autoblock }}
```

Verified working:
- `scene1_icon` works
- `scene1_title_icon` works
- `scene1_button_label` works
- `scene1_text` works
- `scene1_title` works
- `scene2_text` works
- `scene2_button_label` works
- `scene2_privacy_html` works
- `error_text` works
- `success_text` works

Differences
- `scene1_button_background_color` works,  defaults to var(--newtab-button-secondary-color) - This is a good change so snippets show nicely with different Fx themes, but we need to verify that snippet which those use look OK. Filed #836
- `scene1_button_color` works, defaults to `inherit` - This is a good change so snippets show nicely with different Fx themes, but we need to verify that snippet which those use look OK. Filed #836 

Things that don't work
- `scene2_title` doesn't work
- `scene2_newsletter` doesn't work. `en-US` is hard-coded :fire:
- `scene2_email_placeholder_text` works but no default value
- `scene2_dismiss_button` works but no default value

Visual Differences:
 - Privacy policy text and checkbox are misaligned 
 - Snippet container is narrower. Also Snippet text looks smaller. I don't know if that a preview side effect?

Top is ASR snippet VS current AS snippet
![image](https://user-images.githubusercontent.com/584352/48138021-0d49e900-e2ac-11e8-9c11-f938b2c914e9.png)

**Comment by glogiotatidis** [comment]
Related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1505406

**Comment by glogiotatidis** [comment]
@mozmeao/lcm-team FIY this is the QA for Newsletter Template. Please add any additional information / issues / missing elements in this PR. Remember to test with Beta

**Comment by jkt230** [comment]
Hi Giorgos, we've tried to ASR QA Newsletter template (snippet id 14) but when I preview, it quickly jumps to the current snippets live so it doesn't give me a chance to test it out. Is there a way to work around this?

**Comment by glogiotatidis** [comment]
> Hi Giorgos, we've tried to ASR QA Newsletter template (snippet id 14) but when I preview, it quickly jumps to the current snippets live so it doesn't give me a chance to test it out. Is there a way to work around this?

This sounds like #824. Can you confirm that you're testing with Beta or Nightly?

**Comment by jkt230** [comment]
It does sound like 824. And I was testing with Beta 64.0b9. Do you think it's because I also have the release version on my computer as well so it gets confused?

**Comment by jkt230** [comment]
Other issues:

- Default “YOUR EMAIL HERE” but don’t see it (I think you've mentioned it)
- Default “Sign Up” but don’t see it
- Missing but maybe the new colors were chosen purposely to work with dark themes?:
scene1_button_background_color “Button background color. Default #D7D7DB.” 
scene1_button_color “Button text color. Default #0C0C0D.”
- Sent myself an email, have yet to receive it (using default: mozilla-foundation), need to make sure basket ids are being passed

**Comment by ldwright** [comment]
False alarm on the html link not working in scene2_privacy_html, I noticed a space between a href= and " and appears to be working now. Should be good.

**Comment by glogiotatidis** [comment]
> * Default “YOUR EMAIL HERE” but don’t see it (I think you've mentioned it)
Already mentioned.

> * Default “Sign Up” but don’t see it
Default is `Sign me Up`, should be fixed in nightly
 
> * Missing but maybe the new colors were chosen purposely to work with dark themes?:
>   scene1_button_background_color “Button background color. Default #D7D7DB.”
>   scene1_button_color “Button text color. Default #0C0C0D.”

Yes I talk about buttons in `differences` section. We should talk about using non-default colors at some point. See also #682 

> * Sent myself an email, have yet to receive it (using default: mozilla-foundation), need to make sure basket ids are being passed

I'd check this complete behavior on nightly. The bugs we have already filed issues for are only in nightly atm.

**Comment by glogiotatidis** [comment]
Thanks for your reviews @jkt230 @ldwright 

It doesn't seem that we found any missing items. Please check with an up-to-date nightly that everything reporting here has been fixed.

**Comment by jkt230** [comment]
Tested on nightly and received the email, thanks!

**Comment by glogiotatidis** [comment]
Related bugs have been fixed. Template works.
