### ISSUE TITLE
QA FxA Sign Up Template

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#833]
Variables

```
{{ scene1_icon }}  - Optional
{{ scene1_title }} - Optional
{{ scene1_title_icon }} - Optional 
{{ scene1_text }} - Rich Text for scene1/initial view of the snippet.
{{ scene1_button_label }} - Default `Learn more`
{{ scene1_button_color }} - Default #0C0C0D (see `differences` section) 
{{ scene1_button_background_color }} - Default #D7D7DB (see `differences` section)

{{ scene2_title }} - Optional
{{ scene2_text }} - Rich text
{{ scene2_email_placeholder_text }} - Optional `YOUR EMAIL HERE`
{{ scene2_button_label }} - Optional `Sign Me Up`
{{ scene2_dismiss_button_text }} - Optional `Dismiss`

{{ utm_term }}
{{ utm_campaign }}

{{ block_button_text }} - Defaults to `Remove this`
{{ do_not_autoblock }}
```

Verified working:
 - Can set `utm_campaign` 
 - Can set `utm_term` 
 - Can set `scene2_text`
 - Can set `scene1_icon`
 - Can set `scene1_title`
 - `scene1_title` is optional
 - Can set `scene1_icon`
 - `scene1_icon` is optional
 - Can set `scene1_button_label`
 - Can set `scene2_text`
 - Can set `scene2_placeholder_text`
 - Can set `scene2_dismiss_button`
 - Can set `scene2_button_label` 
 - `block_button_text` has default value
 - Can set `block_button_text` custom

Things that don't work
 - `scene1_button_label` has no default value.
 - `scene2_placeholder_text` has no default 
 - `scene2_dismiss_button` has no default
 - `scene2_button_label` has no default
 - `scene2_text` is not rich text - *fixed in nightly*
 - `scene2_title` will not appear - *fixed in nightly*
 - `scene2_text` is larger compared to `scene1_text` (14px vs 12px) - *fixed in nightly*

Differences
 - `scene1_button_color` to `inherit` - This is a good change so snippets show nicely with different Fx themes, but we need to verify that snippet which those use look OK. Filed #836
 - `scene1_button_background_color` defaults to `var(--newtab-button-secondary-color)` - This is a good change so snippets show nicely with different Fx themes, but we need to verify that snippet which those use look OK. Filed #836

**Comment by glogiotatidis** [comment]
Issues filed in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1509810

**Comment by glogiotatidis** [comment]
@mozmeao/lcm-team FIY this is the QA for FxA Signup Template. Please add any additional information / issues / missing elements in this PR. Remember to test with Beta

**Comment by jkt230** [comment]
Looks all good outside the design issue:

The ASR FxA snippet in terms of font size and button size are a lot smaller than the Activity Stream version when compared side by side

![screen shot 2018-11-26 at 11 43 32 am](https://user-images.githubusercontent.com/6807556/49038048-a9129a80-f170-11e8-869a-f334fd8f7623.png)

**Comment by glogiotatidis** [comment]
Issues filed in bug have been verified fixed. 

@jkt230 I wasn't in the design meeting. Do you have an update on why the new snippets appear smaller?

**Comment by jkt230** [comment]
Turns out one of my screens was zoomed in :( So no issue, the design sizing is the same :)

**Comment by glogiotatidis** [comment]
Thanks! closing
