### ISSUE TITLE
QA ASR Fundraising Template

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#834]
Variables

```
{{ donation_form_url }}
{{ currency_code }}
{{ locale }}
{{ text  }}
{{ text_color }}
{{ background_color }}
{{ highlight_color }}
{{ donation_amount_first }}
{{ donation_amount_second }}
{{ donation_amount_third }}
{{ donation_amount_fourth }}
{{ selected_button }}
{{ icon }}
{{ button_label }} 
{{ button_color }}
{{ button_background_color }}
{{ block_button_text }}
{{ monthly_checkbox_label_text }}
{{ test }}
{{ do_not_autoblock }}
```

Things that work
- `text` - works and it's rich text
- `donation_amount_first` works
- `donation_amount_second` works
- `donation_amount_third` works
- `donation_amount_fourth` works
- `test` works, both `bold` and `takeover`
- `icon` works
- `monthly_checkbox_label_text` works and selects montly contributions correctly
- `highlight` text works (and em works)
- `block_button_text` defaults to `remove this`
- custom `block_button_text`
- `text_color` works
- `locale` works
- `selected_button` works
- `currency_code` works
- `button_label` works
- `button_color` works
- `background_color` works
- `donation_form_url` works  
- Functionally the snippet works: I.e. users get to the donation page with amount and donation type (one-off / montly) preselected.

Things that don't work
- We always display icon (defaults to Fx logo)
- `monthly_checkbox_label_text` has no default. Should be `Make my donation monthly`
- `selected_button` no default value. Should be `donation_amount_second`
- `currency_code` no default value. Should be `usd`
- `donation_form_url` URL params do not get preserved
- Checkbox looks weird
![image](https://user-images.githubusercontent.com/584352/49017242-12a2a100-f191-11e8-9db2-817e05bcc0ab.png)

Differences:
- `button_background_color`, `background_color`, `text_color`, `button_color` default to theme colors. Added note in #836. Added an item to #678 to manually check all those snippets to verify that they display correctly.

**Comment by glogiotatidis** [comment]
Filed bug https://bugzilla.mozilla.org/show_bug.cgi?id=1509851 with the found issues

**Comment by glogiotatidis** [comment]
@mozmeao/lcm-team FIY this is the QA for Fundraising Template. Please add any additional information / issues / missing elements in this PR. Remember to test with Beta

**Comment by jkt230** [comment]
Looks all good outside the design issue:

Same as FxA template, the ASR snippet looks a lot smaller (condensed) when compared side by side with the Activity Stream one
![screen shot 2018-11-26 at 11 43 43 am](https://user-images.githubusercontent.com/6807556/49038023-99935180-f170-11e8-8e65-8e06734c6a6a.png)

**Comment by glogiotatidis** [comment]
@k88hudson do you know why snippets appear smaller in ASR? if this a design decision?

**Comment by k88hudson** [comment]
I debugged this with Jean and it looks like she had her browser zoomed in on about:newtab which was making other snippets look larger; the design spec specifies `14px` which is what's currently in nightly, still awaiting uplift to 64

**Comment by glogiotatidis** [comment]
Bug fixed and verified. Thanks all!
