### ISSUE TITLE
Slack notifications for changes in the list view + include creators name

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#838]
Related to #751  (let me know if you rather I reopen that issue):

1) We noticed that when we're in the list view page and checkmark the "published" box and then save, it does not send notifications to our Slack channel #snippets-admin . We would like this method to also send notifications. It only sends notifications when we're in the editing mode page and selecting "published" or "ready for review" in the drop down menu and then saving. 

2) Is it possible within the slack notifications for #snippets-admin to include the content creator's name? For example "Snippet #9553 is ready for review!" by Michelle Anderson, or "Snippet #9553 is published!" by Jean Collings. 

3) Are people who have rights to the snippet service (whether they are admin, advanced user, content creator) automatically added to the #snippets-admin channel? Is there a way to do that?

**Comment by glogiotatidis** [comment]
>     3\. Are people who have rights to the snippet service (whether they are admin, advanced user, content creator) automatically added to the #snippets-admin channel? Is there a way to do that?

Not at the moment. Please handle the Slack group manually.
