### ISSUE TITLE
Add image gallery for icons

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#841]
Investigate this possibility.

It can make the editor's life easier by not uploading the same image over and over and our db smaller. 

As a by-product we can improve the image file size by optimizing on save.

Checks:
 -  image size
 -  Image format
   -  PNG
   - [x] SVG - Django does not support this using `ImageField`. see #925 
 - Transparency
 - image dimensions
 
Open Questions
 -  What to do with currently used images that fail the checks. E.g.
    - Images with wrong dimensions
    - Images in the wrong format (jpeg)
   
Migrate:
 - [x] PNGs wrapped in SVGs

Deploy:
 - [x] Set `MEDIA_ICONS_ROOT="media/icons/"`

This can also work with #634

**Comment by jkt230** [comment]
Want to confirm this is adding the icon library / gallery to the admin tool. [also needs to be searchable and be able to check format/size when uploading].

**Comment by glogiotatidis** [comment]
Yes!

I need to re-engineer how we do template forms first, but that's one of my next things.

**Comment by glogiotatidis** [comment]
The gallery has been deployed to production. We'll create seperate issues for image validation
