### ISSUE TITLE
[Activity Stream] Snippets that have finished their publishing dates are still running

### ISSUE THREAD

**Issue by mediaChick** [mozmeao/snippets-service#858]
I use two computers: both are PCs, both use Windows 10, both run Fx 63.0.3 GA release.

This morning I turned on one computer (it was totally off) and snippets that are set to not be running anymore on November 22 are still running on November 24 on new:tab. I've confirmed the publishing settings in the snippet admin.

![untitled-1](https://user-images.githubusercontent.com/39389621/48971263-294bcb00-efcc-11e8-9f47-5c1a18c544ae.png)

![untitled-3](https://user-images.githubusercontent.com/39389621/48971297-716aed80-efcc-11e8-8fbf-0070db5d1862.png)

![untitled-2](https://user-images.githubusercontent.com/39389621/48971272-3d8fc800-efcc-11e8-883e-2d931060c32f.png)

The World Hello Day holiday snippet above was set to run less than 24 hours on Wednesday, Nov 21 and it's still running on Saturday, Nov 24.

I opened my second computer, which was on but "asleep" since Nov 21 PM, and the snippets above aren't showing -- the snippets scheduled to run right now are.

What is causing unpublished snippets to still appear on just one computer, days after they should have stopped?

**Comment by jkt230** [comment]
I think it may have to do with our "four hour" cache but will let Giorgos confirm!

**Comment by glogiotatidis** [comment]
Indeed that related to the caching.

One thing to note in the specific issue is that publishing start and ending times are handled on the server and not on the client. In this case the browser had a cached version of snippets and it didn't know they had expired until it fetches new snippets. 

This was designed to be feature back in the day so we could avoid sending marketing snippets too early to browsers and leak campaigns before their time. We can discuss if we want a different approach today. I have #667 which is related.

So the question is:

Do both your computers show up-to-date snippets now @mediaChick ?

**Comment by mediaChick** [comment]
@glogiotatidis Both computers are showing current snippets today.

**Comment by glogiotatidis** [comment]
Great, thanks for confirming @mediaChick . I will close this one out then and we can discuss future behavior in #667
