### ISSUE TITLE
[FxA Sign Up Template] Investigate if accounts.f.c has locales support and make the template redirect to the correct locale

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#859]
It seems that the FxA signup/signin template always points users to a en-US version of accounts.firefox.com.

Not sure if accounts.f.c supports other locales. Go ahead and 
 - investigate if other locales are supported
 - if so extend template to support redirecting to the correct locale.

**Comment by jkt230** [comment]
I chatted with Chris More (Adavis was out of office) and he said: "it is all localized. I think it just detects your locale and gives you that content. They may have the ability to pass parameters"

**Comment by glogiotatidis** [comment]
Indeed, verified. It uses `Accept-Language` header and provides localized content. Tested with German

Thanks for checking @jkt230
