### ISSUE TITLE
Update newsletter and s2d templates with new error_page_button_label variable

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#862]
https://bugzilla.mozilla.org/show_bug.cgi?id=1510331

- [ ]  After we push update to the snippets-server we want to update existing snippets with localized retry button text.

**Comment by glogiotatidis** [comment]
Not happening for Fx64, added a note to check in #860

**Comment by glogiotatidis** [comment]
Thanks for working on this @jpetto !

We need to add the new field in the snippets-service side too. Is this something you'll take care or I can help with?

**Comment by jpetto** [comment]
Ah, yep. I'll file a PR for that today.

**Comment by glogiotatidis** [comment]
See #1170 for localiztion
