### ISSUE TITLE
Preview is always using the default theme

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#863]
Currently ASR Snippets preview always displays the default theme. We need a way to preview in other themes as well.

https://bugzilla.mozilla.org/show_bug.cgi?id=1510335

**Comment by jkt230** [comment]
We talked during All Hands the ability to show or not show dark themes in preview mode.

**Comment by glogiotatidis** [comment]
AS team merged a PR, so this is moving \o/

Waiting on docs and then we'll implement our part.

**Comment by glogiotatidis** [comment]
/remind me in two weeks to update with ETA

**Comment by glogiotatidis** [comment]
https://github.com/mozmeao/snippets-service/issues/942

**Comment by glogiotatidis** [comment]
Preview works now on nightly. I'll add this to the queue

**Comment by glogiotatidis** [comment]
Work is tracked in #942. Closing this one
