### ISSUE TITLE
Will List view page Filters and Categories get transferred over to ASR admin?

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#872]
Legacy snippet admin has these filters: 
-By last modified
-by published
-by ready for review
-by channel
-by targeted locales
-by client match rules (probably not necessary)
-by template

Will we have these filters in ASR?

In addition the legacy snippet admin has these categories in the list view:
-Published checkbox
-locale list
-modified time stamp

Can we have these in ASR as well?

**Comment by glogiotatidis** [comment]
Of course! Let's see what's missing in ASR

> -By last modified

exists

> -by published

exists

> -by ready for review

exists

> -by channel

exists

> -by targeted locales

Filed #878

> -by client match rules (probably not necessary)

doesn't exist but won't implement.

> -by template

exists

 
> -Published checkbox
That we can't migrate 1 to 1 without some thought. See ASRSnippets have multiple states `published`, `draft`, `awaiting review` so a checkbox doesn't make sense anymore.

You can already see the status of the snippet in the list view 

![image](https://user-images.githubusercontent.com/584352/49746259-7a84db80-fca9-11e8-9d99-8ab70290a935.png)

And I'm working on adding an action to allow you to publish multiple snippets from that view in #879

![image](https://user-images.githubusercontent.com/584352/49746614-38a86500-fcaa-11e8-8162-41bc0d056b1e.png)


> -locale list

Filed #878

> -modified time stamp

exists

**Comment by glogiotatidis** [comment]
@jkt230 are you covered by the previous comment? Should we go forward with the listed filed issues? Anything else missing / wanted?

**Comment by jkt230** [comment]
Looks good thanks!

**Comment by glogiotatidis** [comment]
Perfetto! We track the new issues for fixes. Closing this one.
