### ISSUE TITLE
Add Category field to ASR Snippets

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#874]
As discussed during the Allhands we want to have a special `Category` field for ASRSnippets.

Add:
 - [x] Category field
 - [x] Add list view filter for categories
 - [x] Complete field for existing snippets
 - ~~Add step in Snippets -> ASRSnippets script~~
 - [x] Give Snippet Editors permissions to edit Categories

@mediaChick @jkt230 can you please list the currently used categories so I can automatically complete the new field for existing snippets?

**Comment by glogiotatidis** [comment]
Also @mediaChick @jkt230 should category be a required field for all snippets ?

**Comment by jkt230** [comment]
Here's the categories we use (is there a way to add description so new publishers understand how to categorize?)

**Utility**
Tips & Tricks + Features - how to get the most out of Firefox like Add-ons, SUMO, FxA

**Other Products & Services** 
Examples like: Lockbox, Firefox Reality Browser, Pocket, Notes, Test Pilot, New Product Releases (Non-Fx), Firefox Send, Firefox Monitor (in dev), VPN (in dev)

**Email** 
Email sign-ups for Mozilla, Firefox, Dev, Mozilla Labs [VR, Scout, Common Voice - etc.], Pocket

**Delight** 
Delightful content including Wiki, Enlightening Life Hacks, Holidays

**Mobile**
Send to Device widgets for Firefox, Focus/Klar, Rocket, Pocket, IRL, Lockbox, Notes, FxA, New Product Releases

**Mission** 
Content around MoFo, Manifesto, Advocacy, Petitions, Fellows, IRL Podcast

**Topical**
Content around contests, Surveys, Fx Census, Blog Posts, Events, Referrals (TY/refer-a-friend) + New Release/Upgrade to latest version (talk about what's changed)

**Fundraising**
Content for fundraising; usually simple snippets 2x a quarter + $$$ Button EOY template 1x a quarter. EOY rotation: Varies.





> As discussed during the Allhands we want to have a special `Category` field for ASRSnippets.
> 
> Add:
> 
>     * [ ]  Category field
> 
>     * [ ]  Add list view filter for categories
> 
>     * [ ]  Complete field for existing snippets
> 
>     * [ ]  Add step in Snippets -> ASRSnippets script
> 
> 
> @mediaChick @jkt230 can you please list the currently used categories so I can automatically complete the new field for existing snippets?

Here's the categories we use (is there a way to add description so new publishers understand how to categorize?)

**Utility**
Tips & Tricks + Features - how to get the most out of Firefox like Add-ons, SUMO, FxA

**Other Products & Services** 
Examples like: Lockbox, Firefox Reality Browser, Pocket, Notes, Test Pilot, New Product Releases (Non-Fx), Firefox Send, Firefox Monitor (in dev), VPN (in dev)

**Email** 
Email sign-ups for Mozilla, Firefox, Dev, Mozilla Labs [VR, Scout, Common Voice - etc.], Pocket

**Delight** 
Delightful content including Wiki, Enlightening Life Hacks, Holidays

**Mobile**
Send to Device widgets for Firefox, Focus/Klar, Rocket, Pocket, IRL, Lockbox, Notes, FxA, New Product Releases

**Mission** 
Content around MoFo, Manifesto, Advocacy, Petitions, Fellows, IRL Podcast

**Topical**
Content around contests, Surveys, Fx Census, Blog Posts, Events, Referrals (TY/refer-a-friend) + New Release/Upgrade to latest version (talk about what's changed)

**Fundraising**
Content for fundraising; usually simple snippets 2x a quarter + $$$ Button EOY template 1x a quarter. EOY rotation: Varies.

**Comment by jkt230** [comment]
> Also @mediaChick @jkt230 should category be a required field for all snippets ?

No it should not be required, in the event it doesn't fit a category (or we need to put in a new category name).

**Comment by glogiotatidis** [comment]
Run code to create categories based on https://github.com/mozmeao/snippets-service/issues/874#issuecomment-445916104 and assign to ASRSnippets

```python
CATEGORIES = {
    'Utility': 'Tips & Tricks + Features - how to get the most out of Firefox like Add-ons, SUMO, FxA',
    'Other Products & Services': ('Examples like: Lockbox, Firefox Reality Browser, Pocket, Notes, Test Pilot, '
                                  'New Product Releases (Non-Fx), Firefox Send, Firefox Monitor, VPN'),
    'Email': 'Email sign-ups for Mozilla, Firefox, Dev, Mozilla Labs (VR, Scout, Common Voice - etc.), Pocket',
    'Delight': 'Delightful content including Wiki, Enlightening Life Hacks, Holidays',
    'Mobile': 'Send to Device widgets for Firefox, Focus/Klar, Rocket, Pocket, IRL, Lockbox, Notes, FxA, New Product Releases',
    'Mission': 'Content around MoFo, Manifesto, Advocacy, Petitions, Fellows, IRL Podcast',
    'Topical': ('Content around Contests, Surveys, Fx Census, Blog Posts, Events, '
                'Referrals (TY / refer-a-friend) + New Release/Upgrade to latest version (talk about what\'s changed)'),
    'Fundraising': ('Content for fundraising; usually simple snippets '
                    '2x a quarter + $$$ Button EOY template 1x a quarter. EOY rotation: Varies.'),

}

user, _ = User.objects.get_or_create(username='jcollings')
for name, description in CATEGORIES.items():
    cat, _ = Category.objects.get_or_create(creator=user, name=name, description=description)
    ASRSnippet.objects.filter(category=None, name__icontains='_{}_'.format(name)).update(category=cat.id)
```
