### ISSUE TITLE
Update ASR Targeting Functionality in Admin

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#883]
During All Hands, we discussed bringing the targeting fields back into the snippet editing mode page so that we can select multiple targets [similar how we can select multiple locales]. 

If anything, definitely need to at least bring back countries in the snippet editing mode page.

**Comment by glogiotatidis** [comment]
> During All Hands, we discussed bringing the targeting fields back into the snippet editing mode page so that we can select multiple targets [similar how we can select multiple locales].

I though we agree to keep targeting as is for now and allow you to select multiple targets for one snippet, right? I filed #875 for this.

**Comment by jkt230** [comment]
Correct! Sorry let me close this one since it's redundant.
