### ISSUE TITLE
Automated data export to Google Cloud Storage for Analytics 

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#887]
We need an automated way to upload to Google Cloud Storage a file with ASRSnippet metadata. The metadata will be in turn parsed by a Python based App Engine job that loads things into Big Query. 

Open questions:
 - [x] File format: Probably CSV. We need to pick a good delimiter 
  - CSV, Delimeter `,`, all fields quoted
 - [x] Interval: How often should the file get updated
  - Daily
 - [x] Metadata to be included:
  - ID
  - Name
  - Campaign

Requires:
- [x] ~~Google Cloud Storage credentials and bucket name~~. Will use S3

- [x] DMS Monitoring Prod

- [x] ADR Document

**Comment by glogiotatidis** [comment]
@gkabbz is this still a thing? Do you have deadline you want this delivered?

**Comment by gkabbz** [comment]
@glogiotatidis apologies for the delay. Yes it's still a thing. I've outlined some requirements here: https://docs.google.com/document/d/1uJkQQkbNZnM-bWmhPZ4AgZPkKZ8wCJXxmD3aZdZMKik/edit
Let me know if you have any questions. I'll setup the bucket for where to drop the file as well as a service account to give you access to the bucket next week.

**Comment by glogiotatidis** [comment]
Done!
