### ISSUE TITLE
ASR Send to Device Template: Input Field Gets Cut Off

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#894]
Can we make this input field flexible so it accepts more characters? It cuts off when I input "Enter your email or phone number" or "Enter your email or phone (10 digits, no spaces) here" 

![screen shot 2019-01-02 at 10 15 23 am](https://user-images.githubusercontent.com/6807556/50605620-9a0dbf00-0e77-11e9-931a-b180da368060.png)

**Comment by glogiotatidis** [comment]
fixed in prod

**Comment by jkt230** [comment]
Can we reopen this issue as it still cuts off some words/letters:

![screen shot 2019-02-07 at 12 02 39 pm](https://user-images.githubusercontent.com/6807556/52439583-ba611700-2ad0-11e9-88c1-91cfe1c9d9cc.png)

**Comment by glogiotatidis** [comment]
Hi Jean,

The new screenshot is in the template (i.e. how the snippets appear on ppls browsers) while the original ask was about the snippets admin UI. Therefore this a new, template related issue.

I feel that the field is visually big enough and I suggest that you rephrase the text or move some of the text in the area bellow. I'm not a UI / UX designer though, so I you want to move this change fwd, please file a new issue. Thanks!

**Comment by jkt230** [comment]
Fair point! I'll experiment with the text and move it below. Thanks for verifying!
