### ISSUE TITLE
ASR Snippet Service List View: Duplicate Snippet Functionality doesn't work 

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#895]
When I try to duplicate a snippet from the list view, it sends me to a "Server Error (500)" page

![screen shot 2019-01-02 at 10 18 15 am](https://user-images.githubusercontent.com/6807556/50605668-d3dec580-0e77-11e9-91ad-be9cdd3e36b1.png)

**Comment by glogiotatidis** [comment]
Got it, thanks for filing the report. Will fix. Meanwhile you can use the `Save as new` button when editing a snippet.

**Comment by glogiotatidis** [comment]
https://github.com/mozmeao/snippets-service/commit/efaf3c69a2440ea9eb3368c72199ff189734d2e5
