### ISSUE TITLE
Unpublishing Functionality Does Not Work for ASR Snippet Admins on Release

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#902]
![screen shot 2019-01-16 at 11 38 23 am](https://user-images.githubusercontent.com/6807556/51275383-aa00c500-1986-11e9-9c75-ea0942b67ae7.png)

Hi Giorgos,
We were trying to unpublish 10546, 10547, 10548 and received this error.

**Comment by glogiotatidis** [comment]
My bad, I failed to update some permissions. Should be fine now. Please check and close issue if everything works for you.

Thanks!

**Comment by jkt230** [comment]
Thanks Giorgos, works now :)
