### ISSUE TITLE
Firefox Emojis not working in https://snippets-admin.mozilla.org/admin/

### ISSUE THREAD

**Issue by stsegovia-moz** [mozmeao/snippets-service#910]
I'm building snippets in the snippets admin tool [https://snippets-admin.mozilla.org/admin/]. Whenever I try to use a Firefox emoji within my copy and then click save, I get an error **"Server Error (500)"**

These are the emoji symbols that I'm trying to use. 
http://mozilla.github.io/fxemoji/dist/FirefoxEmoji/index.html

Here are screenshots of how I used the emoji and the error from saving the snippet. 
![screen shot 2019-02-04 at 10 13 37 am](https://user-images.githubusercontent.com/47153345/52227862-9e0d7200-2865-11e9-8d6a-5162f92a0a15.png)
![screen shot 2019-02-04 at 10 13 47 am](https://user-images.githubusercontent.com/47153345/52227865-a1086280-2865-11e9-95d0-02fb3d80a4dc.png)

**Comment by glogiotatidis** [comment]
Emojis are complicated Unicode symbols which our database configuration does not support atm. I guess this is very low priority, so while it's a valid bug I won't prioritize it for now.

Thanks for the detailed report, it helps!

**Comment by stsegovia-moz** [comment]
Thanks Giorgos! Jean actually confirmed this one for me. My mistake, I thought I was experiencing an error, but it's intentional. It's definitely low priority. 

Thank you for confirming!

**Comment by glogiotatidis** [comment]
This is now working!

Side win from #954
