### ISSUE TITLE
Implement update to ASR Simple Snippet with Button Template with new header icon and labels

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#913]
Giorgos,

I know you're aware of this template update that Jon made but wanted to file a Github to keep track of it. It's available in Beta so would love to start using the updated template as soon as possible so we can test.  

The related issue: https://github.com/mozilla/activity-stream/commit/0087a07d3246d619dd36cfe32e844cafe5d2d1d9

Thanks!

**Comment by glogiotatidis** [comment]
Thanks for filing, will take care of it asap!

**Comment by glogiotatidis** [comment]
This is now available in production for the Simple Snippet Template.

**Comment by jkt230** [comment]
Thank you!! We will try building it and testing it this week.

**Comment by jkt230** [comment]
Question - does this work in release or only in beta?

**Comment by jkt230** [comment]
Just tried to test it and the label/logo did not appear: 

about:newtab?endpoint=https://snippets-admin.mozilla.org/preview-asr/df1c3226-2b62-4aa7-8ba2-cbebea7ba50f/

ID: 10855

**Comment by glogiotatidis** [comment]
This is available in Beta. I tested the preview link above and works fine.
