### ISSUE TITLE
Convert templates to real models

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#916]
Since templates are now code in AS, we can make them code in the service as well. This will allow us to use django's form validation for #655 , use foreign key relationships for the image gallery (#841) and property fix things like #757 

Let's investigate how that would look like and that's the best route to follow.

## Check 
 - [x] Save as new functionality
 - [x] Duplicate
 - [x] user permissions
 - [x] New code serves old templates if no `template_relation` exists

## Deployment plan
 - [x] Backup production DB
 - [x] Run the [migration script](https://gist.github.com/glogiotatidis/f143603e80e9044e0a9e67d777356147) locally with the backup of the previous step. Confirm that all fields are transferred correctly, especially images.
  - List of snippets are required manual migration (all in draft state):
    - [x] 11395
    - [x] 11421
    - [x] 11424
### Staging
 - [x] Set `MEDIA_ICONS_ROOT` config stage
 - [x] Push code to staging
 - [x] Update staging user permissions
 - [x] kubectl into the staging node and install inkscape, required for the migration
   - [x] k8s_oregon_b -n snippets-stage plugin exec-user snippets-stage-clock-86cf445477-7wrjb bash
 - [x] Run migration script
 - [x] Clear bundle cache
   - [x] `deis_oregon run -a snippets-stage  -- ./manage.py clear_cache -a`
 - [x] Confirm bundle generation
 - [x] Kill + restart migration pod
   - [x] k8s_oregon_b -n snippets-stage delete po/snippets-stage-clock-86cf445477-7wrj
### Production
 - [x] Set `MEDIA_ICONS_ROOT` config prod 
   - [x] admin
   - [x] prod oregon
   - [x] prod frankfurt
 - [x] Push code to prod
 - [x] Update prod user permissions
   - [x] Edit ASR Snippets group, search for templates, add all 
   - [x] Edit ASR Snippets group, search for icon, add all
 - [x] kubectl into the staging node and install inkscape, required for the migration
 - [x] Run migration script
 - [x] Clear bundle cache
   - [x] `deis_oregon run -a snippets-admin  -- ./manage.py clear_cache -a`
   - [x] `deis_frankfurt run -a snippets-prod  -- ./manage.py clear_cache -a`
   - [x] `deis_oregon run -a snippets-prod  -- ./manage.py clear_cache -a`
 - [x] Confirm bundle generation
 - [x] Kill + restart migration pod

**Comment by glogiotatidis** [comment]
Note to self: https://stackoverflow.com/a/21498821

**Comment by glogiotatidis** [comment]
Converting to real model is indeed a really good idea.

We have working on in https://github.com/mozmeao/snippets-service/pull/928.

Along this way we decided to go ahead and build the image gallery in #841.

**Comment by glogiotatidis** [comment]
Deployment plan
 - [ ] Backup production DB
 - [ ] Run the [migration script](https://gist.github.com/glogiotatidis/f143603e80e9044e0a9e67d777356147) locally with the backup of the previous step. Confirm that all fields are transferred correctly, especially images.
 - [ ] Push code to staging
 - [ ] Run migration script
 - [ ] Clear bundle cache
 - [ ] Confirm bundle generation
 - [ ] Push code to prod
 - [ ] Run migration script
 - [ ] Clear bundle cache
 - [ ] Confirm bundle generation

**Comment by metadave** [comment]
for prod, can you make another step to remove inkscape when complete:

`kubectl into the staging node and install inkscape, required for the migration`

**Comment by metadave** [comment]
Is there any way to validate the results when in prod?

**Comment by glogiotatidis** [comment]
> for prod, can you make another step to remove inkscape when complete:
> 
> `kubectl into the staging node and install inkscape, required for the migration`

good point. I'll go ahead and kill the migration pod to make sure that it's clean

**Comment by glogiotatidis** [comment]
> Is there any way to validate the results when in prod?

Yes. I'll save replies before after and compare results. Image validation will happen by opening the images and making sure that they appear correctly.

**Comment by glogiotatidis** [comment]
Staging looks good! \o/ 

Waiting on LCM team to confirm production deployment

**Comment by glogiotatidis** [comment]
> Waiting on LCM team to confirm production deployment

we're good. i'm working on the production migration

**Comment by glogiotatidis** [comment]
Production deployment and migration worked flawlessly but the application experienced ten-fold increase in response times on both oregon and frankfurt clusters. 

We collected traces using NewRelic's X-Ray and rolled-back the code to restore the service.

**Comment by glogiotatidis** [comment]
Issue #935 tracks the problem we faced on production.

**Comment by glogiotatidis** [comment]
Today's update:

- Figured out the problem and created a fix in https://github.com/mozmeao/snippets-service/issues/935
- Disabled alarms (synthetics, route53) 
- Manually pushed to `admin` node first, re-run the migration
- Manually pushed to oregon `prod` then, validated that the fix was working
- Same for `frankfurt`
- Completed with merging fix in `production` branch which triggered a full pipeline build and re-pushed everywhere
- Re-enabled alarms (syncthics, route53) which wouldn't have gone off anyway

Result:
- Dropped AVG response time from ~150ms (before yesterday's changes) to ~40ms on both clusters. Fix was good
- Verified replies for multiple locales (en-us, fr, de)
- Images are now links and not included in the snippet bundle
- Bundles now weight *213Kb* (12Kb brotli compressed) for *en-US*, *111Kb* (9.9Kb brotli compressed) for *de*, *104Kb* (8.9Kb brotli compressed) for *fr*
- Previous bundles weighted *1.9M* (442Kb brotli), *1.4M* (234Kb brotli), *1.3M* (182Kb brotli) for the same locales

Wins:
- We expect a significantly smaller CDN traffic bill
- Faster response, less snippets-prod pods, less k8s resources used
- AS and thus Firefox should get faster as the IndexedDB that stores the bundle will get smaller and faster. Also maybe issues like bug 1530714 may disappear with the faster response times.

This one is done!

**Comment by metadave** [comment]
@bensternthal let's keep an eye on snippets CDN costs

**Comment by bensternthal** [comment]
noted!

**Comment by glogiotatidis** [comment]
@bensternthal can we get a first estimation on CDN costs for Apr?

**Comment by bensternthal** [comment]
💰 info sent via email
