### ISSUE TITLE
Fix snippets using JPEGs

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#929]
A few snippets use JPEGs instead of PNGs. JPEGs do not transparency and those images will not work nicely when users have a non default theme selected.

Snippets using JPEG:

- [x] [10548 - MOCO_Global_2019_P100_Mission_IRL S4 E4 V3_SSB_EN_REL_ESR](https://snippets-admin.mozilla.org/admin/base/asrsnippet/10548/change/)
- [x] [10547 - MOCO_Global_2019_P100_Mission_IRL S4 E4 V2_SSB_EN_REL_ESR](https://snippets-admin.mozilla.org/admin/base/asrsnippet/10547/change/)
- [x] [7980 - MOCO_global_2018_f100_week10_campaign_firetv_v1_activity_stream_EN_REL](https://snippets-admin.mozilla.org/admin/base/asrsnippet/7980/change/)
- [x] [7981 - MOCO_global_2018_f100_week14_campaign_firetv_heyalexa_activity_stream_EN_REL](https://snippets-admin.mozilla.org/admin/base/asrsnippet/7981/change/)
- [x] [8419 - MOCO_global_2018_f100_week14_campaign_firetv_heyalexa_activity_stream_DE_REL](https://snippets-admin.mozilla.org/admin/base/asrsnippet/8419/change/)
- [x] [8396 - MOCO_global_2018_f100_week10_campaign_firetv_v1_activity_stream_DE_REL](https://snippets-admin.mozilla.org/admin/base/asrsnippet/8396/change/)

@mozmeao/lcm-team @stsegovia-moz can you please take of those?

**Comment by stsegovia-moz** [comment]
Thanks Giorgos! I'll reach out to the design team and get the PNG/SVG versions of these icons. The bright side is that the IRL snippets are no longer running, but I will still update them.

Thank you! I'll keep you posted when this is done.

**Comment by glogiotatidis** [comment]
You rock! :metal:

**Comment by glogiotatidis** [comment]
I checked the snippets listed above and they are all using transparent PNGs now. \o/

Thanks for taking care of this @stsegovia-moz

**Comment by stsegovia-moz** [comment]
Thank you Giorgos!
