### ISSUE TITLE
Reduce ASRSnippetBundle.key time to execute

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#935]
The `ASRSnippetBundle.key` method is used to decide whether the cached bundle exists and if it's still fresh and thus it gets called often, a lot more compared to the slower `ASRSnippetBundle.generate`.

Metrics taken (on local dev machine) with the Django Profiling app [Silk](https://github.com/jazzband/django-silk) indicate that the time needed to generate a new snippet bundle increased by 70%. Also the time to just return a cached pre-generated bundle doubled. The number of db queries almost doubled and tripled accordingly. 

The new code moves Templates in models so an increase of database queries was expected. Still the response time, especially of `ASRSnippetBundle.key` which handles the vast majority of the requests must be comparable to what we had before.

**Comment by glogiotatidis** [comment]
Pull request #936 fixes the issue with a couple of tricks:
 - Most importantly moves the template.VERSION check outside the loop and to the [app initialization](https://github.com/mozmeao/snippets-service/pull/936/files#diff-deacc399a7637296941b69098876f8f3R54). Template.VERSION is indicates the version of the Template schema and matches the Activity Stream Schema version. Although it was planned to be used for automatic syncing of the two systems, is not used yet. Anyway, since changing templates requires an app restart now, generating this string once on app init is good enough for the service.
 - Moves `Campaign` and `Target` update checks outside `key()` and into the same `post_save` hook Template use. 

These two tricks reduce the response time of generation of new bundles by 10% and it's still 35% slower than the old code, mostly because it executes 30% more db queries (metrics taken on local dev machine). The good news is the response time for cached bundles dropped by an order of magnitude, down to 132ms from 1544ms. That's even better compared to the old template code (748ms). The number of queries dropped from 742 (new template code) and 234 (old template code) to 2 (fix). 

It's suggested that despite that increase bundle generation time, the drastically improved response for cached bundles will bring overall better app performance compared to the past.

|          | time   | time on queries | queries | cached time | cached time on queries | queries |
|----------|--------|-----------------|---------|-------------|------------------------|---------|
| Old code | 1424ms | 526ms           | 698     | 748ms       | 301ms                  | 234     |
| New code | 2456ms | 907ms           | 1222    | 1544ms      | 557ms                  | 742     |
| Fix      | 2208ms | 974ms           | 990     | 132ms       | 81ms                   | 2       |

**Comment by glogiotatidis** [comment]
Fixed pushed to production. As expected the improved key generation time behaves way better

Frankfurt
![image](https://user-images.githubusercontent.com/584352/55065313-441a7300-5084-11e9-8560-854bb2562b2c.png)

Oregon
![image](https://user-images.githubusercontent.com/584352/55065350-572d4300-5084-11e9-95f5-c8f30b6a900d.png)

The AVG response time of the service is less than half now \o/

**Comment by jgmize** [comment]
nice work @glogiotatidis!
