### ISSUE TITLE
Snippet Text Wrapping is Not Fit to Design Standards

### ISSUE THREAD

**Issue by stsegovia-moz** [mozmeao/snippets-service#945]
I just received this issue via the #snippets slack channel. It's an aesthetic/design issue, but not   not an urgent fix.  

The photon design system recommends about 70 characters per line. Currently our snippets create line break after  ~155 characters in the first line. 

Aside from following branding guidelines, it looks a bit off. There's so much text in the first line, yet so little in the 2nd line. 

Can you set the snippet text wrap character limit to 70-80 characters per line? That would help us comply with design standards and appear a bit more visually pleasing.. 

Perhaps we can test this in staging to be sure it doesn't cut off text before we roll it out to production. 

**Example of current snippet** 
<img width="1280" alt="Screenshot 2019-03-30 at 19 02 01" src="https://user-images.githubusercontent.com/47153345/55355772-1e271100-547e-11e9-8ce7-1e1b83c80e69.png">

**Design Guidelines**
https://design.firefox.com/photon/visuals/typography.html#line-length

**Comment by glogiotatidis** [comment]
This is how AS implements this template. I'll bring the issue to the AS - Snippets mtg to discuss options.

Thanks for reporting!

**Comment by stsegovia-moz** [comment]
Thank you!

**Comment by jkt230** [comment]
Giorgos is going to check if we can do <br> tags.

@stsegovia-moz UX suggested that we try having the first sentence as the headline title.

**Comment by glogiotatidis** [comment]
> Giorgos is going to check if we can do
> tags.

Yes you can use `<br/>` tags in HTML fields. The field help will help you identify the fields that support the tag.

![image](https://user-images.githubusercontent.com/584352/55861581-506ff700-5b7f-11e9-9dce-e7eb50b8c66e.png)

**Comment by glogiotatidis** [comment]
Since `<br>` is supported this doesn't look like a technical issue of the snippets service. If we need templates to be changed to display text differently I believe that belongs to another issue.

Thanks!

**Comment by stsegovia-moz** [comment]
I think a <br> is ok as a temporary fix, but if someone were to resize their window, the break may not look very smooth (see screenshots). 

Here's an example of the break in a normal window size
![Screen Shot 2019-04-10 at 9 04 13 AM](https://user-images.githubusercontent.com/47153345/55895125-60cca580-5b70-11e9-8352-3af140eb87b3.png)

Here is an example of the break with a resized/smaller window. 
![Screen Shot 2019-04-10 at 9 04 22 AM](https://user-images.githubusercontent.com/47153345/55895143-675b1d00-5b70-11e9-8992-5db4f0503763.png)

Here are similar examples when using the title for the first line. 
![Screen Shot 2019-04-10 at 9 05 55 AM](https://user-images.githubusercontent.com/47153345/55895198-82c62800-5b70-11e9-9ebd-8fa5157f2e70.png)
![Screen Shot 2019-04-10 at 9 06 03 AM](https://user-images.githubusercontent.com/47153345/55895202-85c11880-5b70-11e9-8555-9bf3ebaa2f77.png)


If you look closely, you can see that when a user adjusts the width of the break causes an awkward flow of the text. This is because the break is within the copy itself and remains in a specific part of the copy. 

Whereas text wrapping limit would be a constraint within the text box that helps the overall copy break to fit within the box.

We can definitely us the <br> tag for breaks temporarily and see if we encounter any issues, but I anticipate these issues with how it displays when resizing windows.

**Comment by glogiotatidis** [comment]
I see what you're saying. I believe @jkt230 said in the mtg that she'll file a bug report for a template change for the AS team.

@jkt230 can you please link to the bug here?

**Comment by jkt230** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1543769
