### ISSUE TITLE
Option To Change or Remove Icon from Snippet

### ISSUE THREAD

**Issue by stsegovia-moz** [mozmeao/snippets-service#946]
Hi Giorgos,

As now, there is no way to remove/change an icon from a snippet. The only way to change a snippet is to upload a new icon, but that overwrites the icon for all other snippets using that previous icon.

Can you create an option for changing/removing snippets without these consequences? Thank you!

![Screen Shot 2019-04-01 at 1 29 10 PM](https://user-images.githubusercontent.com/47153345/55357591-339e3a00-5482-11e9-9d71-31c4f978e0e7.png)

**Comment by glogiotatidis** [comment]
We discussed with Steve how the gallery is designed to work and we agree that changing an icon for a snippet would require creating a new icon gallery entry.
