### ISSUE TITLE
Migrate to PostgreSQL

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#954]
See also https://github.com/mozmeao/infra/issues/1041

Code changes:
 - [x] Update `Dockerfile` to include postgres libs `libpq-dev` and tools `postgresql-client`
 - [x] Update `requirements.txt` to include `psycopg2`
 - [x] Update Travis Tests
 - [x] Update Jenkins Tests

Migration plan:
 - [x] ~~Discuss a read-only timeframe with the OMN team~~ finished in EEST morning. timezones ftw
 - [x] Set `ENABLE_ADMIN=False` on snippets-admin
 - [x] Capture responses for `en-US`, `fr`, `de` on `release` channel
 - [x] Migrate
 - [x] Set `ENABLE_ADMIN=True` on snippets-admin
 - [x] Capture responses for `en-US`, `fr`, `de` on `release` channel and confirm that they are identical with the responses captured before the migration

**Comment by glogiotatidis** [comment]
@jgmize if it's not a big trouble I'd like to migrate to pgsql on AWS first and make sure that everything works fine. Then you can take over and do your GCP migration at your own pace.

For this to work I'd need a pgsql master instance on oregon with a frankfurt read replica. Same setup as we have for MariaDB. I don't mind re-using existing pg instances as long as they have enough power to keep up with snippets.

What do you think about this plan? If you're onboard, can you please provide said pg instances?

**Comment by jgmize** [comment]
Hi @glogiotatidis, I discussed this with @metadave yesterday and I'll work on provisioning a new psql RDS instance in oregon with a read replica in Frankfurt via terraform later today.

**Comment by glogiotatidis** [comment]
Many thanks!

**Comment by glogiotatidis** [comment]
aaaaaand done!

**Comment by stsegovia-moz** [comment]
Sweet! Thank you!
