### ISSUE TITLE
New Firefox Monitor Snippet Template (Using FxA Sign Up Widget)

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#957]
Hi Giorgos,

Got a request from the FxA growth team to create a Firefox Monitor template using the same widget we have for FxA sign up on snippets.

Is it possible to just recreate the template but update it with the correct Firefox Monitor url and info? If so, I'll need to coordinate with Sandy Sage to get a better idea of what url and parameters we need. 

The bug we used for FxA sign up widget to refresh our memories: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1423414

**Comment by jkt230** [comment]
Got an update from Shane T. 

" This snippet would actually have to work different for monitor since its an FxA oauth client (sync isn't). Shane/Vlad/Luke can speak to whether or not it would be possible to link directly into the monitor FxA oauth flow through a snippet - it may be best to link to the monitor site instead (although that would be adding an extra step for the user so the snippet probably wouldn't convert as well).



The answer is no. Linking directly to FxA to sign into Monitor from a snippet will not work, easily, and this is intentional. 
An OAuth flow requires a `state` token, the state token is meant to prevent Cross Site Request Forgery (CSRF), and while this wouldn't exactly be a Forgery, it would appear to be one.

The way CSRF is supposed to be prevented in an OAuth world is like this:

    On Monitor, before the user redirects to FxA, Monitor creates a state token and binds that state token to the user's session.
    Monitor then redirects to FxA with the state token.
    Upon authentication, FxA redirects back to Monitor with the state token and an OAuth code.
    Monitor checks the state token to ensure it matches the one expected for the user's session. If not, then Monitor should refuse to accept the OAuth code because it doesn't know if the user is the party that actually initiated the login.

Now, it's might be possible for there to be some sort of back channel communication to establish a state token, but that seems like it'd be convoluted and brittle.

Better would be to for the snippet link to a page on Monitor that verifies somehow the request is legit and came from a valid snippet (otherwise, the endpoint *could* be used for CSRF), creates and binds a state token to the user's session, then redirects to FxA."

I am letting Michele Warther know and will loop back to close this issue.

**Comment by glogiotatidis** [comment]
Closing this per comment 2
