### ISSUE TITLE
Lockwise, Pocket and Notes  Add-On Filtering

### ISSUE THREAD

**Issue by stsegovia-moz** [mozmeao/snippets-service#966]
As we ramp up snippets promoting Lockwise (formerly Lockbox), Pocket, and Notes as features for Firefox Accounts, we will need to filter out users who already have these features installed on their browser.

Can you add add-on filtering capabilities for:

- Pocket
- Lockwise
- Notes

**Comment by glogiotatidis** [comment]
I added a comment to further discuss this since Pocket and Lockwise are not add-ons

**Comment by glogiotatidis** [comment]
Notes is already available for targeting under the `Browser Add-on` Target

![image](https://user-images.githubusercontent.com/584352/57220382-d9097800-7003-11e9-8790-f7c236121091.png)

**Comment by stsegovia-moz** [comment]
Ah, thank you for clarifying. That's helpful.

**Comment by glogiotatidis** [comment]
I think for pocket and lockwise we'll need to develop extra targets based on #979

Since add-on level targeting for notes is avail i'll close this one
