### ISSUE TITLE
Add more snippet weight options

### ISSUE THREAD

**Issue by stsegovia-moz** [mozmeao/snippets-service#967]
Giorgos, as we talked about in our last Tuesday meeting, we may want lower weights for snippets available, specifically for when we want to test new snippets.

This would allow us to test snippets with a lower rotation that would not disrupt the overall content users view. Thanks!

Would it be possible to add in these weights:
1/10 (10%)
1/20 (5%)
1/40 (2.5%)

**Comment by glogiotatidis** [comment]
Sure, I'll go ahead and add those additional options.

**Comment by glogiotatidis** [comment]
Can add 
 
 - 1/10
 - 1/20
 - 1/50 (instead of 1/40 due to technical reasons) 

Let me know if that's ok @stsegovia-moz ?

**Comment by stsegovia-moz** [comment]
Yes, that works. Thank you!
