### ISSUE TITLE
Target based on used FxA services

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#979]
Heads up that I've made a request to expose more FxA attributes for targeting:

https://bugzilla.mozilla.org/show_bug.cgi?id=1547120

**Comment by glogiotatidis** [comment]
Blocked until fixed on ASR. 

/remind me to check in 3 weeks

**Comment by glogiotatidis** [comment]
Not fixed in ASR.

/remind me to check in 4 weeks

**Comment by glogiotatidis** [comment]
No progress in the bug yet

/remind me to check in 4 weeks

**Comment by glogiotatidis** [comment]
/remind me to check in 1 week

**Comment by glogiotatidis** [comment]
Also https://bugzilla.mozilla.org/show_bug.cgi?id=1550720

**Comment by glogiotatidis** [comment]
This is scheduled for Firefox 70. We will start beta testing on 2019-09-02.

/remind me to code snippets service changes on Aug 26th

**Comment by glogiotatidis** [comment]
It seems that https://bugzilla.mozilla.org/show_bug.cgi?id=1547120 hasn't been picked up by FxA team and it blocks https://bugzilla.mozilla.org/show_bug.cgi?id=1550720.

Andrei will ping FxA team to put bug on their radar again.

/remind me to check in 3 weeks.

**Comment by glogiotatidis** [comment]
There's some progress in the bug, yet to be fixed. 

/remind me to check again in a week

**Comment by jkt230** [comment]
Heads up that this bug was "fixed" but unclear on timeline: https://bugzilla.mozilla.org/show_bug.cgi?id=1547120

**Comment by glogiotatidis** [comment]
Bug 1547120 is the FxA bug which was fixed. Now the Activity Stream / Firefox side needs to be fixed in [bug 1550720](https://bugzilla.mozilla.org/show_bug.cgi?id=1550720) 

I talked with AS team and that's on tracked to be delivered in Fx71

**Comment by glogiotatidis** [comment]
/remind me to check status in 10 days

**Comment by glogiotatidis** [comment]
AS bug is still unresolved. Will check again in a week 

/remind me to check in a week
