### ISSUE TITLE
 Make mobile device sync attribute available to snippet admin service for targeting via AS Router

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#980]
Can we do this one as soon as possible? Assuming it's ready for you to add to the service?

https://bugzilla.mozilla.org/show_bug.cgi?id=1547112

Use case:

We would make sure not to show mobile promotion snippets to those who are synced on a mobile device (we are then assuming they have already downloaded the Firefox app).

**Comment by glogiotatidis** [comment]
Duplicate of #694 and #695

**Comment by glogiotatidis** [comment]
Will add to the queue.
